### ISSUE TITLE
New Collective Page V2 Feedback

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2225] opened 2019-07-09 22:32 UTC
This issue is where we will be collecting feedback from the team and community about the newly redesigned Collective page.

To see a preview of the new Collective page design, append "v2" to the end of any Collective URL.

Examples:

* https://www.opencollective.com/webpack/v2
* https://www.opencollective.com/babel/v2

The person leading this implementation is @Betree - he will be monitoring this thread and taking feedback on board.

**Comment by alanna** [comment] 2019-07-09 22:49
I have some comments myself...

1. What will happen to the design when a Collective has multiple tags? I think we're going to be using tags more and more in the system going forward.

![Screen Shot 2019-07-10 at 10 33 04 AM](https://user-images.githubusercontent.com/5498878/60927506-497f8e80-a2fe-11e9-82e4-538f1fa93735.png)

2. I seem to remember from the design that there is a 'short description' section at the top of the page, under the title and Collective tagline. Is that right? Because while I think it's good not to put a huge amount of text at the top, right now the "About" info is too hidden. Will we be telling Collectives to fill out the short description field to put a few sentences at the top?

3. I don't think the "custom contribution" should be ordered as the first tier, because that means the very first text a potential contributor reads is "Nothing there for you?" which is kind of negative. Can we put that one at the end, so users first look at the Collective's suggestions and only goes custom if nothing fits.

4. It would me more engaging if all the action buttons were colored in instead of white. (e.g. contribute, contact, submit expenses).

5. For Collectives with Updates, "Updates" is the second nav menu item, but scrolling down the page it's actually the third section, under contributors. I think the order should match.

6. Section headings should match menu items. So if the menu says "budget" the section should be "budget" not "transactions".

7. Where is the "edit Collective" link?

8. I assume the images in the tier cards will be changeable by Collectives? I think it would be more fun and engaging if we put default photos in there, instead of this grey money icon. It would also show Core Contributors ideas of what it can look like if they replace it with their own image.

![Screen Shot 2019-07-10 at 10 44 27 AM](https://user-images.githubusercontent.com/5498878/60928007-e7278d80-a2ff-11e9-9e2f-2732d9c61191.png)

9. I know we're planning to give each tier its own page. Is that coming in a future iteration? Right now it sends you straight to the contribution flow if you click a tier.

10. The help text in the budget section could be improved. How about:

> See where our money comes from and where it goes, transparently. Submit an expense to get paid for your contributions to [Collective].

**Comment by Betree** [comment] 2019-07-10 00:19
Thanks for opening this @alanna! I'm assigning @raulgrafico as well because a lot of the feedback will involve the design team. I've added below replies for the points where I have some things to say and let aside pure design feedback for @raulgrafico or @cuiki.

> 1. What will happen to the design when a Collective has multiple tags? I think we're going to be using tags more and more in the system going forward.

Right now we only show the "main tag".

<details>
<summary>Details about how we find out the main tag</summary>

- If host is OSC ==> `OPEN SOURCE`
- Otherwise if the collective has no tags ==> `COLLECTIVE`
- If the collective has tags, we take the first one matching a value in the following map:

```es6
export const CollectiveCategory = {
  ASSOCIATION: 'association',
  COLLECTIVE: 'collective',
  CONFERENCE: 'conference',
  COOPERATIVE: 'coop',
  OPEN_SOURCE: 'open source',
  MEDIA: 'media',
  MEETUP: 'Meetup',
  MOVEMENT: 'movement',
  POLITICS: 'politics',
  TECH_MEETUP: 'Tech meetups',
  US_NONPROFIT: '501c3',
};
```

</details>

> 2. I seem to remember from the design that there is a 'short description' section at the top of the page, under the title and Collective tagline. Is that right? Because while I think it's good not to put a huge amount of text at the top, right now the "About" info is too hidden. Will we be telling Collectives to fill out the short description field to put a few sentences at the top?

The tagline is in fact the short description. They may have been a longer on the design in the past but not in the current version. I agree that the about section is really not visible and that is going to be a problem for some collectives.

A possible answer that we can also give is the ability to change sections order in collective's settings (we're just missing the admin UI for it). With it collectives can bring the about section up. 

> 3. I don't think the "custom contribution" should be ordered as the first tier, because that means the very first text a potential contributor reads is "Nothing there for you?" which is kind of negative. Can we put that one at the end, so users first look at the Collective's suggestions and only goes custom if nothing fits.

100% agree. Also I think that an increasing number of collectives are going to need #2183 that solves the issue too.

> 4. It would me more engaging if all the action buttons were colored in instead of white. (e.g. contribute, contact, submit expenses).

I wouldn't do that for all the buttons but I think too that the `Contribute` buttons should use the `primary` color as this is our main call to action. Also because collectives can now set a primary color for their page, this create a real identity there.

<details>

![Screenshot_2019-07-10 Collective - Open Collective(1)](https://user-images.githubusercontent.com/1556356/60930476-fbdf3380-a2b5-11e9-9f52-5e2fc6f2ffc0.png)

</details>

> 5. For Collectives with Updates, "Updates" is the second nav menu item, but scrolling down the page it's actually the third section, under contributors. I think the order should match.

`Top contributors` is actually not a real section, it's part of the "Contribute" section and has no entry in the NavBar. The real contributors section is after the budget.

> 7. Where is the "edit Collective" link?

<details>

![image](https://user-images.githubusercontent.com/1556356/60930844-b885c480-a2b7-11e9-9429-cdba098663cd.png)

</details>

> 8. I assume the images in the tier cards will be changeable by Collectives? I think it would be more fun and engaging if we put default photos in there, instead of this grey money icon. It would also show Core Contributors ideas of what it can look like if they replace it with their own image.

Yes, that's #1980. Can you provide examples of default photos that could illustrate tiers?

> 9. I know we're planning to give each tier its own page. Is that coming in a future iteration? Right now it sends you straight to the contribution flow if you click a tier.

The `Contribute` button always sends you directly to the contribution flow. To reach the tier page, you have to click on `Read more` (only appears if the tier has a long description).

<details>

![image](https://user-images.githubusercontent.com/1556356/60931079-9e98b180-a2b8-11e9-86ca-1d71618d54ff.png)

</details>

> 12. I think the "all of us" section should actually default to showing core contributors first. Because right now the info displayed is redundant to the "Top contributors" section just above. I also think some people might not immediately get what "core contributor" means, but if they see the team members displayed first thing, they will get it.

Good point.

**Comment by piamancini** [comment] 2019-07-10 07:24
Adding @dodgepong's comments here as well for record. 

The contrast in the top contributors section seemed hard on the eyes, felt noisy

<details>
![image (4)](https://user-images.githubusercontent.com/3671070/60948646-b7728880-a2f3-11e9-8fa7-683f6cc410ce.png)
</details>

one user had this issue on the mobile view
<details>
![image (5)](https://user-images.githubusercontent.com/3671070/60948685-cd804900-a2f3-11e9-9acc-fee01da2fc20.png)
</details>

Generally it felt like the layout suffered from "designed on a wide monitor" syndrome. especially how you have to scroll horizontally to see all the tiers. 

Some smaller displays had issues with the "Our Contributors" section, where it would not fit vertically or horizontally, meaning he had to scroll each direction constantly

Personally from a sales perspective, I felt like the "About" section being on the bottom was out of place, like making the sales pitch the least important part of the page

The "_____ is all of us" header seemed overly large

The overall impression was that it was "very white"

I do like that you can see the messages people left when contributing -- I didn't even know those existed with the old system. It would be nice if those messages were in the notification email we got when someone contributed 

Companies/orgs that don't have square/circle logos seem to suffer as well as companies with white logos

**Comment by piamancini** [comment] 2019-07-10 07:51
Feedback from Democracy Earth: 

'Why we do what we' do seems out of alignment with the rest of the page. Everything is to the left and that's at the center. 

Background image behind logo is broken in mobile
<details>
![IMG_0785](https://user-images.githubusercontent.com/3671070/60950827-2fdb4880-a2f8-11e9-818c-9f5d6bd32c36.jpeg)
</details>

**Comment by Betree** [comment] 2019-07-10 07:53
> Background image behind logo is broken in mobile

This one is a fixed by https://github.com/opencollective/opencollective-frontend/pull/2109 that will be deployed today.

**Comment by yellowwoods12** [comment] 2019-07-11 03:59
The number of contributors card in a row should be less and equal to the number that can fit in the screen along with a margin on the right. This will look much better.
![Screenshot_2019-07-11 Collective - Open Collective](https://user-images.githubusercontent.com/31931348/61021251-5368c680-a3be-11e9-99ca-e61e60923f64.png)

**Comment by Betree** [comment] 2019-07-11 06:30
@yellowwoods12 The horizontal scroll is a choice that design team made to be able to see all the contributors of a collective, even when there are hundreds of them. If we only show a subset of them then we loose the ability to see all collective's contributors in one place. There may be things we can improve on the implementation side for this one, but I think the design for it is clever.


![Peek 11-07-2019 08-23](https://user-images.githubusercontent.com/1556356/61026964-3380d500-a3b5-11e9-9f40-9373e2446e45.gif)

A way to improve that would be to not show any padding on the left if the grid is full.

On your screenshot the navbar seems to appear on the middle of the screen, is it a bug you encountered or a problem with Firefox's integrated screnshot feature?

**Comment by yellowwoods12** [comment] 2019-07-11 07:39
@Betree Sure I get it. But can't we create paging instead of horizontal scrolling according to the time period in which a particular person became a contributor. That will be a more standard way to do this I guess, isn't it?
The navbar in the middle is just an issue with the Firefox's screenshot feature not a bug.

**Comment by alanna** [comment] 2019-07-15 00:16
White logos are not showing up well.

![Screen Shot 2019-07-15 at 12](https://user-images.githubusercontent.com/5498878/61191099-5cc59c00-a6fa-11e9-9d1e-9fc3a0da8bcc.jpg)

**Comment by alanna** [comment] 2019-07-15 00:23
Collective description text should line break before overlapping the background image.

![Screen Shot 2019-07-15 at 12 22 39 PM](https://user-images.githubusercontent.com/5498878/61191187-4d931e00-a6fb-11e9-82a4-c27903155721.png)

**Comment by alanna** [comment] 2019-07-15 04:52
There's too much redundant language in the contribute section. 

We could make "Become a financial contributor" the section title, delete the current section title, lose the blue 'contribution' badges, and make the tier title what goes on the button. Viola, a whole lot less text, a much simpler design, and no information lost.

![Screen Shot 2019-07-15 at 4 48 54 PM](https://user-images.githubusercontent.com/5498878/61196184-eab47d80-a720-11e9-836b-7f371b0b92a6.png)

**Comment by kthull** [comment] 2019-07-16 17:22
The user menu is currently underneath the header image:
<img width="550" alt="Screen Shot 2019-07-16 at 1 21 15 PM" src="https://user-images.githubusercontent.com/984057/61315432-bb5b4a80-a7cc-11e9-93a0-8d7a78f97db6.png">

**Comment by staltz** [comment] 2019-07-16 17:44
Looks nice! Two things I noticed:

- The sticky header is huge and is consuming space to read content
- The hero picture is not entirely shown (I guess I could redesign the hero picture, though)

**Comment by NoWorries** [comment] 2019-07-16 22:17
- These cards are different heights across three tabs:

![image](https://user-images.githubusercontent.com/803064/61333612-92de5980-a87b-11e9-92be-b765ac4a86eb.png)

- Core Contributors tab doesn't have background image:

![image](https://user-images.githubusercontent.com/803064/61333686-d46f0480-a87b-11e9-986a-0fed7fd0c12c.png)

- Menu active state not working consistently

![Jul-17-2019 10-16-37](https://user-images.githubusercontent.com/803064/61333747-1304bf00-a87c-11e9-9cdc-2a70eb7838c8.gif)

**Comment by jfdh** [comment] 2019-07-17 08:33
Very satisfied with the overall redesign.
Two things:
- What about the redesign of host organisations? I can't see the collectives we are hosting on this screen
- I am also missing the dashboard button. Is there a new design for the dashboard btw?
![Screenshot 2019-07-17 at 10 29 22](https://user-images.githubusercontent.com/30813303/61360004-d8038b00-a87d-11e9-9360-815ebf3dbcb1.png)

Thanks for the good work! I look forward to make the best out of it.

**Comment by Betree** [comment] 2019-07-17 08:46
@NoWorries 

> These cards are different heights across three tabs

As we make all cards the same height, the longest one will define the size. In the case of babel, the last one has a long description:

![image](https://user-images.githubusercontent.com/1556356/61360992-e2268900-a87f-11e9-8d84-cd5859409440.png)

---

@jfdh, thanks for mentioning these issues. I'll make sure we prioritize this so hosts don't loose precious info when we roll out the page.

**Comment by NoWorries** [comment] 2019-07-17 21:26
@Betree 
> > These cards are different heights across three tabs

Ah sorry ignore that one then, I was scrolling through the three side by side and didn't check the content across the carousels.

**Comment by alanna** [comment] 2019-07-18 00:12
@Betree I am also interested in clarification about @jfdh 's question above about the design for host pages. I didn't think about how this would affect host and organization pages as the focus was on Collectives. There are a lot of issues that will need to be fixed for hosts before this goes live.

A few I noticed:

* Should not include the 'budget' section (I would love for hosts to have full Collective budget functionality but I think it's out of scope for this project)
* Must feature the "Apply" button
* Where is the link to the dashboard?
* Can hosts do Updates now? If not, remove that section.
* Contributor section doesn't make much sense for a host page, as it's only going to show core contributors not financial contributors (Again I would love it if there was no need for a deperate default Collective for a host but right now that's where financial contributions go).
* Needs to display the hosted Collectives

**Comment by Betree** [comment] 2019-07-18 07:25
@alanna The design team already worked on this by providing a design that will work for Users/Organizations/Hosts: https://www.figma.com/file/e71tBo0Sr8J7R5n6iMkqI42d/OC.COM-04-%2F-Collectives-%E2%86%92-Create%2C-Edit?node-id=3889%3A145

But these two points remain:
- Must feature the "Apply" button
- Where is the link to the dashboard?

**Comment by piamancini** [comment] 2019-07-18 10:32
background image overflows designated space? opencollective.com/osc/v2
<img width="1273" alt="Screen Shot 2019-07-18 at 12 30 31 PM" src="https://user-images.githubusercontent.com/3671070/61450751-0a81b680-a958-11e9-8258-0e96f1bc9d7e.png">

**Comment by Betree** [comment] 2019-07-18 11:00
@piamancini The background image don't have the same dimensions on this page that it used to, we'll have other cases like this (though this one looks really bad). Stretching to the size would not work because we'll end up with strange images:

![image](https://user-images.githubusercontent.com/1556356/61452043-2470c880-a95b-11e9-9709-a4c6ae5d7a95.png)

What we've discussed with @raulgrafico to solve this one is to add the ability to change position/zoom/crop when you edit the image, similar to what you have on facebook/twitter:

![Peek 18-07-2019 12-58](https://user-images.githubusercontent.com/1556356/61452296-c09acf80-a95b-11e9-80bc-9d2ee4a539ca.gif)

**Comment by alanna** [comment] 2019-07-18 22:29
Thanks for that link @Betree - I have looked at the designs for User, Organization, and host pages and added comments. In the future it would be great if I were told about these designs and asked for feedback proactively, so I can suggest changes earlier in the process.

**Comment by Betree** [comment] 2019-07-19 10:28
@alanna I don't think that @raulgrafico is done with these designs, I guess that's why they didn't communicate more about them. But I share the same feeling, I'd love to be notified when things are ready for reviews then ready for implementation. I usually have to make assumptions for this.

**Comment by alanna** [comment] 2019-07-22 03:36
Looks like Facebook is pulling through the host's image instead of the Collective's image when linking to a Collective page. I think it should probably pull through the header image.

<img width="495" alt="Screen Shot 2019-07-22 at 3 33 40 PM" src="https://user-images.githubusercontent.com/5498878/61604597-4b4e3800-ac96-11e9-8889-c1970b55bdc9.png">
<img width="501" alt="Screen Shot 2019-07-22 at 3 33 16 PM" src="https://user-images.githubusercontent.com/5498878/61604598-4b4e3800-ac96-11e9-9e44-f7dc959b8ed7.png">

**Comment by Betree** [comment] 2019-07-22 11:49
@alanna That's a bug linked to the avatar refactor, we normally take the collective image and fallback on the host image if it's not available. Will fix.

**Comment by alanna** [comment] 2019-07-23 23:11
@Betree Did you intend to close this issue? Let's leave it open throughout the launch to collect feedback. (Sorry if I'm misunderstanding something here but I'm going to go ahead and reopen it).

**Comment by Betree** [comment] 2019-07-24 06:22
@alanna it was a mistake, GitHub auto-closed it because https://github.com/opencollective/opencollective-frontend/pull/2230 had "resolve" in the description. Thanks for re-opening

**Comment by CheesePwn** [comment] 2019-08-20 08:54
This is really good! Only one issue though, markdown is completely broken on tiers. Where you could actually use markdown in v1 of tiers, you can't now. Is that intentional?

v1:

![](https://i.imgur.com/vmBbMwF.png)

v2:

![](https://i.imgur.com/j2nBMDQ.png)

Also it seems you can't view who has pledged to which tier anymore. 

Thanks for the incredible work on OpenCollective over the years. I'm really digging v2.

**Comment by Betree** [comment] 2019-08-20 10:28
> This is really good! Only one issue though, markdown is completely broken on tiers. Where you could actually use markdown in v1 of tiers, you can't now. Is that intentional?

@CheesePwn The use of markdown in v1 was undocumented, I'll bring up the topic but there's good chances that we're going to get rid of this behavior to incentive a new way of presenting things: you can now attach goals and rich descriptions to tiers, which results in a page where you can add as much text as you want, images, a video -- everything you need to describe the contribution :slightly_smiling_face: 

<details>

![image](https://user-images.githubusercontent.com/1556356/63339044-4daebb00-c344-11e9-9e4d-5a6ca8d0512b.png)

![localhost_3000_open-potatoes_tiers_to-the-moon-2807 (6)](https://user-images.githubusercontent.com/1556356/59099321-13c44000-8923-11e9-8283-1d93f99e2fa8.png)

</details>

> Also it seems you can't view who has pledged to which tier anymore.

This one is yet to come, final design will look like this:

![image](https://user-images.githubusercontent.com/1556356/63339602-8bf8aa00-c345-11e9-8544-f0569e93acbc.png)

> Thanks for the incredible work on OpenCollective over the years. I'm really digging v2.

Thank you so much, that's very kind! @opencollective/design and especially @raulgrafico worked hard on this :pray:

**Comment by CheesePwn** [comment] 2019-08-20 10:46
> Thank you so much, that's very kind! @opencollective/design and especially @raulgrafico worked hard on this 🙏

You're doing great work @Betree. Thanks for the updates. That's actually more than enough to what I was expecting!

**Comment by simonmichael** [comment] 2019-09-16 23:01
Congrats in advance! Here's a bug I found:
- using firefox 70 on mac
- click Edit main color
- in the colour field, start typing the color name "midnightgreen"
- after the "g", you get a "crash": "Ooops, an unexpected error seems to have occurred  🤕"

and a feature request: the # suggests this field will only accept hex codes, it would be nice if it accepted color names (or full CSS color value syntax ?)

**Comment by Betree** [comment] 2019-09-17 05:55
@simonmichael thanks for testing that! We'll make sure this gets fixed before the release

**Comment by piamancini** [comment] 2019-09-23 15:10
NCP has been released! 
Closing this issue in favor of #2445.

**Closed by piamancini** 2019-09-23 15:10 UTC
Labels: collective page v2, discussion
