### ISSUE TITLE
Event pages not featuring sponsors

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3644] opened 2020-10-28 20:36 UTC
I'm not sure if this is a bug, a regression, or working as intended.

Currently, event sponsors/financial contributors aren't really being shown in the event page design. For example on [this event](https://opencollective.com/mauticon-2020-aa109fa5) they only appear as tiny icons on the contribution card.

![Screen Shot 2020-10-29 at 9 33 50 AM](https://user-images.githubusercontent.com/5498878/97493536-f84f4e80-19c9-11eb-92f5-ce81ee9c58aa.png)

Looking at the `profile page` settings for an event, it seems like you're not able to activate the `contributors` section, which would show the leaderboard and highlight the sponsors. That section is just missing from the list.

![Screen Shot 2020-10-29 at 9 30 58 AM](https://user-images.githubusercontent.com/5498878/97493643-26cd2980-19ca-11eb-959c-0366fee2d704.png)

I think this is not great because event sponsorship is a major way money comes into many events and a very important aspect of the feature, which is meant to be a combination of event functionality, budget functionality, and transparency about funding.

**Comment by znarf** [comment] 2020-12-09 14:52
Currently for Events, we display "Sponsors" in the "Participants", it's the historical behavior.

<img width="1242" alt="Screenshot 2020-12-09 at 15 51 46" src="https://user-images.githubusercontent.com/806/101645271-775a8c80-3a36-11eb-843c-3023ea6f15ce.png">

**Comment by znarf** [comment] 2020-12-09 19:49
This issue seems a duplicate of https://github.com/opencollective/opencollective/issues/3637

**Closed** 2020-12-10 07:33 UTC
Labels: support
