### ISSUE TITLE
Settings: clicking on `Add Tags` scrolls to top

### ISSUE THREAD

**Issue by snitin315** [opencollective/opencollective#4011] opened 2021-02-24 02:25 UTC
**Describe the bug**

On the user settings page, when clicking on `Add Tags`, the window gets scrolled to the top.

**To Reproduce**
1. Go to '/user/edit'
2. Click on `Add Tags` at the bottom.
3. See error.

**Expected behavior**

Scrolling should not happen.

**Screenshots**

https://user-images.githubusercontent.com/46647141/108938106-791b1000-7675-11eb-8d8c-df66514f4bbb.mp4

**Desktop (please complete the following information):**

Any

**Smartphone (please complete the following information):**
Any
**Additional context**

None

**Comment by sridhar02** [comment] 2021-03-31 16:35
@Betree I have checked the issue, I am unable to reproduce it in my local machine or on production site, i think this issue fixed, may be you can close it, if you are able to reproduce it let me know i can work on it

**Comment by SudharakaP** [comment] 2021-03-31 16:40
@snitin315 : Yes, this is resolved by, https://github.com/opencollective/opencollective-frontend/pull/6058. 😄

**Closed by SudharakaP** 2021-03-31 16:40 UTC
Labels: bug, complexity → simple, frontend
