### ISSUE TITLE
Allow flexible contributions to tiers

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3720] opened 2020-11-24 21:47 UTC
I created a tier and set it to `flexible` but it still forces you the choose the frequency (`one off` `monthly` `yearly`). When I set it to one-off and then tried to switch to a recurring contribution, it gave me an error. We should allow admins to set up these tiers however they need, including fully flexible between one-off or recurring. (This was a standalone page tier but I'm not sure that matters?)

<img width="665" alt="Screen Shot 2020-11-25 at 9 40 28 AM" src="https://user-images.githubusercontent.com/5498878/100155060-717b8c00-2f0b-11eb-9212-1cc39a3babb8.png">

**Comment by Betree** [comment] 2020-12-24 08:52
As a potential fix, we could add a `Flexible` option in the `Interval` select to bypass the validations on this field.

![image](https://user-images.githubusercontent.com/1556356/103076161-66c91b00-45cd-11eb-87c1-64b0aec9de68.png)

**Comment by snitin315** [comment] 2020-12-24 09:44
@Betree can this be a bounty? I would like to work on this one.

**Comment by snitin315** [comment] 2021-01-11 15:41
@Betree can you provide specs ? I would like to work on this one.

**Comment by Betree** [comment] 2021-01-11 15:53
If we go with https://github.com/opencollective/opencollective/issues/3720#issuecomment-750811427, the first step would be to add the `flexible` option in https://github.com/opencollective/opencollective-api/blob/master/server/models/Tier.js#L182 and to provide this new value in the API. Then we must adapt the [contribution flow](https://github.com/opencollective/opencollective-frontend/blob/node-14-2/components/contribution-flow/StepDetails.js#L219) to accept any kind of `interval` if the tier interval is set to flexible. We'll also need to add the value to `components/edit-collective/sections/Tiers.js`.

Finally, we'll need to look for all the places using `tier.interval` to prevent the side-effects of this change. For example [here](https://github.com/opencollective/opencollective-api/blob/master/templates/emails/collective.monthlyreport.hbs#L193), we don't want to display `$40 per flexible` in the email.

I'll let @znarf confirm these specs first, it's an important change in the model so having a second opinion on this is better.

**Comment by znarf** [comment] 2021-01-22 08:30
@znarf Looks good to me!

**Comment by Betree** [comment] 2021-03-15 08:22
:gift: :money_with_wings: A **$300** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $300 when the Pull Request is reviewed, accepted and merged.

Because of its complexity, this issue is reserved to members of https://github.com/orgs/opencollective/teams/recurring-contributors and https://github.com/orgs/opencollective/teams/confirmed-contributors.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by Betree** [comment] 2021-04-06 16:37
:trophy: This issue has been completed by @snitin315  

To claim the bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)

**Closed** 2021-04-06 16:37 UTC
Labels: $300, api, bounty, complexity → medium, feature, frontend
