### ISSUE TITLE
Unable to Verify using Github

### ISSUE THREAD

**Issue by dreygur** [opencollective/opencollective#6186] opened 2022-11-24 06:44 UTC
Unable to Verify using Github

**To Reproduce**
1. Go to 'https://opencollective.com/opensource/apply/intro'
2. Click on 'Verify using GitHub'
3. Click on 'Approve'

**Error response from api**
```
{
    "error": {
        "code": 500
    }
}
```

**Comment by Betree** [comment] 2023-01-11 11:08
cc @gustavlrsn

**Comment by gustavlrsn** [comment] 2023-01-11 13:19
@dreygur I'm not able to reproduce this error. Can you confirm if it is still occurring?

**Comment by dreygur** [comment] 2023-01-12 04:56
It's not occurring anymore

**Comment by gustavlrsn** [comment] 2023-01-12 13:46
@dreygur thank you for the confirmation. Closing this issue.

**Closed by gustavlrsn** 2023-01-12 13:46 UTC
Labels: bug
