### ISSUE TITLE
Bugs with events

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1918] opened 2019-04-09 19:31 UTC
While using Events on OC for [Sustain Meetup](https://opencollective.com/sustainoss/events/sustain-community-meetup-442ev), I stumbled upon small but annoying bugs

- [ ] Timezone should be the time zone of the place
- [ ] Contribution flow should be simpler for free tickets (skip step 2)
- [ ] Button in contribution flow should not be "make a contribution" but "get ticket"

**Comment by znarf** [comment] 2019-04-10 07:17
If you want that to be fixed, can you split that in multiple issues?

It's not a good workflow to have these list of issues, bugs, enhancements.

**Comment by znarf** [comment] 2019-05-17 09:06
@xdamman Closing the issue because it's invalid. If you want to follow up on that, please create individual issues that can be easily worked on. If these are bugs, they should have steps to reproduce.

**Closed by znarf** 2019-05-17 09:06 UTC
Labels: Bug Fix Fridays, invalid
