### ISSUE TITLE
Unable to edit recently edited subscription amount

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#1817] opened 2019-03-15 05:47 UTC
**Describe the bug**
Backer changed subscription from $25 > $50. But then he wanted to change it again to $65. He was not able to see how to edit the new $50 subscription. So he had to cancel it and re-do a new one.

**To Reproduce**
I am not sure how to test this myself without changing an actual subscription, but if someone can do it in a test environment it would probably be pretty clear if it's reproducible.

**Expected behavior**
If you edit a subscription amount, you should be able to edit it again if you change your mind.

**Additional context**
I'm speculating, but maybe this happened because the $50 subscription was in some kind of pending state since it hadn't been charged yet, or hadn't gone on the monthly schedule yet?

**Comment by znarf** [comment] 2019-03-15 07:46
@alannallama what about testing on http://staging.opencollective.com/?

**Comment by alannallama** [comment] 2019-03-16 04:43
@znarf I tried to set up subscriptions on staging, but got this error using a gift card:

> No such customer: cus_DamYChuIoHbvF2; a similar object exists in live mode, but a test mode key was used to make this request.

...and this one using a credit card.
> Your card was declined. Your request was in test mode, but used a non test (live) card. For a list of valid test cards, visit: https://stripe.com/docs/testing.

**Comment by znarf** [comment] 2019-03-16 12:31
To test on staging, always use test credit cards from Stripe, that's right.

> Genuine card information cannot be used in test mode. Instead, use any of the following test card numbers, a valid expiration date in the future, and any random CVC number, to create a successful payment.

Can you try again?

**Comment by alannallama** [comment] 2019-03-18 02:12
In order to use test cards from stripe, I need the expiry dates and ccv numbers, but the list I saw only has the credit card number alone.

**Comment by alannallama** [comment] 2019-03-18 02:19
OK @znarf I verified this on staging. 

To reproduce:

* Set up a subscription
* Edit the amount
* Try to edit the amount again
* Menu does not have any option besides cancel.

<img width="575" alt="Screen Shot 2019-03-18 at 3 18 41 PM" src="https://user-images.githubusercontent.com/5498878/54502769-3e8ca100-4991-11e9-8a90-b6433b0ed5d9.png">

**Comment by Betree** [comment] 2019-04-10 15:33
So the root cause here comes from https://github.com/opencollective/opencollective-api/blob/0025ecb722e19bb897cf5a6d23fecda0fe07fc4b/server/graphql/v1/mutations/orders.js#L756 when we set the new order status to `PENDING`

In https://github.com/opencollective/opencollective-frontend/blob/bb85d9f6278c5ccf53a52e553be9b37509f8ffc0/src/components/SubscriptionCard.js#L451 we only show the buttons to edit amount and payment method if the order status is **not** `PENDING`.

@znarf In the API, should we not directly set the order status to `ACTIVE`?

**Comment by znarf** [comment] 2019-04-11 11:53
I think this was done on purpose based on a feedback from @xdamman.

**Comment by piamancini** [comment] 2019-04-11 16:30
wait, why would be want to edit a pending order? The logic seems ok to me

**Comment by alannallama** [comment] 2019-04-12 02:54
Well, we know this case arises because this was instigated by a user who
had this issue. What if you simply make a mistake when updating the
subscription amount, and need to change it again right away?

**Comment by znarf** [comment] 2019-04-12 06:30
@piamancini I don't see why changing the amount should put the order in `PENDING`. If it's waiting for next month payment, then all subscriptions should be `PENDING` forever.

This is creating an unexpected, undocumented and confusing behavior for the donator. Unless there is a strong technical reason, we should not do that.

**Comment by Betree** [comment] 2019-04-12 08:06
Apparently this was done https://github.com/opencollective/opencollective-api/pull/1564

Quote:
https://github.com/opencollective/opencollective-api/pull/1564#discussion_r238634122

> 
> it only changes the status from `PENDING` to `ACTIVE` when waiting the payment methods `processOrder`( a more concrete case would be waiting on stripe to confirm payment and then right away update the order again from PENDING to ACTIVE). but in this PR's case for the orders to change from `PENDING` to `ACTIVE` I needed to do one more change. Look at https://github.com/opencollective/opencollective-api/blob/753d48825039b182b27077ecbe804d5b4fca678f/server/lib/subscriptions.js#L72-L97
> 
> I could still "reuse" the original Order which is usually `ACTIVE`(my bad for the comment above, I assumed it wrongly because the orders have a `PENDING` status on the test file, and we execute both `PENDING` and `ACTIVE` orders regardless) but I really think it's better keep it PENDING and only change on the first execution.
> 
> a use case would be:
> - You donate 2USD **monthly** to mochajs in November 15th, thus creates an Order and its status is `ACTIVE`.
> - you update that subscription to donate 10USD in November 23rd. this will, on the background, deactivate the original subscription and create a new one as well as generate a new Order.
> - This new Order would have the status `PENDING` because it'll only be executed in December 1st. And it'll become active as soon as it's executed for the first time(transactions created).
> 
> PS: To check **Order** default status, see : https://github.com/opencollective/opencollective-api/blob/master/migrations/20180727173834-add-status-to-order.js

**Comment by znarf** [comment] 2019-04-12 08:27
@Betree while it did sound _reasonable_ back then, reading back this discussion I still don't see why it  _needs_ to be `PENDING`. 

What I was trying in the past discussion was to make sure it was on purpose and explicit. Now, I'm questioning the purpose.

**Comment by piamancini** [comment] 2019-04-12 14:03
> @piamancini I don't see why changing the amount should put the order in PENDING. If it's waiting for next month payment, then all subscriptions should be PENDING forever.

I agree. I thought there was a pending order already (like when someone chooses payment method other and received the instructions to wire the funds)  and user wanted to edit it.

**Comment by piamancini** [comment] 2019-04-12 14:04
> Well, we know this case arises because this was instigated by a user who
> had this issue. What if you simply make a mistake when updating the
> subscription amount, and need to change it again right away?

If you made the payment already and want to change it, then the order is not pending

**Comment by znarf** [comment] 2019-07-05 14:54
Should have been fixed in https://github.com/opencollective/opencollective-api/pull/2064

**Closed by znarf** 2019-07-05 14:54 UTC
Labels: bug, complexity → medium, frontend
