### ISSUE TITLE
Invoice expense with invalid address

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3630] opened 2020-10-27 01:38 UTC
See https://opencollective.com/mealsofgratitude/expenses/26459

Under the payee address it just shows:
![Screen Shot 2020-10-27 at 2 37 13 PM](https://user-images.githubusercontent.com/5498878/97246319-f1a5c780-1861-11eb-8b79-7deb322ca819.png)

Really what we should do is force the address to match or just take it directly from the bank account owner address details pulled from Transferwise. But for non-bank transactions we definitely need them to input a valid address in these fields.

**Comment by Betree** [comment] 2020-10-27 06:59
Seems like a duplicate of #3145?

**Comment by sbinlondon** [comment] 2021-01-26 11:57
Yes it's a duplicate. Closing the other issue.

@kewitz and I chatted and he feel it would be a good idea to take the details from Transferwise as @alanna mentioned.

**Comment by sbinlondon** [comment] 2021-01-29 14:30
Regarding the demo of https://github.com/opencollective/opencollective-frontend/pull/5801

### questions to discuss from demo:

* how should we store the structured address info in the backend? should it be backwards compatible?
* cacheing the Shopify data or be prepared to proxy it
* need double check that all the ISO codes from the InputCountryCode (and also the language choice dropdown) match the ones the Shopify API is expecting
* add a drop down select for province/state/etc based on the fields that are returned there
* in Expenses should we prefill the address data on the left with the address data from the bank account and/or vice versa?

@kewitz @Betree @znarf

**Closed** 2021-02-22 19:43 UTC
Labels: bug, complexity → simple, expenses, frontend
