### ISSUE TITLE
Error donate money from collective to collective in GBP

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1811] opened 2019-03-13 12:58 UTC
> I want to donate the £26.17 (GBP) balance that's remaining in Norwich Sharing City to Open Collective UK, but when I try to donate £26 (GBP) I get an error telling me I only have $26.17 (USD) left. See attachment.

![](https://d.pr/free/i/81vJtD+)

**Comment by znarf** [comment] 2019-03-13 13:37
If there is really $26 left on the account, then it's normal that $34 can't be paid.

**Comment by xdamman** [comment] 2019-03-13 16:23
The collective is in GBP, the host is in GBP, the collective to which they want to donate the money is in GBP. So something is off.

**Comment by Betree** [comment] 2019-03-14 22:46
Added frontend label because collective balance should be displayed in pounds, not dollars.

**Comment by xdamman** [comment] 2019-03-15 11:38
But it looks like it's the error message returned by the API. So maybe there is a just a mismatch with the currency being used here (maybe it's the currency of the individual admin of the collective that makes the donation instead of the currency of the collective?).
Not sure how much the frontend is involved here.

**Comment by Betree** [comment] 2019-03-26 09:29
So there is an issue with the interface here: we always display `$` instead of payment method's currency for the "Available balance".

However that's not the root cause for this bug, the root cause is https://github.com/opencollective/opencollective/issues/1865

I've changed `Norwich Sharing City Collective` payment method's currency to `GBP`. @xdamman can you try again to see if it works?

**Comment by xdamman** [comment] 2019-04-01 10:34
Waiting for Lauren to try again. Will report back.

**Comment by Betree** [comment] 2019-05-09 07:56
@xdamman Any news from Lauren?

**Comment by Betree** [comment] 2019-08-19 13:32
This should be fixed now. @xdamman please re-open if you get any feedback

**Closed by Betree** 2019-08-19 13:32 UTC
Labels: api, blocked → waiting feedback, bug, complexity → medium, frontend
