### ISSUE TITLE
"Amount" label on gift card form is ambiguous

### ISSUE THREAD

**Issue by lencioni** [opencollective/opencollective#1733] opened 2019-02-14 17:27 UTC
I've been using the gift card form, and I have found the "Amount" label to be a little ambiguous--is it asking for dollar amount or the amount of cards I want to create? I know that the dollar sign in the input itself helps to clarify, but when scanning the form for understanding, I'm seeing the label and not the faded dollar sign.

I think this would be improved and a little easier for folks to use by changing the "Amount" label to "Dollar Amount".

![airbnb - open collective 2019-02-14 09-23-09](https://user-images.githubusercontent.com/195534/52805090-a8382900-303a-11e9-9607-96ad67d2e535.png)

**Comment by Betree** [comment] 2019-02-18 08:40
Thanks for the detailed issue @lencioni!

@cuiki Do you agree with this?

**Comment by znarf** [comment] 2019-02-18 09:14
I get the point from @lencioni but disagree on the solution.

The problem is that the currency is unclear, $ can be the sign (and dollar the name) of many currencies (Canadian, Mexican, New Zealand). 

I would propose to use 3 letters currency on the left (USD or US$) and double that with a plain english confirmation on the right (ie: amount in US dollars)

**Comment by znarf** [comment] 2019-07-05 15:10
A $50 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $50 when the Pull Request is reviewed, accepted and merged. [More info](BOUNTY.md)

This bounty is currently reserved to participants of the OSCA (Open Source Africa) event. If not completed there, it will be later open to everyone.

**Comment by Akumzy** [comment] 2019-07-06 14:18
I'll like to work on this (OSCA PH)

**Comment by alabobriggs** [comment] 2019-07-06 15:29
Am from OSCA ph and I'll like to work on this

**Comment by alabobriggs** [comment] 2019-07-09 16:10
Please I need a link to an example of this issue @lencioni @znarf

**Comment by alabobriggs** [comment] 2019-07-10 10:21
[Pull request](https://github.com/opencollective/opencollective-frontend/pull/2131) for this issue

**Comment by Rexben001** [comment] 2019-08-03 13:08
I'm from OSCA Lagos, I'm working on this

**Comment by znarf** [comment] 2019-08-15 08:00
:trophy: Resolved by @Rexben001  in https://github.com/opencollective/opencollective-frontend/pull/2286 

To claim the bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)

For more info about the bounty process and how to format your invoice, please read https://docs.opencollective.com/help/developers/bounties

**Comment by znarf** [comment] 2019-08-15 08:00
This is not yet live, will be part of our next deploy.

**Closed by znarf** 2019-08-15 08:00 UTC
Labels: $50, complexity → simple, enhancement, frontend, good first issue, osca
