### ISSUE TITLE
Abilty to Order, tiers, projects etc

### ISSUE THREAD

**Issue by shannondwray** [opencollective/opencollective#6445] opened 2023-02-20 13:11 UTC
## Who is your user?
Admins

## What are they trying to achieve?
Abilty to choose the order in which Projects and tiers are displayed on the collective or fiscal host page

## How are they currently doing this?
Would need to delete and ensure they are set up in the order they are wanting to be displayed 

## How well understood is this problem?

 - [ ] Surfacing: if you feel this is a seed of an idea that needs to be researched.
 - [ ] Understanding: if you've done some research and feel it is already well understood and ready for shaping.
 - [ ] Shaping:  if you feel a solution is clearly defined and can be made into a pitch ([read more about shaping](https://basecamp.com/shapeup/1.1-chapter-02))
 - [ ] Pitching: if you feel that it is ready to be presented for prioritisation ([read more about pitching](https://basecamp.com/shapeup/1.5-chapter-06))

**Comment by Betree** [comment] 2023-02-20 13:18
Duplicate of https://github.com/opencollective/opencollective/issues/4622

**Comment by Betree** [comment] 2023-02-20 13:19
Note that tiers can already be re-ordered with drag'n'drop

**Closed by Betree** 2023-02-20 13:18 UTC
Labels: duplicate
