### ISSUE TITLE
custom contribution -> make a donation

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2213] opened 2019-07-08 16:55 UTC
I know that terms have been discussed but seeing them in context changes the perspective.
When going to the collective page, my eye is directly drawn to the tiers.

The title "Custom Contribution" is not clear to me.
It feels like I can define the way I want to contribute (not only financially). It also seems like work. 

Why not simply: "Make a donation".
and the tag could be "financial contribution" instead of "custom contribution".

So instead of:
![](https://d.pr/free/i/3hySIM+)

something like:
![](https://d.pr/free/i/UqcKHS+)

Also it feels like the amount of the "Rebel" and "Super rebel" tiers should be part of the card and not just in the description. No?

**Comment by piamancini** [comment] 2019-07-08 20:10
We specifically said we wanted to own the idea of contribution, contribute, contributors. Introducing an adhoc term here 'donation' is confusing. We can't use 'Make a Donation' and the button being 'Contribute'. Also it would be confusing regarding the rest of the tiers that don't have the word 'Donation'. 

Custom Financial Contribution should be the right term.

**Comment by xdamman** [comment] 2019-07-08 20:40
Yes we want to own the idea of “contribution”, “contribute” and “contributors”. But we shouldn’t loose track of what the user expects.

So while we can call this a “custom financial contribution” in our interface when defining the type of tier (i.e. in the “edit tier” interface for the admins), the main title should be something that the end user expects, not the accurate technical term according to our own terminology.

The number one call to action on any website of any community / non profit is “donate”. So this has to be somewhere very visible. A lot of people complained in our current interface that it wasn’t obvious how they could make a simple (one time) “donation”.

**Comment by Betree** [comment] 2019-07-08 21:04
> Also it feels like the amount of the "Rebel" and "Super rebel" tiers should be part of the card and not just in the description. No?

Yes, this part is yet to come.

**Comment by alanna** [comment] 2019-07-08 22:50
I think we should stick with the 'contribution' based terminology we agreed.

However, unless I am misunderstanding, the text @xdamman is referring to is customisable by the Collective right? Is the question here about what the default should be? I think we should stick with our agreed terms and if the core contributor wants to change it to 'donation' they can do it themselves.

**Comment by Betree** [comment] 2019-07-08 23:22
It's not customisable yet but will soon be: https://github.com/opencollective/opencollective/issues/543#issuecomment-508932858

**Comment by xdamman** [comment] 2019-07-09 07:53
I’m really worried that we start designing for our constrains, not for our users. This is a big red flag for me. “Custom financial contribution” is a very technical term (and a mouthful). I have yet to see this term on the Internet (we are literally the only ones using this [according to google](https://www.google.be/search?q=%22Custom+financial+contribution%22&ie=UTF-8&oe=UTF-8&hl=en-be&client=safari))

The proper term for this is “donation”. Visitors don’t care about our constrains and all our features and why we might have very good reasons to refer to those donations as “custom financial contributions”. 

That’s why my proposal to stay consistent with the term on the platform of “financial contribution” is to use that as the tag/category/type of tier but use the “user friendly term” as the title (per my screenshot above).

I’d also simplify by removing “custom”. It’s simply a “financial contribution”.

**Comment by alanna** [comment] 2019-07-09 07:56
I agree we should use simple, friendly language whenever possible. The confusion comes because "donation" is used in our system already for another thing (in-kind, non-financial contributions that are accounted in the budget). There is a risk of us getting too constrained, but there is also risk in being sloppy with the terms. That's how we ended up with all this confusion in the first place. This particular instance isn't the most important battle in my view, so I won't really argue for it. I just think we need to be mindful.

**Comment by Betree** [comment] 2019-07-09 08:01
User expecting to find a `Donate` button sounds like something we can (and should) test.

Process would be pretty simple:
1. Present Open Collective briefly, avoid using the terms `Contribute` and `Donate`
> Open Collective is a place where you can support the Open Source project that you love.

2. Give the person a (test) credit card number, ask them to go and support Webpack and open the V2 page for them. Half participants get a page with `Donate`, the other half with `Contribute`

3. Measure:
  - How long it takes before they reach the contribution flow
  - What percentage ends up on the wrong page by clicking somewhere else

**Comment by Betree** [comment] 2019-07-09 08:55
I thought that the blue button at the top was `Donate`, but actually I see that it's `Contribute`.

As we're not changing the existing terminology then my [previous comment](https://github.com/opencollective/opencollective/issues/2213#issuecomment-509535386) doesn't seems to me anymore like a thing we should do.

**Comment by xdamman** [comment] 2019-07-09 09:23
> The confusion comes because "donation" is used in our system already for another thing (in-kind, non-financial contributions that are accounted in the budget).

This shows that we are designing for our system, not for the visitors of the page.
Most visitors will never face this other part of the system. If this is creating confusion, I’d address this in the part of the system that is less visible.

I really feel strongly about this because this is a prime example of why open source software has always struggled to offer great front end products. And also why old big companies struggle to offer compelling end user experiences. They are too much driven by their constrains and by being technically super accurate in their terms. They lack empathy for the end user. We need to design for the end users and walk our way back from there, not the other way around.

That said, @alanna’s point about consistency is a very important point. Consistency is required to  provide a good user experience. But consistency shouldn’t prevent us from using the language of our users. That’s why a good way to do this is to categorize the different elements using consistent concepts (that’s what I tried to do by using “financial contribution” as the type of the tier but not its default title).

**Comment by alanna** [comment] 2019-07-09 09:43
The best way to "use the language of our users" is to make the wording customizable, which it will be. We said in the team retreat that we wanted to stop rehashing decisions that have already been made. At the same time, we need to keep reviewing things to make sure they are still right and to improve them. But the time to review a decision is *after* you have gone through with implementing it and actually have some results, not halfway through the implementation. Let's do another terminology review in a couple months.

**Comment by xdamman** [comment] 2019-07-09 10:43
> The best way to "use the language of our users" is to make the wording customizable

Sure. But defaults matter. A lot.

> the time to review a decision is after you have gone through with implementing it and actually have some results, not halfway through the implementation. Let's do another terminology review in a couple months.

In a couple of months? Huh. No.
Aren't we doing this preview release to get feedback? What did I miss?

I agree that we should have a time for feedback, a time for decision, etc.

But in this case, we only agreed on the overall terminology. We never reviewed it in context. It's the first time we can see it in context, that's why I'm bringing this up now. Decisions that we take out of context should be guidelines, not blindly imposed. Otherwise we will fall back into a very rigid top down structure.

To be clear, my goal is not to rehash a decision here. I think the terminology we came up with is good and really helps with consistency. My proposal is to keep this terminology (just remove "custom" to simplify it because a "financial contribution" is by definition custom as its amount and frequency have to be defined). But given the context that we now have thanks to this preview release, my proposal is to use this terminology as a support (i.e. to show the tier type / category), not as the default title. When I read "Custom contribution" in this current implementation, I expect a form where I can describe how I think I can contribute beyond money (which I think we should have eventually once we will support other types of contribution, but this is beyond the scope of this).

**Comment by piamancini** [comment] 2019-07-11 11:44
How about Make a custom donation? 

My thinking is:  if we add the word 'custom' then when I log in as a user I see that one way of giving money is custom (donation) and one way is fixed (tiers). This is less dissonant and doesn't make me think why one thing is call donation (customizable) and the other contribution (recurring). Without scaring me into not starting a recurring subscription by making me think I am joining anything. Which I not, i just want to give a little bit of money every month

**Comment by xdamman** [comment] 2019-07-11 11:56
Custom is not a great word. What does it mean custom donation? A donation is custom by default because when you donate, you expect to be able to choose the amount and the frequency. So let’s remove the word “custom”, it adds confusion without adding much (if at all). A [quick google search](https://www.google.be/search?q=%22custom+donation%22&ie=UTF-8&oe=UTF-8&hl=en-be&client=safari) shows that “custom donation” is a very technical term only used in interfaces meant for the administrators, not for the end users.

You can make a donation and it can be one time or recurring.
That’s what people expect. Keep it simple and clean.

Then there are predefined ways to contribute that are more rigid. They are defined by the admins of the collectives. They can also be one time or recurring financial contributions.

No matter if you made a donation or contributed to one of the tiers, as long as you give money, you will be considered as a financial contributor. Your donation will be considered as a financial contribution whose description is “Donation”. That’s how we reconcile having a consistent terminology while embracing the expectations of the visitors.

**Comment by piamancini** [comment] 2019-07-11 12:56
ok I can get behind that. 
What do we do with the Default though? 
We have thousands of collectives that have SPONSOR and BACKER tiers which are recurring. 
What label and CTA do we assign? 
Sure new users will know to edit and pick, but our existing base?

**Comment by xdamman** [comment] 2019-07-11 15:42
That's a good question. Let's create a new issue to define "smart defaults" for tiers.

**Comment by alanna** [comment] 2019-07-15 03:51
CTAs should be based on the word `contribute`. Our existing Sponsor and Backer tiers become regular tiers with the titles "sponsor" and "backer" or whatever other titles the core contributors have customized. The button says "contribute". 

Or, we could just get rid of the tier title all together and instead make the title the text on the button. Right now the design has way too much redundant text and we don't need it. We also don't need to blue labels that also say "financial contribution" either in my opinion. 

This whole question could be radically simplified. We're getting into debates about text because there's a bunch of unnecessary text.

**Comment by alanna** [comment] 2019-07-15 03:51
But what we should NOT do is add more terms like "donate" or whatever, which only confuses things more.

**Comment by Betree** [comment] 2019-07-16 07:45
[This feedback](https://github.com/opencollective/opencollective/issues/2228#issuecomment-511087129) from a user seems relevant for the current conversation:

> As for terminology I think this is very important and I currently feel like it's an opportunity for improvement for open collective. The word contribute, especially in the landscape of open source projects, tends to be associated with the idea of sending in improvements to the project in the form of code or documentation, etc. GitHub chose the word sponsor, which open collective uses as a tier name. Donate make sense, but lines up more with the one time donation idea unless it's presented right which I would think looks something like this:
>
> One prominently placed "donate" button on the page. This should be the biggest if not the only call to action above the fold. Clicking it takes you either to a new screen to proceed the donation, or keeps you on the same page but scrolls to a section with a form to complete the donation process.

**Comment by Betree** [comment] 2019-07-16 07:47
How/when do we close this issue?

**Comment by xdamman** [comment] 2019-07-16 08:09
> This whole question could be radically simplified. We're getting into debates about text because there's a bunch of unnecessary text.

Agreed.

> But what we should NOT do is add more terms like "donate" or whatever, which only confuses things more.

I really would love to understand why from your perspective “donate” is confusing.
Another relevant user feedback on that point: #2228

**Comment by xdamman** [comment] 2019-07-16 08:21
I think there is a big misunderstanding that I introduced when I was pushing for “we should own the terms contribute/contributors/contributions”. While I still think we should focus on becoming the platform for people to contribute to a community, I think that at this stage –that is, until we offer other ways to contribute than financial contributions– it’s going to confuse people to over use “contribution”, especially if it replaces what they already know (donate, become a backer, a sponsor ...). So I think slowly introducing “Contribute” would be better (as the title of the section for example like we already have in the design – and yes we could remove the title or subtitle that are redundant). 

That way people understand that all those tiers are ways to contribute financially (so maybe we should just keep the subtitle to be explicit that today we only support “Make a financial contribution”?). You can contribute by making a donation, you can contribute by becoming a backer, a sponsor. No matter what you pick, you are making a financial contribution to the collective. In a future version we will also allow people to make other types of contributions, in which case it would make sense to introduce a second line of tiers to distinguish between “Financial contributions” or “Other ways to contribute”.

**Comment by Betree** [comment] 2019-07-19 14:50
@alanna @piamancini @xdamman We need to wrap this up to move forward with the implementation. This is a design/terminology decision so I'm not the one who should take it.

**Comment by piamancini** [comment] 2019-07-24 13:12
@alanna, you started this terminology discussion and did the work of pushing though it, it seems like you are the legitimate decision-maker here. We can have a final call about it but then you should decide so Ben can move forward.

**Comment by alanna** [comment] 2019-07-25 01:09
If it's my decision, then I think we should implement what we decided and then focus on improving it, instead of changing halfway through. This kind of text is super easy to update so it's very low risk to change it later.

After thinking about this issue I posted somewhere else that I think the problem is we're using too much text and it's redundant. I suggested this change to fix it:

> We could make "Become a financial contributor" the section title, delete the current section title, loose the blue 'contribution' badges, and make the tier title what goes on the button. Viola, a whole lot less text, a much simpler design, and no information lost.

![](https://user-images.githubusercontent.com/5498878/61196184-eab47d80-a720-11e9-836b-7f371b0b92a6.png)

We should stick with "financial contribution" for now. I don't think we should introduce other terms like "donate" or whatever, because we are trying to simplify language across the app and focus on "contribute" as the key action.

**Comment by Betree** [comment] 2019-07-25 07:45
@alanna Can you create a separate issue for this and tag design on it? Having the tier title on the button may not play nicely with https://github.com/opencollective/opencollective/issues/543

According to https://github.com/opencollective/opencollective/issues/2267 this issue should now be closed. We can also plan a call to discuss it as we wanted to do on Tuesday if anyone thinks that we should.

**Comment by alanna** [comment] 2019-07-29 00:16
@Betree raised #2280

**Comment by alanna** [comment] 2019-07-29 00:16
Closing this issue as the decision has been made for the time being.

**Closed by alanna** 2019-07-29 00:16 UTC
Labels: collective page v2, discussion
