### ISSUE TITLE
Apply with new collective fails on OSC

### ISSUE THREAD

**Issue by brendan8c** [opencollective/opencollective#6280] opened 2023-01-07 05:04 UTC
Is it possible to create a project alone? Requires 2 administrators but I am creating a project alone.

![001](https://user-images.githubusercontent.com/61526280/211132002-f85ac37a-ca30-436a-9b1d-ba11c9fb3419.gif)

**Comment by RichardLitt** [comment] 2023-01-08 13:49
It looks like you are not creating a collective, but instead applying for hosting under Open Source Collective at https://opencollective.com/opensource/apply. 

Do you have the URL of the page you took a screenshot of, to confirm?

**Comment by brendan8c** [comment] 2023-01-08 15:59
I don't understand what you mean by url address or screenshot for confirmation.
Did I miss something?
Here is what I do when trying to apply.
Is my course of action incorrect?
I am alone and I do not have a team and even more administrators.

![001](https://user-images.githubusercontent.com/61526280/211206461-a7bd2666-2482-4144-befb-ff3674f2757a.gif)

**Comment by BenJam** [comment] 2023-01-09 09:50
@brendan8c apologies, you can apply with an individual account, the policy has been reset https://opencollective.com/opensource/updates/updating-open-source-collectives-eligability-criteria

**Comment by RichardLitt** [comment] 2023-01-09 13:21
@BenJam That's the policy, but the code doesn't allow new collectives to sign up with OSC without having two admins. I just tested it. 

@brendan8c For now you can press back and apply manually by pressing Click Here. See screenshot below. Let me know if that doesn't work. 

<img width="659" alt="Screenshot 2023-01-09 at 08 20 54" src="https://user-images.githubusercontent.com/910753/211317618-85bd4d0e-e561-417f-a4ae-7d7f5bee8e11.png">

**Comment by brendan8c** [comment] 2023-01-09 13:59
@BenJam, I also read your last post.
But at the moment, projects with only 2 administrators are still accepted.

![16_54_28 09-01-2023](https://user-images.githubusercontent.com/61526280/211324677-5c6c484a-7aca-4c09-8d92-96a6aff09f92.png)

@RichardLitt, I tried what you suggested but it didn't work for me either.

![001](https://user-images.githubusercontent.com/61526280/211325142-cddd7a8b-7dba-47d3-8ed5-d74cc21bfd6f.gif)

**Comment by RichardLitt** [comment] 2023-01-09 15:33
@brendan8c Want to try again? Let us know how it goes!

**Comment by brendan8c** [comment] 2023-01-09 16:18
@RichardLitt, User @Betree writes that this is currently not possible and it will take time for the changes to take effect. Because they are currently working on it. Does it make sense for me to repeat my attempts if this does not work at the moment?

**Comment by Betree** [comment] 2023-01-09 16:45
> @RichardLitt, User @Betree writes that this is currently not possible and it will take time for the changes to take effect. Because they are currently working on it. Does it make sense for me to repeat my attempts if this does not work at the moment?

Sorry for the confusion, it should be working now. The fix we're working on addresses an issue that prevented hosts from disabling the 2 admins policy.

**Comment by Betree** [comment] 2023-01-10 11:16
@brendan8c Sorry for the inconvenience, it seems to be a different issue that I could not reproduce. I've notified another engineer who'll be looking at it soon.

For now, I suggest you apply manually: go to https://opencollective.com/opensource/apply/intro and select "Request manual verification".

**Comment by brendan8c** [comment] 2023-01-10 11:33
@Betree, I went to the page you mentioned.
I clicked on the "Request manual verification" button, filled out the required forms, clicked the check box and clicked the "Submit application" button.
Got the same error as above in the screenshot.

**Comment by gustavlrsn** [comment] 2023-01-11 10:33
@brendan8c Hello! I've looked at this but not able to reproduce the "Not Found" error message. I'd be interested to see the details of the request that is failing, in the Network tab of the developer tools in your browser, after clicking submit.

**Comment by brendan8c** [comment] 2023-01-15 17:42
@gustavlrsn,
Look, I chose manual verification, filled in the required fields.
Clicking the next button gives an error.
![001](https://user-images.githubusercontent.com/61526280/212557515-63761cd9-6e00-4662-98a6-390ade51d25b.gif)

**Comment by gustavlrsn** [comment] 2023-01-16 11:00
@brendan8c Thank you for the screenrecording! I was able to test with similar data and find out that we had an issue with parsing underscores in GitHub handles. A fix is incoming.

**Comment by gustavlrsn** [comment] 2023-01-16 11:59
@brendan8c The fix is now in production and things should work, thanks for reporting and providing more details!

**Closed** 2023-01-17 10:18 UTC
Labels: bug, frontend

**Comment by brendan8c** [comment] 2023-01-17 15:41
Oh thanks everyone! Now it works 💜
