### ISSUE TITLE
Better flow for submitting an expense as a third party vendor

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#6618] opened 2023-03-30 15:28 UTC
I fully resonate with this user:

<img width="620" alt="Screenshot 2023-03-30 at 5 09 33 PM" src="https://user-images.githubusercontent.com/74358/228881845-92ec9608-51fc-46ae-9836-0ced37d06a9d.png">

The flow should move the burden from the vendor (expense/invoice submitter) who has no interest in signing up for yet another platform to the admins who already have an account and are used to the platform:

1. Go to https://opencollective.com/citizen_garden/expenses/new
2. Big surface area to drag and drop a PDF of an invoice (or a picture of a receipt)
3. Enter description, total amount, Pick: pay the vendor directly (vendor name, IBAN or paypal) *OR* reimburse me (your name, IBAN or paypal) DONE
4. Thank you. Your invoice/receipt has been submitted to the "Citizen Garden Collective". As soon as it is approved by one of the admins (admins' names), it will be processed by their fiscal host (All for Climate ASBL/VZW). Please leave your email address to be notified when it is paid.

Even better: create an email billing@:collectiveSlug.opencollective.com where any vendor can submit a PDF attachment or a picture. Mark the expense as "incomplete" until someone goes and add the missing information (payout and amount).
Related: #1862

**Comment by Betree** [comment] 2023-03-30 16:21
Duplicate of https://github.com/opencollective/opencollective/issues/5894

**Comment by znarf** [comment] 2023-03-30 16:48
While it's a duplicate, completely agree and experienced the pain myself.

**Comment by xdamman** [comment] 2023-04-09 16:51
In the meantime, can you merge those two accounts and add me as an admin so that I can actually do it on behalf of the vendor? 
- https://opencollective.com/tournevie
- https://opencollective.com/tournevie1

Thank you.

**Comment by Betree** [comment] 2023-04-14 07:02
@xdamman Done, both profiles are now merged under https://opencollective.com/tournevie, and you're an admin of the profile

**Closed by Betree** 2023-04-14 07:02 UTC
Labels: duplicate
