### ISSUE TITLE
Markup appearing in expense email notification

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4552] opened 2021-08-16 23:32 UTC
https://opencollective.com/vuetify/expenses/43516

![Screen Shot 2021-08-17 at 11 31 37 AM](https://user-images.githubusercontent.com/5498878/129641706-ddee2e5a-b7e4-4787-a5cd-391935ca4d8a.png)

In the email:

![Screen Shot 2021-08-17 at 11 32 30 AM](https://user-images.githubusercontent.com/5498878/129641757-19acc2e6-0733-4c59-982f-91257fad3af6.png)

**Comment by Betree** [comment] 2021-08-17 06:52
For reproduction: this must be specific to grants, as we don't allow rich text in regular expenses

**Comment by aggmoulik** [comment] 2021-09-03 07:41
Hey @Betree , I am new to the opencollective repo, can you help with this issue as I want to work on it, seems like a good issue to work on initially.

**Comment by Betree** [comment] 2021-09-03 08:35
@aggmoulik Since this is an API issue, you'll need to clone both Frontend and API. You can follow these steps to setup your local env: https://github.com/opencollective/opencollective-frontend#environment-variables. Once everything's working, you'll be able to see sent emails on http://localhost:1080/.

Regarding this issue itself, you could reproduce it by:
- Picking the collective you want to use for your tests. I recommend http://localhost:3000/apex
- Allowing the "Grant" expense type on this by setting `settings.fundingRequest` to `true`. You'll need to do this directly in the database, `Collectives` table, using something like https://dbeaver.io.
- Then you can go to http://localhost:3000/apex/expenses/new, pick "Grant" as expense type, fill the form and submit. See the email result.

An alternative way to approach this would be to add a test in `opencollective-api/test/server/graphql/v2/mutation/ExpenseMutations.test.js` that creates a grant expense with some HTML for items description, checks the email sent and makes sure there's no HTML in there.

**Comment by Betree** [comment] 2021-10-18 08:12
This one looks quite bad. Let's make sure we look at it once https://github.com/opencollective/opencollective/issues/4819 gets merged.

![image](https://user-images.githubusercontent.com/1556356/137693318-ac1d7c62-77dc-4a5e-804a-a5d95a59bc51.png)

**Closed** 2021-11-02 14:27 UTC
Labels: bug, complexity → simple, api
