### ISSUE TITLE
Mismatch in Refund Ids when an Expense is paid/refund multiple times

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#5213] opened 2022-02-08 10:40 UTC
It seems we're not properly tracking the RefundTransactionId on the second and subsequent refunds.

- ExpenseId=22333
- ExpenseId=15861

**Comment by Betree** [comment] 2022-02-09 07:55
I think the root cause for this one was fixed in https://github.com/opencollective/opencollective-api/pull/6999, but I missed checking existing data to see what we needed to migrate.

**Comment by znarf** [comment] 2022-02-09 08:01
Cool, that looks good. I'll try to double check if there are more Expenses that needs to be fixed.

**Comment by alanna** [comment] 2022-08-05 03:31
Was this fixed?

**Comment by Betree** [comment] 2022-08-05 07:52
**SQL query to detect invalid entries**

```sql
-- Select all expenses where the number of distinct `RefundTransactionId` is not equal
-- to the number of transactions associated with a refund.
select e.*
from "Expenses" e
INNER JOIN "Transactions" t ON t."ExpenseId" = e.id
WHERE t."deletedAt" IS NULL
AND t."RefundTransactionId" IS NOT NULL
GROUP BY e.id
HAVING COUNT(DISTINCT t."RefundTransactionId") != COUNT(t.id)
ORDER BY MAX(t.id) DESC
```

**Result expense IDs**

The two expenses mentioned in the issues were returned by the query:
`22333,20385,20031,15861,14586,11383` 

**Action taken**

Given the small number of cases, I went with a manual edit. For each expense:

```sql
select id,
       type,
       description,
       "isRefund",
       "RefundTransactionId",
       "deletedAt",
       (
            "RefundTransactionId" IS NOT NULL
            AND (SELECT "RefundTransactionId" FROM "Transactions" WHERE id = t."RefundTransactionId") = t.id
       ) AS is_paired -- Small flag to help us see if then transaction and its refund are uniquely paired to each others
from "Transactions" t
where "ExpenseId" = :ExpenseId
ORDER BY id DESC
```

Then manually edited all the `RefundTransactionId` to match the proper transaction. I also manually marked a few transactions as deleted as they looked like incomplete manual edits (i.e. original transaction being marked as deleted but not its refund).

<details>

<summary>Full SQL logs of my actions</summary>

```log
Query: UPDATE public."Transactions" SET "RefundTransactionId" = 470319 WHERE id = 470646
[2022-08-05 09:26:35] 1 row affected in 105 ms
Query: UPDATE public."Transactions" SET "RefundTransactionId" = 470646 WHERE id = 470319
[2022-08-05 09:26:35] 1 row affected in 101 ms
Query: UPDATE public."Transactions" SET "RefundTransactionId" = 470318 WHERE id = 470647
[2022-08-05 09:26:35] 1 row affected in 101 ms
Query: UPDATE public."Transactions" SET "RefundTransactionId" = 470647 WHERE id = 470318
[2022-08-05 09:26:36] 1 row affected in 101 ms
Query: UPDATE public."Transactions" SET "RefundTransactionId" = 469460 WHERE id = 469375
[2022-08-05 09:28:39] 1 row affected in 101 ms
Query: UPDATE public."Transactions" SET "RefundTransactionId" = 469461 WHERE id = 469374
[2022-08-05 09:28:39] 1 row affected in 101 ms
Query: UPDATE public."Transactions" SET "RefundTransactionId" = 390315, "deletedAt" = null WHERE id = 390300
[2022-08-05 09:38:41] 1 row affected in 101 ms
Query: UPDATE public."Transactions" SET "RefundTransactionId" = 388311 WHERE id = 387860
[2022-08-05 09:38:42] 1 row affected in 100 ms
Query: UPDATE public."Transactions" SET "RefundTransactionId" = 390314, "deletedAt" = null WHERE id = 390301
[2022-08-05 09:38:42] 1 row affected in 102 ms
Query: UPDATE public."Transactions" SET "RefundTransactionId" = 387858 WHERE id = 387851
[2022-08-05 09:38:42] 1 row affected in 101 ms
Query: UPDATE public."Transactions" SET "RefundTransactionId" = 387859 WHERE id = 387850
[2022-08-05 09:38:42] 1 row affected in 100 ms
Query: UPDATE public."Transactions" SET "RefundTransactionId" = 388310 WHERE id = 387861
[2022-08-05 09:38:42] 1 row affected in 101 ms
Query: UPDATE public."Transactions" SET "RefundTransactionId" = 387861 WHERE id = 388310
[2022-08-05 09:38:42] 1 row affected in 102 ms
Query: UPDATE public."Transactions" SET "RefundTransactionId" = 390301 WHERE id = 390314
[2022-08-05 09:38:42] 1 row affected in 102 ms
Query: UPDATE public."Transactions" SET "RefundTransactionId" = 387860 WHERE id = 388311
[2022-08-05 09:38:42] 1 row affected in 102 ms
Query: UPDATE public."Transactions" SET "RefundTransactionId" = 390300 WHERE id = 390315
[2022-08-05 09:38:42] 1 row affected in 103 ms
Query: UPDATE public."Transactions" SET "RefundTransactionId" = 440386 WHERE id = 440201
[2022-08-05 09:42:47] 1 row affected in 102 ms
Query: UPDATE public."Transactions" SET "RefundTransactionId" = 440387 WHERE id = 440200
[2022-08-05 09:42:47] 1 row affected in 102 ms
Query: UPDATE public."Transactions" SET "RefundTransactionId" = 441903 WHERE id = 441506
[2022-08-05 09:42:47] 1 row affected in 102 ms
Query: UPDATE public."Transactions" SET "RefundTransactionId" = 441902 WHERE id = 441507
[2022-08-05 09:42:47] 1 row affected in 100 ms
Query: UPDATE public."Transactions" SET "RefundTransactionId" = 441507 WHERE id = 441902
[2022-08-05 09:42:47] 1 row affected in 100 ms
Query: UPDATE public."Transactions" SET "RefundTransactionId" = 441506 WHERE id = 441903
[2022-08-05 09:42:48] 1 row affected in 100 ms
Query: UPDATE public."Transactions" SET "RefundTransactionId" = 438793 WHERE id = 437840
[2022-08-05 09:44:29] 1 row affected in 101 ms
Query: UPDATE public."Transactions" SET "RefundTransactionId" = 438792 WHERE id = 437841
[2022-08-05 09:44:30] 1 row affected in 102 ms
Query: UPDATE public."Transactions" SET "RefundTransactionId" = 438795 WHERE id = 438796
[2022-08-05 09:44:30] 1 row affected in 100 ms
Query: UPDATE public."Transactions" SET "RefundTransactionId" = 438794 WHERE id = 438797
[2022-08-05 09:44:30] 1 row affected in 101 ms
Query: UPDATE public."Transactions" SET "RefundTransactionId" = 438797 WHERE id = 438794
[2022-08-05 09:44:30] 1 row affected in 102 ms
Query: UPDATE public."Transactions" SET "RefundTransactionId" = 438796 WHERE id = 438795
[2022-08-05 09:44:30] 1 row affected in 101 ms
Query: UPDATE public."Transactions" SET "RefundTransactionId" = 361441 WHERE id = 361444
[2022-08-05 09:45:39] 1 row affected in 101 ms
Query: UPDATE public."Transactions" SET "RefundTransactionId" = 361443 WHERE id = 361442
[2022-08-05 09:45:39] 1 row affected in 102 ms
Query: UPDATE public."Transactions" SET "RefundTransactionId" = 361442 WHERE id = 361443
[2022-08-05 09:45:39] 1 row affected in 101 ms
Query: UPDATE public."Transactions" SET "RefundTransactionId" = 361440 WHERE id = 361437
[2022-08-05 09:45:40] 1 row affected in 101 ms
Query: UPDATE public."Transactions" SET "RefundTransactionId" = 361444 WHERE id = 361441
[2022-08-05 09:45:40] 1 row affected in 101 ms
Query: UPDATE public."Transactions" SET "RefundTransactionId" = 361439 WHERE id = 361438
[2022-08-05 09:45:40] 1 row affected in 101 ms
Query: UPDATE public."Transactions" SET "deletedAt" = '2022-08-05 09:48:39.005000 +00:00' WHERE id = 290256
[2022-08-05 09:48:46] 1 row affected in 106 ms
Query: UPDATE public."Transactions" SET "deletedAt" = '2022-08-05 09:48:39.005000 +00:00' WHERE id = 290255
[2022-08-05 09:48:46] 1 row affected in 104 ms
Query: UPDATE public."Transactions" SET "deletedAt" = '2022-08-05 09:48:39.005000 +00:00' WHERE id = 290260
[2022-08-05 09:48:46] 1 row affected in 103 ms
Query: UPDATE public."Transactions" SET "deletedAt" = '2022-08-05 09:48:39.005000 +00:00' WHERE id = 290259
[2022-08-05 09:48:46] 1 row affected in 105 ms
```

</details>

**Closed by Betree** 2022-08-05 07:52 UTC
Labels: bug, ledger, complexity → simple, api
