### ISSUE TITLE
Emailed system generated receipt is empty file

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4770] opened 2021-10-03 05:27 UTC
I downloaded the receipt attached to an email notification of a contribution, and it resulted in apparently an empty file.
<img width="805" alt="Screen Shot 2021-10-03 at 6 22 35 PM" src="https://user-images.githubusercontent.com/5498878/135741102-28a4b04b-5551-42c6-bfa4-119300971fab.png">
<img width="851" alt="Screen Shot 2021-10-03 at 6 22 42 PM" src="https://user-images.githubusercontent.com/5498878/135741104-0760453a-2cfa-4537-a4b6-258144200199.png">

<img width="281" alt="Screen Shot 2021-10-03 at 6 23 38 PM" src="https://user-images.githubusercontent.com/5498878/135741116-c4555d62-f191-4f0d-a693-c86b73704710.png">

I went to the transaction and downloaded the same receipt and it was fine.

<img width="751" alt="Screen Shot 2021-10-03 at 6 26 20 PM" src="https://user-images.githubusercontent.com/5498878/135741196-1ac714ad-bbd6-4f5d-a89a-efe11b6bd906.png">

<img width="843" alt="Screen Shot 2021-10-03 at 6 27 27 PM" src="https://user-images.githubusercontent.com/5498878/135741232-1f5aad89-7dfb-4aa0-8865-0d3dcb0daa6b.png">

**Comment by znarf** [comment] 2021-10-04 07:52
According to the logs, it went ok. 

<img width="1409" alt="Screenshot 2021-10-04 at 09 50 21" src="https://user-images.githubusercontent.com/806/135813445-3437802f-0740-4cfe-bda2-6aa8321fe133.png">

But I can see that the attachment is broken in other emails.

**Comment by znarf** [comment] 2021-10-04 09:33
Might be fixed by https://github.com/opencollective/opencollective-api/pull/6663

**Comment by znarf** [comment] 2021-10-04 18:58
@alanna it's a bit difficult to reproduce but we fixed some suspicious related code. There is good chance this is it.

**Comment by BenJam** [comment] 2022-01-05 13:23
closing because ☝️

**Closed by BenJam** 2022-01-05 13:23 UTC
Labels: bug, pdf
