### ISSUE TITLE
"Be the first one to contribute!" on free tier/contribution instead of showing contributors

### ISSUE THREAD

**Issue by adionditsak** [opencollective/opencollective#7502] opened 2024-08-04 13:16 UTC
**Describe the bug**
On a free tier, I have multiple contributors, but the free tier does not represent who contributed to it but still has the text "Be the first one to contribute!"

**To Reproduce**
1. Contribute/register to a free tier contribution on any collective
2. See the frontend which still states "Be the first one to contribute!" and not the people who clicked this

**Expected behavior**
To represent the people who contributed to the free tier to show their symbolic and also valuable contribution

**Comment by Betree** [comment] 2024-08-05 07:05
Hi @adionditsak, could you share a link to the collective/tier affected by this issue?

**Comment by adionditsak** [comment] 2024-08-05 13:24
@Betree It is on a cooperative that I co-organise called ursuppe. [Here is a link to our page](https://opencollective.com/ursuppe). As mentioned a couple of people have signed up for the free tier "Immaterial Soup Member", and I would have expected them to be present on the list of contributors although they are in a situation where they could not afford to financially contribute. Maybe it could be resolved by showing them under "[collective name] is all of us" and under "All contributors", but not under Financial contributors, if you think a distinction is necessary.

**Comment by adionditsak** [comment] 2024-08-28 10:28
@Betree Do you know whats the status here or if this is even a proper issue? Would be nice to have them visible on our profile :)

**Comment by adionditsak** [comment] 2024-08-28 10:50
@Betree I was just made aware that issue has existed for a long time (https://github.com/opencollective/opencollective/issues/6774). I will follow this issue and investigate if I can contribute.

**Comment by Betree** [comment] 2024-09-05 09:39
@adionditsak https://github.com/opencollective/opencollective/issues/6774 is indeed the root cause for this issue. I'm closing this one as a duplicate, but feel free to re-open it if I missed anything.

**Closed by Betree** 2024-09-05 09:39 UTC
Labels: bug, duplicate
