### ISSUE TITLE
Expense Inviting Errors with 0 total amount

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#6828] opened 2023-06-16 14:09 UTC
**Describe the bug**

It seems that inviting a user to submit a reimbursement by default gives error; `Validation error: Validation min on amount failed`, although we mark the amount here as optional. 

![image](https://github.com/opencollective/opencollective/assets/12435965/afcbb356-1603-40a3-b17b-e70dd0060266)

**To Reproduce**
1. Go to any collective
2. Click on submit expense and go through the flow on creating an expense invite (type reimbursement as seen on the below screen-cast)
3. See error

**Expected behavior**

We should not see any error and the validation should not be done since the amount field is optional.

**Screenshots**

[invite-error.webm](https://github.com/opencollective/opencollective/assets/12435965/b40f3216-0686-42d9-a336-b7089337735c)

**Comment by SudharakaP** [comment] 2023-06-16 14:13
This was reported at, https://opencollective.freshdesk.com/a/tickets/216459

**Comment by Betree** [comment] 2023-06-19 06:16
Strange, the `min` on amount has always been there: https://github.com/opencollective/opencollective-api/pull/426. Either:
1. A sequelize update changed the default behavior for this validation
2. Or we changed something in the invite process
3. Or the invite process has never worked with 0 amounts

**Comment by Betree** [comment] 2023-10-03 06:12
Duplicate of https://github.com/opencollective/opencollective/issues/6587

**Closed by Betree** 2023-10-03 06:12 UTC
Labels: duplicate
