### ISSUE TITLE
Make it easier to search through tags to add to a transaction

### ISSUE THREAD

**Issue by kaylarep** [opencollective/opencollective#5535] opened 2022-05-06 22:19 UTC
## [User story ](https://opencollective.freshdesk.com/a/tickets/81304)

> - As of right now, you can't search through tags when attempting to add one to a transaction. This means it takes a lot longer to find the correct tags, and with all the different versions of one tag makes it hard to keep things organised. 

_Originally posted by @kaylarep in https://github.com/opencollective/opencollective/issues/5138#issuecomment-1119147207_

**Comment by Betree** [comment] 2022-05-09 06:21
This part is actually a duplicate of https://github.com/opencollective/opencollective/issues/5523. Feel free to re-open if I misunderstood

**Closed by Betree** 2022-05-09 06:21 UTC
Labels: duplicate

**Comment by kaylarep** [comment] 2022-05-13 20:09
@Betree I think this issue was referring to tags on Expenses instead of tags on Collectives.  Will https://github.com/opencollective/opencollective/issues/5523 cover that as well?

**Comment by Betree** [comment] 2022-05-16 06:25
> @Betree I think this issue was referring to tags on Expenses instead of tags on Collectives. Will #5523 cover that as well?

Yes, the component mentioned in https://github.com/opencollective/opencollective/issues/5523 is the same we use everywhere (search, settings, expenses, etc).
