### ISSUE TITLE
System is treating sending Event funds to Collective as a Contribution

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4382] opened 2021-06-21 21:23 UTC
There was an event with $1 left, so I clicked the button on the banner to send the funds to the parent Collective.

This triggered a notification and receipt as if this were a normal contribution.

![Screen Shot 2021-06-22 at 9 14 43 AM](https://user-images.githubusercontent.com/5498878/122829739-7e464e00-d33b-11eb-9cdc-d96e7f1b148e.png)

![Screen Shot 2021-06-22 at 9 16 16 AM](https://user-images.githubusercontent.com/5498878/122829223-d92b7580-d33a-11eb-919a-e1c99890fa6d.png)

There are multiple issues here:
* It's confusing for the user to receive this email when they did not make a contribution, only transferred funds from Event to Collective.
* The receipt is not OK from an accounting/legal perspective... 
  * There was no actual movement of funds, and no receipt should be issued at all. This is evidence of a transaction between entities that did not occur, can mess up tax reporting, etc.
  * An Event is not an entity and the location of an event is not its address. The Event is showing up here as the "bill to" and its location as an address, which is misleading.
* The Event is now showing up as a Contributor on the Collective, which isn't right.

![Screen Shot 2021-06-22 at 9 21 36 AM](https://user-images.githubusercontent.com/5498878/122829597-4e974600-d33b-11eb-9c69-25a4538eedab.png)

Moving funds from an Event to a Collective should be considered an internal transfer. The same goes for Projects (can someone check if Projects have the same issue?).

**Comment by Betree** [comment] 2021-06-22 06:54
So the list of fixes expected here are:
1. Don't send a "thank you" email when moving funds between a sub-collective (event/project) and its parent
2. In the frontend, hide the "Download receipt" button for internal transactions like that
3. When generating receipts for events, use the parent collective as the source of the info (for location, address, etc)
4. Don't create a `Members` (`BACKER`) entry when moving funds between a sub-collective (event/project) and its parent

Some of these items can eventually be moved to new issues if the assignee can't fix them all in one go.

**Comment by alanna** [comment] 2021-07-13 01:42
Came across another example of this, which is a bit different. When a Host contributes to its own Collective, the system is treating it like an external contribution. Any time the payer and payee entities are the same on the receipt, it's a pretty strong indicator the receipt should not exist or is representing something off-base.

<img width="722" alt="Screen Shot 2021-07-13 at 1 39 21 PM" src="https://user-images.githubusercontent.com/5498878/125376817-e8ed2580-e3df-11eb-9f9f-41c9ec4dd5e7.png">

However, in this case, unlike transferring event funds to a Collective, I think it does make sense for a host to show up as a contributor on the Collective page. If the host doesn't want that, they can move the money via Add Funds. In this case I did it specifically because it's a contribution from the host not added funds. But that point is not nearly as important as fixing the issue of such transfers generating receipts.

**Comment by SudharakaP** [comment] 2021-07-20 16:12
>     3\. When generating receipts for events, use the parent collective as the source of the info (for location, address, etc)

@Betree @znarf : I think this point is redundant given that we are hiding the receipts for events in point 2 anyways. 🤔 

> However, in this case, unlike transferring event funds to a Collective, I think it does make sense for a host to show up as a contributor on the Collective page. If the host doesn't want that, they can move the money via Add Funds. In this case I did it specifically because it's a contribution from the host not added funds. But that point is not nearly as important as fixing the issue of such transfers generating receipts.

@alanna @znarf : So if I get this correctly we should not generate receipts for transfers from host to one of its own collective. Correct? 🤔 😄

**Comment by alanna** [comment] 2021-07-20 23:03
A receipt is a document generated for legal and accounting purposes providing evidence of funds moving from the purchaser to the vendor in a transaction. Moving money between Open Collective balances within the same Host is not a transaction and money is not moving between entities, so a receipt in this case does not make sense.

**Comment by SudharakaP** [comment] 2021-07-21 20:26
> A receipt is a document generated for legal and accounting purposes providing evidence of funds moving from the purchaser to the vendor in a transaction. Moving money between Open Collective balances within the same Host is not a transaction and money is not moving between entities, so a receipt in this case does not make sense.

@alanna : Thanks for the explanation. I've added support for that as well. 👍🏽

**Comment by SudharakaP** [comment] 2021-07-26 04:04
It seems that everything in this issue was addressed, and therefore I am closing the issue. 🙂

**Comment by alanna** [comment] 2021-08-02 08:06
Reopening because I just got an email and receipt for a contribution made from the Host to one of its Collectives. This document doesn't make sense as a receipt.
[transaction_documentation_2021-08-02_734746e9-06f8-4f78-822c-caf5806e6e66.pdf](https://github.com/opencollective/opencollective/files/6915359/transaction_documentation_2021-08-02_734746e9-06f8-4f78-822c-caf5806e6e66.pdf)

**Comment by znarf** [comment] 2021-08-02 08:09
@alanna Could you create a different issue if the problem is (perhaps slightly) different?

**Comment by alanna** [comment] 2021-08-02 08:14
It's the same issue, exactly what was mentioned above

> So if I get this correctly we should not generate receipts for transfers from host to one of its own collective. Correct? 🤔 😄

**Comment by znarf** [comment] 2021-08-02 08:19
I was just looking at the issue title "System is treating sending Event funds to Collective as a Contribution", I haven't seen it went out of scope already.

**Comment by SudharakaP** [comment] 2021-08-23 21:23
Closing this issue as the final point above https://github.com/opencollective/opencollective/issues/4382#issuecomment-890814928 has been solved. Feel free to open a new issue if there's anything more to improve along these lines. 😄

**Closed by SudharakaP** 2021-08-23 21:23 UTC
Labels: bug, api, frontend
