### ISSUE TITLE
Overlapping UI when adding video to standalone tier

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3897] opened 2021-01-22 22:46 UTC
The save button and the input for the video URL.

<img width="1243" alt="Screen Shot 2021-01-23 at 11 45 17 AM" src="https://user-images.githubusercontent.com/5498878/105557225-8a1feb00-5d70-11eb-994b-b92653234a3b.png">

**Comment by saideepesh000** [comment] 2021-02-02 15:32
Hey @alanna, could you please help me to reproduce this on the website, I couldn't figure out this campaign page.

**Comment by alanna** [comment] 2021-02-02 22:14
Create a standalone tier, then try to add a video.

**Comment by saideepesh000** [comment] 2021-02-03 14:08
Hey @alanna, I found it, could you give me the actual output that you want, so that I can work on it.

**Comment by alanna** [comment] 2021-02-03 21:52
The save button and the input for the video URL should not overlap or be overlapped by other UI elements.

**Comment by SudharakaP** [comment] 2021-06-01 12:39
@opencollective/design : This issue had an overlapping input and video and I proposed a fix for this at, https://github.com/opencollective/opencollective-frontend/pull/6434. What I've done here at the screenshot is that making sure the video and the corresponding input appears below the short description as you can see from the screenshot there. But [after discussion with Benjamin](https://github.com/opencollective/opencollective-frontend/pull/6434#pullrequestreview-672715851) it was pointed out that this probably is from the initial design that we had some other positioning for the video for larger screens (for smaller screens it seemed to be in par with the screenshot). Appreciate if you could take a look and confirm on the best design for this. 😄

**Comment by SudharakaP** [comment] 2021-06-22 12:57
For this one the slightly changed new design is given at https://www.figma.com/file/KinuveYf4WUlRIXzMTnmIsmO/OC-Design-Lab?node-id=10960%3A0. I'll reiterate on this to fix this bug, note that in the design we also have a new delete button. Since there pages are changing completely in https://github.com/opencollective/opencollective/issues/4299, I'll leave that for later if there's no objection as the purpose here is to fix the bug of overlapping.  😄 🐨 

cc: @Betree

**Closed** 2021-07-09 13:20 UTC
Labels: bug, complexity → simple, frontend, good first issue, needs design
