### ISSUE TITLE
Transparency of fees for expense payouts

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4886] opened 2021-10-31 23:00 UTC
Currently, we don't show payment processor fees on expenses anywhere (e.g. PayPal and Wise fees). We should reveal them in the transaction details and/or in the expense updates once paid.

## Who is your user?
Expense payees, Collective admins, and Host admins

## What are they trying to achieve?
Transparently see fees associated with expense payouts.

## How are they currently doing this?
There is no easy way to see payment processor fees charged on expense payouts, so people need to manually compare the amount received with the amount of the expense to see the difference. Host admins and expense payees can access this data manually, but Collectives admins (and the public) have no way to see these numbers directly even if they go looking.

### P3 high frequency, low  impact

**Comment by Betree** [comment] 2021-11-02 07:18
Duplicate of https://github.com/opencollective/opencollective/issues/4691

**Comment by znarf** [comment] 2022-01-04 10:51
I'm closing as duplicate.

**Closed by znarf** 2022-01-04 10:51 UTC
Labels: frontend, enhancement, duplicate
