### ISSUE TITLE
Submit an expense in different currency

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#101] opened 2016-05-30 15:51 UTC
@sedubois should be able to send his invoice in EUR to the OpenCollective collective which is in USD.
(same for me for my expenses in Europe)

We should add a dropdown in the form to submit an expense:
- [ ] On website: https://github.com/OpenCollective/opencollective-website/blob/a45f891fc0a81bae1585e0b6b007460a328208c0/frontend/src/components/ExpenseForm.js
- [ ] On app: https://github.com/OpenCollective/opencollective-app/blob/c14ba8d312b50600f6d5573da39393d24de8affa/frontend/src/components/TransactionForm.js

**Comment by asood123** [comment] 2016-05-31 00:51
We should do this. We need to investigate how Paypal handles currency conversion - what data is reported to us and the currency of the transaction, etc. It would be a good opportunity to complete the migration to the new `Expense` model as well - it's more stable and scalable.

**Comment by sedubois** [comment] 2016-08-10 15:35
@asood123 @xdamman we already get the money in group currency remaining in preapprovalDetails response after submitting expense. The issue is that we just didn't store this amount. So to do:

- [ ] store preapprovalDetails response (which includes amount remaining) in `PaymentMethod.data`
- [ ] create script to populate these preapprovalDetails for all paypal `PaymentMethod`s
- [ ] update `Transaction.netAmountInGroupCurrency` based on subtraction from amount in preapprovalDetails response after paying expense, with previous value stored in `PaymentMethod.data`
- [ ] also take opportunity to remove from codebase currencies (such as `INR`) not supported by PayPal
- [ ] adapt `app` and `website` to specify currency in submit + edit expense forms

Other possibilities observed:
- it's technically possible to hold several wallets for different currencies, instead of converting to a single one, but that would probably require more effort
- instead of relying on preapprovalDetails data, we could rely on the [doc](https://www.paypal.com/us/cgi-bin/marketingweb?cmd=_display-xborder-fees-outside) which gives the rates (percentage + fixed) (but that's probably fragile) + call the [ConvertCurrency API](https://developer.paypal.com/docs/classic/api/adaptive-payments/ConvertCurrency_API_Operation/) but it gives "an estimated exchange rate"

**Comment by asood123** [comment] 2016-08-12 21:30
Been thinking about this for a few days. Main issue is that we aren't dealing with fees properly, so every solution creates more complication. We should accurately store the fees. It's fine to do it with another call afterwards (that's how we do it for stripe - we make a separate call after the txn finishes).

@xdamman do you know why we went with adaptive-payments, instead of REST API?

**Comment by piamancini** [comment] 2017-11-08 21:54
@asood123 found a solution today, always host currency and conversion on the fly. not sure when/how will be implemented. closing this.

**Closed by piamancini** 2017-11-08 21:54 UTC
