### ISSUE TITLE
Bug with crypto payments on event pages

### ISSUE THREAD

**Issue by RCheesley** [opencollective/opencollective#4661] opened 2021-09-09 17:24 UTC
**Describe the bug**
On events, if the crypto payment option is enabled, you do not actually get to the payment page - it just redirects you to the contribute page.

Screencast: https://youtu.be/JO6J-o-qOEg

**To Reproduce**
1. Enable crypto payments on event
2. Click to contribute on the tier
3. See error

**Expected behavior**
It should work the same as with the main collective and direct you to /donate/crypto

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: Version 93.0.4577.63 (Official Build) (x86_64)

**Comment by SudharakaP** [comment] 2021-09-09 19:31
@RCheesley : I couldn't recreate this issue yet. For example on staging we have the Crypto payment method enabled on this event; https://staging.opencollective.com/webpack/events/test-event-b24b157c and it seems to work fine for me. Does it work for you as well (just so that we are sure it's not a browser related issue)?

**Comment by RCheesley** [comment] 2021-09-09 19:36
You have no tiers set up there at all, maybe that is the difference.

**Comment by RCheesley** [comment] 2021-09-09 19:39
https://youtu.be/iTWHKCpUGkE here is a screencast with the URL showing :)

**Comment by SudharakaP** [comment] 2021-09-09 22:46
@RCheesley : Thanks for the information. I've narrowed down the root cause. We will push a fix for this tomorrow. 👍🏽 

@znarf : This issue is cause by a missing condition in the contribution blocker section. I've fixed that in the above PR. The problem is that we have to specifically check for the crypto contribution as well as otherwise when the user disables the custom contribution tier it will redirect to the `/contribute` page. 

https://github.com/opencollective/opencollective-frontend/blob/54f218d007cdf899f66d1c73e04826b9283706e7/pages/contribution-flow.js#L147

**Closed** 2021-09-30 14:31 UTC
Labels: bug, complexity → simple, frontend
