### ISSUE TITLE
Unexpected error when blocking google domains

### ISSUE THREAD

**Issue by nailyk-fr** [opencollective/opencollective#1819] opened 2019-03-16 13:30 UTC
# Describe the bug
The website is almost unusable without google domains. 

# To Reproduce
1. Add no script to Firefox: https://addons.mozilla.org/en-US/firefox/addon/noscript/
2. Go on on the page to edit your profile
3. Allow temporary opencollective.com only 
![image](https://user-images.githubusercontent.com/16372405/54475908-5af4d600-47f7-11e9-9eb8-3bd3b412dcfd.png)
4. Each page display an error, you cannot add credit card. 
![image](https://user-images.githubusercontent.com/16372405/54475954-e1a9b300-47f7-11e9-8d74-14de42a904bb.png)
(Hit f5 usually load the page successfully)

# Device
- OS: Linux x86_64
- Browser: `Firefox Nightly 67.0a1 (2019-02-15) (64 bits)`

It may not be related to google domain blocking.

**Comment by znarf** [comment] 2019-03-25 13:09
Blocking "Google Maps" should not break editing, only the feature requiring "Google Maps" (InputTypeLocation).

**Comment by znarf** [comment] 2019-07-05 15:06
A $50 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $50 when the Pull Request is reviewed, accepted and merged. [More info](BOUNTY.md)

This bounty is currently reserved to participants of the OSCA (Open Source Africa) event. If not completed there, it will be later open to everyone.

**Comment by burinious** [comment] 2019-07-06 14:00
from #oscaph will like to work on this issue

**Comment by znarf** [comment] 2019-09-13 12:28
This issue is now open to everyone.

**Comment by someofthethings** [comment] 2019-10-07 17:20
For $100 I must ask the question: is these any evidence Google are blocking this themselves? If so $100 doesn't seem worth it, if that's that it's worth to your collective.

**Comment by yellowwoods12** [comment] 2019-10-22 15:31
@znarf Would like to work on this one. Can this be assigned to me?

**Comment by ola3510** [comment] 2019-10-28 13:30
@znarf I would love to work on this...can it be assigned please?

**Comment by znarf** [comment] 2019-10-28 13:46
@yellowwoods12 @ola3510 This issue has been already tackled in half in https://github.com/opencollective/opencollective-frontend/pull/2777

It's still open because it would be great to have a message warning that the "Location" input is not properly functioning because Google Maps could not be loaded. Feel free to work on that. I will keep the $100 bounty.

**Comment by jzabala** [comment] 2019-11-06 02:23
Is someone working on this issue? it would be cool to assign it if someone is already working on it.

**Comment by Jeanluis019** [comment] 2019-11-24 04:04
@znarf I can't reproduce this bug, I followed the steps in the description and it didn't work for me, any suggestions?

**Comment by jeffin143** [comment] 2019-11-24 05:59
> @znarf I can't reproduce this bug, I followed the steps in the description and it didn't work for me, any suggestions?

@Jeanluis019 please refer comment https://github.com/opencollective/opencollective/issues/1819#issuecomment-546953378

**Comment by Jeanluis019** [comment] 2019-11-24 15:18
@jeffin143 Thank you! Can anyone assign me this issue, please? (@znarf )

**Comment by jeffin143** [comment] 2019-11-24 15:25
> @jeffin143 Thank you! Can anyone assign me this issue, please? (@znarf )

Since nobody is currently assigned, you can go ahead and take a shot :)

**Comment by jzabala** [comment] 2019-11-24 15:30
@Jeanluis019 sure, assigned. Time limit is 1 week, so we can free the bounty for someone else in case you have trouble completing it.

**Comment by oncletom** [comment] 2020-01-05 21:37
I tried to reproduce by blocking `https://maps.googleapis.com/maps/api/` with uBlock Origin. HTTP calls are blocked, and the error does not show up. Is that issue still relevant?

**Comment by znarf** [comment] 2020-01-05 22:17
@oncletom The error is catched since https://github.com/opencollective/opencollective-frontend/pull/2777 Before closing this issue, we want to display a warning in the forms where the API is used. There is an open PR for that: https://github.com/opencollective/opencollective-frontend/pull/3029

**Comment by oncletom** [comment] 2020-01-05 23:02
Gotcha, thanks for clarifying this out 🙂

**Comment by znarf** [comment] 2020-02-17 08:45
Removing assignment because it's been a long time, it was not far to be completed.

**Comment by joshikeno** [comment] 2020-02-17 09:44
@znarf 
this problem only exists we `google` domains are blocked.
We can use an alternative `Geolocation Autosuggestion` service like [`#Maptiler`](https://github.com/opencollective/opencollective-frontend/pull/3356)  or [`osm`](https://osmnames.org/api/) when google is blocked.

**Comment by znarf** [comment] 2020-02-17 09:46
@joshikeno we don't want to go that far here, we just want to fail elegantly and let the user know, the PR was almost ready.

**Comment by joshikeno** [comment] 2020-02-17 09:48
Alright, understood. 
I would take care of that.

**Closed** 2020-02-18 11:00 UTC
Labels: $100, bounty, complexity → minimal, enhancement, frontend, good first issue
