### ISSUE TITLE
CSV Exports filename should be in ISO date format

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#3096] opened 2020-04-29 11:45 UTC
Todays it's looking like `znarf--20200202000200-20200430130485.csv`

It would be clearer if it was `znarf-2020-02-01-2020-04-30.csv` or `znarf-from-2020-02-01-to-2020-04-30.csv`.

**Comment by SleeplessByte** [comment] 2020-04-29 12:11
The dates are also incorrect. The to date has inadvertently an extra month added:

2020-01-01 to 2020-01-31 is exported as
2020-01-01 to 2020-02-31 (without any data from February in there).

**Comment by SudharakaP** [comment] 2020-04-30 01:11
I can give it a try at this one if no one is already working on this. :smile:

**Comment by SudharakaP** [comment] 2020-04-30 05:18
Here I've done a pull request to change the filename structure to reflect `sudharaka-from-2020-02-01-to-2020-04-30.csv` format. 

@SleeplessByte : Within the generated CSV files [it seems that we generate](https://github.com/opencollective/opencollective-frontend/blob/001113d89adf6006ef4e84d6bd01892a7c89c62a/components/expenses/TransactionsExportPopoverAndButton.js#L19) the date times in YYYY-MM-DD format. Example,

```
Transaction Description,User Name,User Profile,Transaction Date,Collective Currency,Host Currency,Transaction Amount,Host Fee (USD),Open Collective Fee (USD),Payment Processor Fee (USD),Net Amount (USD),Subscription Interval,Order Date
"$100 bug bounty claim for https://github.com/jhipster/generator-jhipster/pull/9509","Vishal Mahajan","http://opencollective.com/vishal423",2019-04-26 01:58:35,"USD","USD",-100.00,0.00,0.00,-5.55,-105.55,"one time","2019-04-26T08:58:35.000Z"
"Monthly financial contribution to JHipster (Backer)","Ergon TI SpA","http://opencollective.com/ergon-ti",2019-04-24 18:10:30,"USD","USD",2.00,-0.10,-0.10,-0.38,1.42,"month","2019-04-25T01:10:30.000Z"
"Monthly financial contribution to JHipster (Backer)","Jaime Freire Sáenz de la Calzada","http://opencollective.com/jaime-freire-saenz-de-la-calzada",2019-04-24 16:57:57,"USD","USD",2.00,-0.10,-0.10,-0.38,1.42,"month","2019-04-24T23:57:57.000Z"
```

So I am not sure exactly where within the CSV file we generate it in MM/DD/YYYY format. Can you provide an example by any chance? :thinking: :thinking:

**Comment by znarf** [comment] 2020-04-30 20:14
@SleeplessByte can you give us an example of MM/DD/YYYY within the file?

**Comment by SleeplessByte** [comment] 2020-05-01 10:39
Of course. So the _CSV_ seems okay, the receipts are not:

1. https://opencollective.com/<username>/transactions
2. Get receipts
3. ![image](https://user-images.githubusercontent.com/1964376/80799989-9c397800-8ba8-11ea-9b5a-df20b750ff8b.png)

(I'm okay sharing this "personal" information).

[derk-jan_opensource_2020-01-01_2020-02-31 (2).pdf](https://github.com/opencollective/opencollective/files/4563608/derk-jan_opensource_2020-01-01_2020-02-31.2.pdf)

Check the filename, and the issue with the dates insides.

**Comment by SudharakaP** [comment] 2020-05-02 01:14
@SleeplessByte : Thanks for the information. 

I've made two more pull requests in addition to the csv file name change; 

1) To change the file name of the generated transactions pdf files; it should now have the format similar to the csv; derk-jan_opensource-from-2020-01-01-to-2020-02-31.pdf

2) To change all dates within the transactions pdf file to have the format YYYY/MM/DD. 

I hope this helps. :smile:

**Comment by SleeplessByte** [comment] 2020-05-02 01:40
It helps a lot. The `datesTo` is still incorrect for the pdfs. The _format_ is now correct, but the value is not. The generated file: `derk-jan_opensource_2020-01-01_2020-02-31.pdf` **should** have been:
`derk-jan_opensource_2020-01-01_2020-01-31.pdf`

```diff
- derk-jan_opensource_2020-01-01_2020-02-31.pdf
+ derk-jan_opensource_2020-01-01_2020-01-31.pdf
```

**Comment by SudharakaP** [comment] 2020-05-02 02:35
@SleeplessByte : The pull requests I've made are not merged yet. You will only see the changes reflected after they are reviewed, merged and new deployment is done. 🙃

**Comment by SleeplessByte** [comment] 2020-05-02 13:26
I meant: I didn't see the date fixed in the PRs ;)

**Comment by SudharakaP** [comment] 2020-05-02 13:28
@SleeplessByte : Ah, got it; sorry I misunderstood. I'll do some more tests on why the month has a problem and will try to fix it. :thinking:

**Comment by SudharakaP** [comment] 2020-05-06 05:38
Okay, I've found the root cause of the wrong value in the filename as well. Just made a commit to #4112 which should take care of it. So to summarize I have three PRs related to this issue; 

1) https://github.com/opencollective/opencollective-frontend/pull/4098 : I am not sure if this is needed or not since the issue is not about CSV files as we initially thought but rather about PDFs.

2) https://github.com/opencollective/opencollective-frontend/pull/4112 : Fixes the filename issue of the transactions PDF file. 

3) https://github.com/opencollective/opencollective-pdf/pull/356 : Converts all dates within the transactions PDF file to international format. 

Feel free to let me know if there's any further suggestions. :smile:

**Closed** 2020-06-15 06:37 UTC
Labels: complexity → simple, enhancement, frontend
