### ISSUE TITLE
Contributions showing up twice and not at all on user's profile

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5134] opened 2022-01-24 00:58 UTC
https://opencollective.com/taase-vaoga

Te Awhi Rito shows up twice. But the Event contribution doesn't show up at all under 'all contributions' and you can't see them until you click "events"

<img width="813" alt="Screen Shot 2022-01-24 at 1 52 32 PM" src="https://user-images.githubusercontent.com/5498878/150706062-1afec363-9f87-4892-ab33-73e3248b7a2d.png">

Then it shows duplicate cards of the event contribution.

<img width="796" alt="Screen Shot 2022-01-24 at 1 56 04 PM" src="https://user-images.githubusercontent.com/5498878/150706067-9211dddd-73a3-4e5c-8e42-dc625ee52b8f.png">

**Comment by Betree** [comment] 2022-01-24 09:39
Duplicate of https://github.com/opencollective/opencollective/issues/4672. Proposed some ideas in https://github.com/opencollective/opencollective/issues/4672#issuecomment-920725640

**Closed by Betree** 2022-01-24 09:39 UTC
Labels: bug, duplicate
