### ISSUE TITLE
Offline Transactions, easier way to reflect on OC 

### ISSUE THREAD

**Issue by shannondwray** [opencollective/opencollective#6611] opened 2023-03-29 04:37 UTC
## Who is your user?
Collective admins, fiscal host admins 

## What are they trying to achieve?
When transactions happen offline. i.e. an invoice is paid directly from a bank account or an invoice is sent via email and the company doesn't want to deal with OC. We are needing an easier way to put invoices through that don't require a dummy organisation account. 

## How are they currently doing this?
Currently you have to create a fake organisation account and use this to pretend to be the company receiving the money so that your balance on OC is accurate. or you have to pay these with your personal $ and then submit a reimbursement. 

## How well understood is this problem?

 - [ ] Surfacing: if you feel this is a seed of an idea that needs to be researched.
 - [ ] Understanding: if you've done some research and feel it is already well understood and ready for shaping.
 - [ ] Shaping:  if you feel a solution is clearly defined and can be made into a pitch ([read more about shaping](https://basecamp.com/shapeup/1.1-chapter-02))
 - [ ] Pitching: if you feel that it is ready to be presented for prioritisation ([read more about pitching](https://basecamp.com/shapeup/1.5-chapter-06))

**Comment by Betree** [comment] 2023-03-29 06:26
Duplicate of https://github.com/opencollective/opencollective/issues/5894

Feel free to re-open if I misunderstood.

**Closed by Betree** 2023-03-29 06:26 UTC
Labels: duplicate
