### ISSUE TITLE
Default amount for a tier should be one of the presets

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1905] opened 2019-04-04 17:58 UTC
Related to #1887

The minimum amount should be >= `presets[0]` if there are presets.
![](https://d.pr/free/i/jlEhdK+)

Also, when we show the tier on the collective page, it should show `${presets[0]}+` and not `${tier.amount}+`

And in the contribution flow, we shouldn't allow to put a custom amount < presets[0]:
![](https://d.pr/free/i/kDKNEl+)

**Comment by znarf** [comment] 2019-04-05 06:40
In the code, we have that:

```
// Return the minimum amongs presets and amount
return min(isNil(tier.amount) ? tier.presets : [...(tier.presets || []), tier.amount]);
```

I don't really see the rationale behind each point:

- "The minimum amount should be >= presets[0] if there are presets." we already have a rule in place, what's better about this approach?
- "when we show the tier on the collective page, it should show ${presets[0]}+ and not ${tier.amount}+" what's the purpose of the default amount then?
- "in the contribution flow, we shouldn't allow to put a custom amount < presets[0]:" how do we communicate that rule to the donator?

Root cause? Looks we're trying to enforce a "minimum amount" that is not defined or existing anywhere. It's absolutely not clear or expected for neither the admin or the donator. I highlighted last week that we don't have any error messages in the contribution flow for the donator in that case.

If we want to enforce a minimum amount, we should let admins set one. And we should communicate it clearly to the donator.

**Comment by xdamman** [comment] 2019-04-05 19:20
> "The minimum amount should be >= presets[0] if there are presets." we already have a rule in place, what's better about this approach?

Somehow that rule is not being applied. We shouldn't be able to set an amount < presets[0]

> "when we show the tier on the collective page, it should show ${presets[0]}+ and not ${tier.amount}+" what's the purpose of the default amount then?

e.g. become a gold sponsor starting at $500/month. Presets: 500, 1000, 1500, default amount: 1000.

> "in the contribution flow, we shouldn't allow to put a custom amount < presets[0]:" how do we communicate that rule to the donator?

Ideally, where there are presets, the `amount` field should turn into a `<select>` to pick from one of the presets.

**Comment by znarf** [comment] 2019-04-09 08:40
> The minimum amount should be >= presets[0] if there are presets.

Until we make it clear that we're enforcing the first preset as a minimal amount, this is arbitrary and not expected for the admins or for the donators. This can be explained in the UI with some extra labels, or a FAQ on the side.

Also, what was the behavior before the new contribution flow? Did we got it wrong?

**Comment by znarf** [comment] 2019-05-08 10:14
Now that we have a "minimum amount"  `minimum_amount` set in the database, this issue is about enforcing that the "default amount" (`amount`) is one of the `presets` when the amount type is "flexible amount".

**Comment by znarf** [comment] 2019-05-28 07:13
@flickz To close this issue, please create a new frontend PR that is only doing Tier validation from the backend.

Just make sure the error is properly displayed when submitting the form.

**Comment by znarf** [comment] 2019-06-03 16:02
That was done in https://github.com/opencollective/opencollective-frontend/pull/1823

**Closed** 2019-06-03 16:04 UTC
Labels: api, bug, complexity → simple, frontend
