### ISSUE TITLE
Discover Page Pagination Breaks after Fourth Page

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4944] opened 2021-11-13 03:42 UTC
This was initially reported at, https://opencollective.slack.com/archives/C0HSLRNVC/p1636749289074000

It seems that trying to navigate through all the collectives in our discover page with the `sort` selected to `newest` after the 3rd page the search fails with the following error. 

```
Int cannot represent non 32-bit signed integer value: 4015000000 Int cannot represent non 32-bit signed integer value: 2422000000
```

![search-break](https://user-images.githubusercontent.com/12435965/141604472-a0898096-68a6-46f2-85b9-b69e25f78ec5.gif)

**Comment by SudharakaP** [comment] 2021-11-13 09:38
I did some investigation and managed to recreate this in my local. This happens when we overflow the limit of `GraphQLInt`. To recreate select a collective and keep on adding funds to it and and when the fund amount exceeds the limit of `GraphQLInt we will not be be able to access the collective. There seems to be at least one collective in our prod db for which this has happened. Will investigate more on a fix. 🤔 

Reference: https://github.com/graphql/graphql-spec/issues/73

**Comment by SudharakaP** [comment] 2021-12-05 17:07
There was some discussion about using `float` when communicating between front-end and api instead of integers. Maybe something we should look into prioritizing this or next sprint? Especially given that this occurred again at, https://github.com/opencollective/opencollective/issues/5017 🤔 

cc: @opencollective/core-developers

**Comment by Betree** [comment] 2021-12-06 06:36
> There was some discussion about using `float` when communicating between front-end and api instead of integers at https://opencollective.slack.com/archives/G46PNRCGP/p1637603764449700. Maybe something we should look into prioritizing this or next sprint? Especially given that this occurred again at, #5017 thinking
> 
> cc: @opencollective/core-developers

That would be a way to solve it in the long run. As medium/long-term alternatives, we can think about:
- Limiting the amounts for added funds
- Find a way to not surface these spammy/test accounts in the discover/search pages

**Comment by znarf** [comment] 2021-12-06 10:06
For search, we have a flag `hideFromSearch` that is ready to be used, we simply have to tag those profiles.

**Comment by Betree** [comment] 2021-12-06 11:08
> `hideFromSearch`

@znarf This flag is not used yet on the discover page. I've opened an API PR to change that: https://github.com/opencollective/opencollective-api/pull/6927.

**Comment by znarf** [comment] 2021-12-06 12:37
Are the problematic profiles now flagged? If not, ca someone pass a list to me privately?

**Comment by Betree** [comment] 2021-12-07 13:07
> Are the problematic profiles now flagged? If not, ca someone pass a list to me privately?

I personally haven't flagged them nor built a list yet. @SudharakaP did you do that already?

Happy to help generate the list if we don't have anything.

**Comment by SudharakaP** [comment] 2021-12-07 21:57
> > Are the problematic profiles now flagged? If not, ca someone pass a list to me privately?
> 
> I personally haven't flagged them nor built a list yet. @SudharakaP did you do that already?
> 
> Happy to help generate the list if we don't have anything.

I've sent you both a DM with the collective IDs. 😉

**Comment by Betree** [comment] 2022-04-19 07:36
A duplicate was created [here](https://github.com/opencollective/opencollective/issues/5452) but it's more focused on the root cause. Closing this one.

**Closed by Betree** 2022-04-19 07:36 UTC
Labels: bug, api
