### ISSUE TITLE
[RESEARCH] Tax forms alternative

### ISSUE THREAD

**Issue by iamronen** [opencollective/opencollective#7181] opened 2024-01-03 07:07 UTC
We currently depend on Dropbox for signing and storing tax forms. 
We would like to remove this dependency and shift to an open-source solution that is better integrated into the platform both from a technical and user experience perspective.

This is a research project to:
 - Review open source solutions and understand & assess the work that would be involved in making this change.
 - Identify UX requirements that would arise from this change and shape solutions.
 - Identify administrative UX requirements that would alleviate the need for engineers (who currently have to do manual to deliver the outcomes required by fiscal hosts) to be involved in this process.

**Comment by Betree** [comment] 2024-01-03 07:41
Duplicate of https://github.com/opencollective/opencollective/issues/6262

**Closed by Betree** 2024-01-03 07:41 UTC
Labels: duplicate
