### ISSUE TITLE
Expense submitters and collective admins are notified when expense categories they selected are changed. 

### ISSUE THREAD

**Issue by hdiniz** [opencollective/opencollective#7205] opened 2024-01-09 13:26 UTC
Part of https://github.com/opencollective/opencollective/issues/7197

When an expense category is modified by either a collective admin or fiscal host admin it is a learning moment. The expense submitter and/or collective admin need to be notified about this so that they can make better selections in future expenses.

**Comment by Betree** [comment] 2024-01-09 13:29
Duplicate of https://github.com/opencollective/opencollective/issues/7053

**Closed** 2024-01-09 13:29 UTC
Labels: accounting, api
