### ISSUE TITLE
Unable to login on OC V2

### ISSUE THREAD

**Issue by thibauld** [opencollective/opencollective#484] opened 2017-10-11 00:49 UTC
Tried to login on Firefox 56.0 (64-bit) and Chrome  61.0.3163.100 (Official Build) (64-bit) on Ubuntu 16.04 but my email seems to not be recognized as valid.
![oc-bug](https://user-images.githubusercontent.com/197119/31416601-306d325a-adf8-11e7-947d-a0eecaaa0dbd.png)

**Comment by piamancini** [comment] 2017-10-11 14:21
Hi @thibauld I can't reproduce, it's working well for me. 
I just created a login token for you on your democratech account. Try clicking there (you should have received an email) and see if it works.

**Comment by thibauld** [comment] 2017-10-11 18:43
Hi @piamancini 
Yep, I saw the login email arriving.
Hmmm... I still have the issue here, I trying with my second email t****@gmail.com and I have the same issue. To be sure it is not a chrome or firefox extension that is interfering, I just tried in incognito mode on Chrome and private window on Firefox and I have the same issue again.
![oc-bug](https://user-images.githubusercontent.com/197119/31459713-fe587f50-ae91-11e7-95d2-1c7ee2229211.png)
![oc-bug2](https://user-images.githubusercontent.com/197119/31459789-3d84c846-ae92-11e7-9e14-3105d5afab71.png)
I noticed that I get a different error though: error 500 this time instead of 400 with my previous report. Hope this helps!

**Comment by thibauld** [comment] 2017-10-11 18:48
I think I understand the bug. I tried to login "slower" and it worked.
It looks like the login only works as long as the "exists" GET HTTP request returns before the "signin" POST HTTP is done. If I try to login to fast, without waiting for the "exists" request to return, the login fails. Hopefully troubleshooting the issue just got a lot easier :)

**Comment by piamancini** [comment] 2017-10-12 00:09
cc / @xdamman

**Comment by piamancini** [comment] 2017-10-12 00:10
Issue is solved, closing it and moving it to https://github.com/opencollective/opencollective/issues/431, to list of things to look after the end of the month.

**Closed** 2017-10-13 14:54 UTC
