### ISSUE TITLE
Credit card payment blocked by nonexistent postcode requirement

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4143] opened 2021-04-02 01:15 UTC
![Screenshot_20210402-125816](https://user-images.githubusercontent.com/5498878/113369456-dd8c6600-93bd-11eb-9d8d-d7d7fb3daa03.png)

User was trying to contribute to https://opencollective.com/ehf-community

There's no place to put in the postcode but it says postcode required.

**Comment by SudharakaP** [comment] 2021-04-02 02:07
Was looking at this and just to put down my analysis on the matter; my understanding is that we previously made the zip code conditionally render; https://github.com/opencollective/opencollective-frontend/pull/1523. However doing this can lead to inaccuracies as per https://github.com/stripe/react-stripe-elements/issues/20#issuecomment-401247331. Ideally we should render the postal code for all occasions but according to the previous bug it seems we had to remove the postal code from rendering for all instances. 😄 

@Betree @znarf : What I was thinking is, we could perhaps use the same logic we have now, but add an additional check such that, when stripe comes back with that error and if we are hiding the postal code (`hidePostalCode=false`) we will set [`hidePostalCode=true`](https://github.com/opencollective/opencollective-frontend/blob/32e9f0e17fb5388d943739ba85b42819fc36b0c6/components/NewCreditCardForm.js#L41). If this makes sense to you I can  do a pull request to try out this change. 😄

**Comment by Betree** [comment] 2021-04-02 06:34
I was able to reproduce by not entering the CVC. The error message is inaccurate and should be fixed, but the root cause is that the user did not enter any verification code.

![image](https://user-images.githubusercontent.com/1556356/113388255-2debcf80-938e-11eb-8911-70c194d43396.png)

**Comment by Betree** [comment] 2021-05-06 06:59
@piamancini Not entirely as we still don't have a specific message for a missing CVC code, but it seems that we now require the postal code which makes it more difficult to miss.

![image](https://user-images.githubusercontent.com/1556356/117254496-c15e6780-ae48-11eb-80d2-e5b8f80a48db.png)

**Closed** 2021-05-17 14:57 UTC
Labels: bug, complexity → simple, frontend
