### ISSUE TITLE
Localization issue in old version of Safari

### ISSUE THREAD

**Issue by mgm1313** [opencollective/opencollective#3095] opened 2020-04-28 20:19 UTC
**Describe the bug**

**To Reproduce**
1. Go to any organization page 
2. See error

**Screenshots**
![Schermafbeelding 2020-04-28 om 22 17 03](https://user-images.githubusercontent.com/9018689/80533495-029e7a80-899e-11ea-840f-f6c15e19948b.png)

**Desktop:**
 - OS: MacOS Mojave 10.14.6
 - Browser: Safari
 - Version: 12.1.2 (14607.3.9)

**Comment by Betree** [comment] 2020-04-29 09:20
Thanks for the report @mgm1313, we just got a similar one for French. Translations may be out of sync, I'll check that now.

![image](https://user-images.githubusercontent.com/1556356/80580115-54311e80-8a0b-11ea-9c8d-f3a3a196c6ec.png)

**Comment by Betree** [comment] 2020-04-29 15:45
@mgm1313 I've synchronized the translations, can you tell me if it's fixed on your side?

I've been unable to reproduce this issue on Chrome and Firefox, so it may be linked to Safari.

**Comment by mgm1313** [comment] 2020-04-29 15:48
@Betree Flushed my cache, but it's not yet fixed. 
For example the discovery page:
<img width="1552" alt="Schermafbeelding 2020-04-29 om 17 47 19" src="https://user-images.githubusercontent.com/9018689/80616713-85c4dc80-8a41-11ea-9683-d51389fe4c79.png">

I'm unable to reproduce on Firefox and Chrome on my machine as well. So seems to be Safari related indeed.

**Comment by Betree** [comment] 2020-04-29 15:54
@mgm1313 thank you very much, we're going to investigate based on that.

**Comment by znarf** [comment] 2020-04-29 16:08
@mgm1313 I'm not reproducing, what is your Safari version ?

**Comment by Betree** [comment] 2020-04-30 08:35
I just ran a more comprehensive test.
- No other browser (IE, Edge, Chrome, Firefox) seems affected by this.
- Safari 13 is not affected
- All previous versions of Safari seem affected (tested 12, 11 and 10.1)

**Comment by SudharakaP** [comment] 2021-06-18 13:28
@Betree : How can we test this. Now that we have a fix for this at, https://github.com/opencollective/opencollective-frontend/pull/6506 I think we could give this a test using that PR. However I don't have Safari. Maybe, @znarf if you have a mac? 😄

**Comment by Betree** [comment] 2021-06-18 13:47
@SudharakaP We need to test with an old version of Safari, the simplest is to use https://www.lambdatest.com real-time

**Comment by Betree** [comment] 2022-06-02 15:31
Another report for this: https://opencollective.slack.com/archives/C6JTTA4SK/p1654069464383359.

We don't have the capacity to maintain deprecated browsers in the team, but if someone is willing to help we're happy to merge contributions for this.

**Comment by Betree** [comment] 2023-12-27 10:29
According to https://caniuse.com/usage-table, Safari <= 12 now accounts for less than 0.1% of active browsers; we'll therefore not attempt to patch this on our side.

**Closed by Betree** 2023-12-27 10:29 UTC
Labels: bug, help wanted, frontend, complexity → unknown, wontfix
