### ISSUE TITLE
GraphQL error when viewing an expense

### ISSUE THREAD

**Issue by josegonzalez** [opencollective/opencollective#2262] opened 2019-07-22 02:54 UTC
**Describe the bug**

I'm attempting to browse to the expenses for the Dokku collective, and I cannot see what the expenses were due to a graphql error.

**To Reproduce**
1. Go to https://opencollective.com/dokku/expenses/
2. Click on the sidebar where it says Finpo
4. See error message that says "graphql error" - the source seems to be `FromCollectiveId not found`

**Expected behavior**

I would expect a view that shows who submitted the expense and a few details, such as on other collectives.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Safari
 - Version 12.1.1 (14607.2.6.1.1)

**Comment by Betree** [comment] 2019-07-22 07:55
Hi @josegonzalez! Sorry for this bug, we should not be displaying that `Finpo (inc)` link because they never submitted an expense to your collective. Root cause is apparently that we're counting a refund as a payed expense. Should be fixed today.

**Comment by Betree** [comment] 2019-07-23 10:04
Fixed by https://github.com/opencollective/opencollective-api/pull/2300, we now show only recipients who have already been paid (that's why the list appears empty for Dokku right now).

**Closed by Betree** 2019-07-23 10:04 UTC
Labels: bug, priority
