### ISSUE TITLE
In kind expenses/donations

### ISSUE THREAD

**Issue by shannondwray** [opencollective/opencollective#6978] opened 2023-09-05 08:28 UTC
## Who is your user?
Expense submitters 

## What are they trying to achieve?
"Some of our members have paid for things that our collective needs (such as Zoom subscriptions, and materials for distributing food) and would prefer not to get reimbursed for the expense and instead treat it as a donation. How can this be captured in Open Collective, or can it be? We have receipts for the materials, and the donor would like to get a tax credit for it if possible."

_When submitting an expense, I want to put the collective as the payee, so I can donate the $ back to the collective_

## How are they currently doing this?
"But it seems that the only way to do that is to have the donor submit the expenses, get reimbursed by the collective, and then re-donate the money. Is this the only way, or am I missing something?"

## How well understood is this problem?

 - [ ] Surfacing: if you feel this is a seed of an idea that needs to be researched.
 - [ ] Understanding: if you've done some research and feel it is already well understood and ready for shaping.
 - [ ] Shaping:  if you feel a solution is clearly defined and can be made into a pitch ([read more about shaping](https://basecamp.com/shapeup/1.1-chapter-02))
 - [ ] Pitching: if you feel that it is ready to be presented for prioritisation ([read more about pitching](https://basecamp.com/shapeup/1.5-chapter-06))

**Comment by Betree** [comment] 2023-09-18 06:16
Duplicate of https://github.com/opencollective/opencollective/issues/1895

**Closed by Betree** 2023-09-18 06:16 UTC
