### ISSUE TITLE
Account for bank fees when confirming pending order

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4144] opened 2021-04-02 01:23 UTC
## User story 
As a host admin, I need to input the actual amount that was received via bank transfer (or other means not integrated into the platform) when confirming a pending financial contribution on the host dashboard. For example, someone makes a contribution of $100, but actually what arrives in the bank is $95 due to bank transaction fees. When I confirm the transaction, it should credit the Collective $95 not $100.

## Best solution for this problem
I think the designers could come up with a better solution, but what I thought of was a box where you confirm the amount actually received. This would default to the amount the transaction was for originally, but could be edited to reflect the exact amount received, and that's what would be credited to the Collective balance.

<img width="1050" alt="Screen Shot 2021-04-02 at 2 19 17 PM" src="https://user-images.githubusercontent.com/5498878/113369873-e893c600-93be-11eb-9d1b-ba5cb5bb1895.png">

## MVP
The current workaround for this is to either confirm the order and then submit an expense to the Collective for the difference, or cancel the pending order and use Add Funds to manually credit the correct amount. Both of these are a lot of work for the admin and prone to human error.

**Comment by SudharakaP** [comment] 2022-01-05 14:25
This seems to be a duplicate of https://github.com/opencollective/opencollective/issues/4069 and if no objections I am closing this.

**Closed by SudharakaP** 2022-01-05 14:25 UTC
Labels: feature, complexity → medium, api, frontend, duplicate
