### ISSUE TITLE
HTML markup appearing in bank transfer instructions

### ISSUE THREAD

**Issue by fabianmendes** [opencollective/opencollective#4188] opened 2021-04-14 17:25 UTC
**Describe the bug**

**To Reproduce**
1. Go to any Collective.
2. Click on Donation.
3. Donate... (any amount).
4. See error: 
![image](https://user-images.githubusercontent.com/31230743/114752670-9179e380-9d24-11eb-85a4-4e8fb18bd918.png)

**Expected behavior**
Should not appear <br>  or <br/> whatever... nor <code> and </code> (see screenshot above).

**Desktop (please complete the following information):**
 - OS: RPi OS 32-bit.
 - Browser: Chromium
 - **Version  88.0.4324.187 (Build oficial)** Built on Raspbian , running on Raspbian 10 (32 bits)

**Comment by Betree** [comment] 2021-04-14 17:37
Thank you for reporting this @fabianmendes.

I thought we migrated all of them but apparently, we still have 41 hosts with HTML markup in their instructions. We should sanitize that to remove all markup.

```sql
SELECT * FROM "Collectives" c WHERE (settings -> 'paymentMethods' -> 'manual' -> 'instructions')::varchar LIKE '%<%'
```

**Comment by Betree** [comment] 2021-04-21 08:40
Actually, this is a duplicate of https://github.com/opencollective/opencollective/issues/4002

**Closed by Betree** 2021-04-21 08:40 UTC
Labels: api, bug, duplicate, important, task
