### ISSUE TITLE
Better support for other expense _payout_ methods (besides Paypal, like IBAN/SEPA)

### ISSUE THREAD

**Issue by jancborchardt** [opencollective/opencollective#1217] opened 2018-08-07 18:19 UTC
Currently the only proper way to receive expenses is Paypal. The "other" method feels strange, as it needs to be handled off-platform somehow then.

It would be great if there would be other _official_ methods, for example being able to put in an IBAN address to wire to. Or adding IBAN to the payment methods too, and using that for payouts as well.

URL for example: https://opencollective.com/opensourcedesign/expenses/new#

![screenshot from 2018-08-07 20-16-01](https://user-images.githubusercontent.com/925062/43794495-c3571aae-9a7e-11e8-830a-c6432f339baa.png)

**Comment by xdamman** [comment] 2018-08-08 09:29
Would love to do that. @marcogbarcellos is working on a new version of the ledger that will make it easier to support new payment methods.

**Comment by jancborchardt** [comment] 2018-11-18 20:36
Probably makes sense to reopen as it’s not there yet and also referenced in https://github.com/opencollective/opencollective/issues/1326 :)

**Comment by devurandom** [comment] 2019-01-08 20:41
> See also this poll about the payment methods that people would love to have: #919

Is there any reason not to close this as a duplicate of #919?

**Comment by devurandom** [comment] 2019-01-09 09:58
Thanks for the clarification. I did not understand the difference until you explained it.

Do you also have a list of possible providers for payouts?

I am right now looking for legal and possibly tax-free ways for a Tanzanian social free-software-based organisation to raise money for their operations. This has proven to be rather difficult so far, since being Tanzanian they do not have US or SEPA bank accounts, and PayPal and others we looked at so far do not operate in Tanzania. So it appears they require a truly intercontinental SWIFT transfer. (They do have an IBAN.) If OpenCollective could help here, that would be awesome.

**Comment by piamancini** [comment] 2019-01-09 14:57
Hi @devurandom unfortunately it's out of our scope - the only thing that comes to mind is thesegovia.com we would like to offer them as an option in the future but it's not in the roadmap. You can still use open collective of course to show how much funding you've received and how you are spending it, but you'd have to set up your own host.

**Comment by devurandom** [comment] 2019-01-25 15:33
> Hi @devurandom unfortunately it's out of our scope - the only thing that comes to mind is thesegovia.com we would like to offer them as an option in the future but it's not in the roadmap.

Is it already the time to contribute code implementing support for Segovia or are other steps needed prior to that?

**Comment by znarf** [comment] 2019-01-25 15:59
@devurandom Are you operating a Host, or do you know a Host who would be willing to use Segovia?

**Comment by devurandom** [comment] 2019-01-26 07:21
> @devurandom Are you operating a Host, or do you know a Host who would be willing to use Segovia?

Currently neither. I could operate a host for testing and development purposes, but my goal would be for this to be supported by opencollective.com itself.

**Comment by znarf** [comment] 2019-01-26 16:03
@devurandom Once available on Open Collective (the software and the platform), it needs to be activated by the Hosts (such as Open Source Collective) that are interested by Segovia support. I expect that each will somehow need to connect their bank account. Once done, people will be able to start asking for Segovia payouts on the Collectives available on these Hosts.

Do you want to use the Open Source Collective for your use case? If that's the case, let's check with @piamancini that they would activate Segovia if it was available on the platform. Just want to make sure that we don't waste anyone time.

**Comment by devurandom** [comment] 2019-01-27 09:17
> Do you want to use the Open Source Collective for your use case? If that's the case, let's check with @piamancini that they would activate Segovia if it was available on the platform. Just want to make sure that we don't waste anyone time.

I do not see myself running my own host (which would imply setting up an escrow account and/or a non-profit organisation to handle the money transfers, as far as I understand), so yes, I would like to use the Open Source Collective's services.

**Comment by nemchik** [comment] 2019-04-17 14:20
Have you guys considered allowing Stripe itself to do the payouts? Another donation platform I have used (BeerPay) has the recipients use Stripe directly to receive donations. Somehow they have managed to do this without fees, but in that scenario donations go directly from the end user making the donation to the recipient and there is no project balance or expenses, etc.

Anyway it seems like your platform is already working with Stripe to receive funds, so why not allow payouts via Stripe as well?

I like that #919 had a poll that allowed voting for other payment methods, maybe a similar poll for payout methods could be made?

**Comment by rugk** [comment] 2019-04-24 17:00
So is not this a dupe of https://github.com/opencollective/opencollective/issues/1742?

**Comment by nemchik** [comment] 2019-04-24 17:10
@rugk I may be mistaken, but those issues you have posted seem to be on the topic of donors having more transaction options when making donations. This issue is about collective's having more transaction options for payouts.

**Comment by rugk** [comment] 2019-04-24 17:15
Ah okay, did not know that. Still don't get it all, where is used what and what issue is about what here… Actually, you should just support SEPA anywhere, taht's the point. :smile:

**Comment by Betree** [comment] 2020-09-16 08:01
IBAN/SEPA payouts are now supported via Transferwise (see https://docs.opencollective.com/help/fiscal-hosts/payouts/payouts-with-transferwise). I think we can close this one?

Ping @kewitz

**Comment by kewitz** [comment] 2020-09-16 12:54
Resolved by #2836.

**Closed by kewitz** 2020-09-16 12:54 UTC
Labels: api, backlog, complexity → complex, feature
