### ISSUE TITLE
NZD Host's Wise balance displaying in EUR

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4091] opened 2021-03-16 08:56 UTC
<img width="788" alt="Screen Shot 2021-03-16 at 9 55 29 PM" src="https://user-images.githubusercontent.com/5498878/111282031-6b6c0f80-86a2-11eb-995c-3c683c268a54.png">

**Comment by kewitz** [comment] 2021-03-23 21:56
@alanna is this an intermittent bug? I notice the screenshot on the other bug-report displays NZD.

**Comment by alanna** [comment] 2021-03-23 22:37
Yeah it has disappeared now. Weird.

**Comment by kewitz** [comment] 2021-03-24 12:55
@alanna the requested behavior is already implemented and this can be caused by issues on Wise's API.
I'll close this for now but I would be curious to know if this ever happens again.

**Closed by kewitz** 2021-03-24 12:55 UTC
Labels: api, bug, frontend, transferwise
