### ISSUE TITLE
Calculate host fee on pre-tax total

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4492] opened 2021-07-23 23:35 UTC
Example: Contributor buys event ticket. The ticket price is $100. The system adds local tax (15% GST), so the total payment is $115. 

Now: 10% Host fee is calculated on the total of $115, so $11.50 is diverted to the Host balance, $15 tax is not credited to any balance, and $88.50 to the Collective (I think? please check that the Collective isn't getting 90% of $100=$90 because in that case the totals won't add up).

How it should be: 10% host fee calculated on tax exclusive amount of $100, so $10 goes to Host, $90 to Collective, and $15 held back for tax.

Why: The Host has to give that $15 to the government and it belongs to neither to Collective nor the Host. The current way it's calculated unfairly gives extra money to the Host and less to the Collective, and makes things confusing in the ledger trying to get everything to add up when tax is being calculated.

I would suggest we actually go back and retroactively fix all such transactions, but I fear it would cause a lot of problems because this will also affect platform fee totals, etc. But on the other hand, this only affects a small number of hosts who charge local tax and a small number of their transactions that attract local tax. I would like this retroactively fixed for OCNZ.

**Comment by ankitzm** [comment] 2021-08-12 17:42
I am quite new to this, so can I know where do we need to improve the code.

**Comment by alanna** [comment] 2023-02-10 03:06
This is causing issues for OCNZ's accounting, I hope it can be fixed soon

**Comment by alanna** [comment] 2023-02-22 22:32
@Betree wondering if there's any update on this one?

**Comment by Betree** [comment] 2023-02-23 07:08
@alanna It has been prioritized for implementation this sprint

**Comment by Betree** [comment] 2023-04-04 07:40
Root cause fixed in https://github.com/opencollective/opencollective-api/pull/8665

- [ ] Run the script to fix data in production
- [ ] Create expenses to settle for OCEU and OCNZ
- [ ] Check if expenses are concerned too (for expenses between hosts): https://github.com/opencollective/opencollective-api/blob/87ed2b1a7d952929d511b06fb138431116875a34/server/models/Transaction.js#L620

**Comment by Betree** [comment] 2023-04-05 08:31
Settlement expenses created:
- https://opencollective.com/opencollective/expenses/132271 (OCNZ)
- https://opencollective.com/opencollective/expenses/132273 (Europe)

We're all done here!

**Closed by Betree** 2023-04-05 08:31 UTC
Labels: bug, complexity → medium, api, tax
