### ISSUE TITLE
Represent funds coming through Events and Projects in the parent Collective budget stats

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#4360] opened 2021-06-11 22:47 UTC
When you look at https://opencollective.com/modulo it appears like they have raised $0.

<img width="1101" alt="Screen Shot 2021-06-12 at 10 40 20 AM" src="https://user-images.githubusercontent.com/5498878/121755164-9b746300-cb6a-11eb-83a9-6e57270281f3.png">

But this is not actually the case. It's just that they are running everything through Projects.

<img width="1189" alt="Screen Shot 2021-06-12 at 10 41 01 AM" src="https://user-images.githubusercontent.com/5498878/121755217-bcd54f00-cb6a-11eb-96a9-49ce89c2b92e.png">
<img width="1110" alt="Screen Shot 2021-06-12 at 10 41 16 AM" src="https://user-images.githubusercontent.com/5498878/121755220-bf37a900-cb6a-11eb-85f8-b696007928c2.png">

This creates an inaccurate picture of this Collective's finances.

I understand that we want Projects to have separate budgets, and I support that approach, but what if a contribution to a Project first went to the parent Collective as a credit, then immediately was transferred to the Project budget, debiting the parent budget and cancelling the transaction out? That way the parent budget would reflect all funds raised through all its Projects, but the money would be sitting in the Project budget.

I think this is important for transparency, record-keeping, and reporting. If a Collective wants to export all its transactions, right now they would have to individually go to each different Project and export them, then manually combine them together, which would be time consuming and error-prone. It's also messing up data like the leaderboard (#4350) because the system counts Project as separate Collectives. We have gotten feedback from users that they are confused and put off by Projects having a top-level URL (opencollective.com/project instead of opencollective.com/collective/project) - all of this leads me to think we should really treat Projects more as sub-parts of Parents, not as much as totally independent. Passing the budget through the Parent is part of this, conceptually.

**Comment by alanna** [comment] 2021-06-11 22:51
Oh god I've just stumbled across another reason for this: OCF is going through an audit and for that they will be looking at the balances of every Collective and how it changes over time. If a Collective's funds are spread out to multiple projects without good data showing the connections, this will be very messy to figure out for next year's audit.

**Comment by znarf** [comment] 2021-06-12 08:11
There are some good points, seems obvious that the balance should somehow expose money hold on Projects and Events.

> We have gotten feedback from users that they are confused and put off by Projects having a top-level URL (opencollective.com/project instead of opencollective.com/collective/project)

Normally, they should not have a top-level URL. I know that sometime it's the case but this is a bug that should be fixed.

>  If a Collective's funds are spread out to multiple projects without good data showing the connections, this will be very messy to figure out for next year's audit.

For reporting, it's not a new problem because we used to have Events with the same behavior. How were we doing audits/accounting with Events?

**Comment by alanna** [comment] 2021-06-13 04:01
> For reporting, it's not a new problem because we used to have Events with the same behavior. How were we doing audits/accounting with Events?

I'm not sure. This same question applies to things like monthly/yearly Host reports, and for the "XYZ is Hosting 56 Collectives" stat on Host pages. Are events counted as seperate Collectives for these purposes? Is money going through events left off the totals for reporting?

@leonardohofling how have we been handling funds in Events when it comes to things like the metabase dashboards we've provided the accountants? Could this be a cause of the discrepancies I just emailed you about re: OCF audit?

**Comment by BenJam** [comment] 2021-07-01 16:24
> If a Collective's funds are spread out to multiple projects without good data showing the connections

the connections are there, collectives with a parent collective are what you're looking for: https://opencollective-metabase.herokuapp.com/question/350

**Comment by alanna** [comment] 2021-07-01 22:47
It's helpful that we can get to the data @BenJam but this is really about how the data shows up in CSV exports and in-app reports and screens, because that's what's used for accounting and grant reporting back t funders, etc. We have to make sure the user-facing data is handled correctly because the data is used for official purposes and we can't give a metabase dashboard to every Collective and Host.

**Comment by alanna** [comment] 2021-07-06 21:19
Hey is this going to be prioritised this sprint? It keeps causing problems. Is it considered part of ledger refactoring? @Betree @piamancini

**Comment by Betree** [comment] 2021-07-07 06:50
It's not part of the ledger refactoring project (https://github.com/opencollective/opencollective/issues/4124), which is currently closed and marked as done.

**Comment by BenJam** [comment] 2021-07-12 09:53
We are looking at improving CSV reports this sprint, so I hope that we can incorporate this into that https://github.com/opencollective/opencollective/discussions/4405#discussioncomment-942132

**Comment by znarf** [comment] 2021-08-04 12:55
On the budget side, it's a bit problematic to change the definition of the balance and integrate Projects and Events. Balances are completely separated and we use this to prevent people to spend more than their balance. If I have $50 in my Collective and $100 in my Event and we display $150 as a balance. Does this mean that I can spend the $150? That would be a problem. How do we make it clear that the "real" balance is only $50 if we display everywhere $150?

On the transactions and CSV side, it's also dispruptive to introduce those transactions. Are we sure that this is what all our users want or need? What do we we do for the one willing to keep current behavior and not having mixed transactions?

We're running Events this way since the beginning of Open Collective. Why did we not feel this important pain in those 5 years?

From Engineering standpoint, it's too complex and not a project we can lead right now. We can look at it when key questions will be addressed and clear specs given.

**Comment by BenJam** [comment] 2021-08-04 14:20
> Why did we not feel this important pain in those 5 years?

fair point. 

I think maybe the best thing to do here is list balances on the cards for projects and/or include the total balance/raised/distributed in the overview:

![Screenshot 2021-08-04 at 15 20 37](https://user-images.githubusercontent.com/158833/128197827-b6e92493-06b0-4c43-8387-2c82ae0d2283.png)

**Comment by alanna** [comment] 2021-08-04 21:50
> If I have $50 in my Collective and $100 in my Event and we display $150 as a balance. Does this mean that I can spend the $150? That would be a problem. How do we make it clear that the "real" balance is only $50 if we display everywhere $150?

This was not what I suggested. I suggested that money going to Events and Projects passes *through* the parent. So it would look like:

* User contributes $50 to Project
* $50 is credited to Parent 
* $50 is immediately debited from Parent and credited to Project
* End results is $0 in Parent balance, $50 in Project balance
* But the funds are acknowledged in the parent's stats of total raised and disbursed, just like if a Collective raised $50 and then donated it to another Collective in the same Host.

This way, a parent Collective with all or most activities in Events and Projects will not appear to be dead when in fact it's active, and the stats of the Parent will make sense. We have to remember that most people looking at these numbers are using them as heuristics for non-quantitative queries like "How active is this community?" "Who funds this project?" "Is this genuine?" - and other users are looking for quantitative things like "How much money has this Collective raised overall?" which are also broken by not reflecting Events and Projects in the parent's budget stats.

None of the above will break integrity of the ledger or falsely show available money in two places at once, and it will also not require complicating the already complicated budget stats info box with data about Events and Projects.

**Comment by alanna** [comment] 2021-08-08 21:39
@znarf @BenJam what do you think of my suggestion above?

**Comment by tom-here** [comment] 2021-08-10 12:42
> @znarf @BenJam what do you think of my suggestion above?

I'm new to the discussion here, but I agree with Alanna's suggestions. (This bit from her is particularly important IMO: 'We have to remember that most people looking at these numbers are using them as heuristics for non-quantitative queries like "How active is this community?" "Who funds this project?" "Is this genuine?" - and other users are looking for quantitative things like "How much money has this Collective raised overall?" which are also broken by not reflecting Events and Projects in the parent's budget stats.. Yes Also with BenJam who suggested we list Project numbers in the budget overview.') 

I also agree with @BenJam about listing Projects on the budget overview.

Whatever can be done to aid transparency and simplicity for donors/funders who are not on OpenCollective a lot and likely won't have the patience to dig around - they just want to see the financial figures front and center. And so do I as I monitor the accounts!

**Comment by znarf** [comment] 2021-08-10 13:06
@alanna I'm sceptic about your proposal in this state:

- "$50 is immediately debited from Parent and credited to Project". This transaction is problematic because it would be attributed to the Parent Collective and not to the Original Source. The Project budget will be full of such transactions and will not be much readable. It's in my opinion a hack, and a complicated one.
- This will not answer the balance question: how much money is globally hold between the Collective and its Projects. Even if we want to keep budgets and balance separated, that's a legit question that we want to answer.
- The disbursed metric will be flawed. If I donate $50 directly to a Project, is it really appropriate to say that $50 was disbursed from the Collective to the Project? Perhaps some people will be fine or happy with it, but some may also find it questionable.

In the end, I think we don't have a choice but to support fully the 2 use cases.

For a Collective:

- Transactions
  - a) Only Collective Transactions
  - b) All transactions including the one in Events/Projects
- Metrics
  - a) Collective balance/raised/disbursed
  - b) Collective aggregated balance/raised/disbursed including the one in Events/Projects

For a Fiscal Host:

- Transactions
  - a) Only Host Transactions on its own account
  -  b) All transactions including the one in Hosted Collectives (and their Events/Projects)
- Metrics
  - a) Host account balance/raised/disbursed
  - b) Host aggregated balance/raised/disbursed including the one in Events/Projects. (aka: Total Money Managed, etc ...)

Some people are interested in a) some in b). We have to find a way to surface the data in the UI without resorting to changes in our model. There is no huge difficulty to fetch the data from the API. The problem is more on how to display everything.

For the Transactions list, we could simply have a checkbox to switch between mode a) and mode b). We could even default to b) if we think it's the most relevant.

For the metrics, I think the best is to display both metrics. While it may seem bloated, I think the proposal from @BenJam is in the right direction. We can definitely make it look better with the help from the design team.

**Comment by alanna** [comment] 2021-08-10 21:33
I understand the need to keep the ledger consistent, but I still think there's a way to achieve that along the lines of what I suggested, and I still think it's very important to do it. Let's discuss in the team meeting today @znarf

**Comment by alanna** [comment] 2022-03-04 05:04
Bumping this one based on user feedback from some large Funds that this issue prevents them from wanting to show their budgets on their page because it wouldn't accurate reflect reality when a lot of their activities happen in Projects (i.e. the parent page looks dead with a tiny budget even if there's lots of money in Projects). Disincentivising transparency due to this issue isn't a great outcome, so hopefully we can handle showing Project transactions better soon.

**Comment by RCheesley** [comment] 2022-04-01 12:20
+1 from me - this is a real issue and does suggest less funds available to the collective than there actually are. Also as an Admin it is hard for me to know where our funds are currently distributed!

**Comment by GemmaTuron** [comment] 2022-04-01 17:21
I see I'm a late comer to this discussion. For our particular case, the solution proposed above by @alanna where funds always pass through the main budget would be good enough... our issue is that funders and contributors might think we are not raising any money if it goes directly to projects and does not show in the Total Budget

**Comment by alanna** [comment] 2022-04-04 21:01
Another reason this needs a better design: we don't show the budget section if a Collective has had no transactions. If all a Collective's transactions are in Events and Projects, the entire budget section will appear hidden or missing on the parent, even if they are financially active in sub-Collectives. This doesn't look right and is misleading in terms of transparency.

**Comment by alinamanko** [comment] 2022-04-05 20:17
Another angle to this... Any transfers between the main budget to the project still default to show as 'contribution' and only when the project balance is zeroed, the classification would default to 'balance transfer'. This lack of clarity in separating the activity causes balances to inflate and can lead to reaching wrong conclusions when looking at the collective activity and a reconciliation of the financial data.

**Comment by alanna** [comment] 2022-04-05 20:33
Good point. We need to ensure the transfers back and forth between projects and parent don't artificially inflate the overall picture of the budget.

**Comment by BenJam** [comment] 2022-04-25 14:21
Proposed a cheeky MVP for this today: consider _only_ the current balance across the Collective's Events and Projects, and add that alongside the Collective's balance. I think there are a couple of options here:

- state the total balance and add 'includes x amount in events and projects'
- state the collective's balance and add 'and X amount in events and projects' 

@opencollective/design we should probably do a quick (30 min) call for this.

**Comment by Memo-Es** [comment] 2022-04-27 02:35
Events and projects are part of a project's budget IMO, so I think we should go with:
 - state the total balance and add 'includes x amount in events and projects'

Eager to hear what @aminakazi thinks

**Comment by alanna** [comment] 2022-04-28 22:53
Will this issue include enabling Collective admins to view and approve all Collective expenses, including those in Events and Projects, in one place, or should I raise a separate issue for that?

**Comment by debryc** [comment] 2022-04-29 00:01
I think adding the balance of each project on the collective page would help with this!
<img width="436" alt="Screenshot of Slack (4-28-22, 8-01-13 PM)" src="https://user-images.githubusercontent.com/3423434/165866219-40d64eab-e9fc-4258-b21f-24f6bd19ac14.png">

**Comment by aminakazi** [comment] 2022-06-13 09:34
**Proposed solution:**
![Show Funds](https://user-images.githubusercontent.com/48468919/173323864-261bd4f3-7445-4382-9ba4-67faa954ee89.jpg)
We add a sentence under the budget overview section which mentions the amount from events and projects. We link the word events and projects to their sections respectively.

**Figma Link can be [found here](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/?node-id=17375%3A220833) 🎨**

**Next Steps:**
• Define how total raised and total disbursed are calculated.
• Redesign this section based on the change in the definition.

**Comment by piamancini** [comment] 2022-06-13 13:18
- [ ] Define what total raised and disbursed should account for. @znarf @aminakazi

**Comment by debryc** [comment] 2022-06-22 21:04
> **Proposed solution:** ![Show Funds](https://user-images.githubusercontent.com/48468919/173323864-261bd4f3-7445-4382-9ba4-67faa954ee89.jpg) We add a sentence under the budget overview section which mentions the amount from events and projects. We link the word events and projects to their sections respectively.

We actually want to see funds that are not yet allocated to projects. We need to know what balance is available for collective-level expenses. With this new design that information is no longer easily available.

**Comment by znarf** [comment] 2022-07-04 10:46
@aminakazi Sorry, late feedback, I'm against changing the definition of balance that is currently displayed. For now, if we display only one balance, this should stay the current one:
- this is the balance that we're communicating in various reports
- this is the balance we use to allow or disallow Expenses (is there enough budget?)

To solve this issue, I would prefer:
- to use a tool tip to provide extra explanations and/or alternative balance
- use the text on the bottom to explain that there is more money available in Events and Projects.

**Comment by znarf** [comment] 2022-07-04 10:54
Q2 Sprint 2 Week 5:

- [ ] ship Frontend implementation

**Comment by znarf** [comment] 2022-07-12 08:06
Latest version:

<img width="503" alt="Screenshot 2022-07-12 at 10 06 04" src="https://user-images.githubusercontent.com/806/178441408-916ea72e-512f-406d-80c2-f3da4056299d.png">

**Comment by BenJam** [comment] 2022-07-22 10:54
closing as this is done for mo, feel free to open a new issue and link this for context if needed.

**Closed by BenJam** 2022-07-22 10:54 UTC
Labels: complexity → complex, api, frontend, enhancement, needs specs, important
