### ISSUE TITLE
Fiscal host settings

### ISSUE THREAD

**Issue by lukeeey** [opencollective/opencollective#2309] opened 2019-08-07 11:11 UTC
**Describe the bug**
The Fiscal Host can be removed with any confirmation and once its gone, you cant apply to join it again as the slug is already taken by your collective.

**Expected behavior**
I would be able to join the host again without deleting my collective and creating it again from the host page (https://opencollective.com/opensource)

Also it would be nice if there was a confirmation before it is removed, as its very easy to accidently remove it.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome

**Comment by flickz** [comment] 2019-08-07 11:51
@lukeeey Thank you for reporting this, can you describe how to recreate the issue with screenshot maybe?

**Comment by lukeeey** [comment] 2019-08-07 13:17
No because i dont fancy doing it again. I explained it and its extremely easy to do, just click the button to remove the host

**Comment by alanna** [comment] 2019-08-08 21:41
#2156 would help in this situation. I believe that's being worked on.

@lukeeey You don't need to recreate your Collective in order to join again, normally. This situation is being caused by a bug #2281 - which is supposed to be fixed already. Maybe the fix has not yet been fully deployed. @znarf can you confirm?

The way it's supposed to work is if you have a Collective without a host and you go to a host's page, it should give you the option to join with your existing Collective.

@lukeeey sorry you ran into this problem. Can you please let us know the name of the Collective you created? We should be able to put it back in the host manually on our side if the feature isn't working again by today.

**Comment by znarf** [comment] 2019-09-30 12:38
@lukeeey @alanna Is that still an issue? If not, this should be closed.

**Comment by lukeeey** [comment] 2019-09-30 18:00
i dont fancy testing it

**Comment by znarf** [comment] 2019-09-30 21:02
Ok, this was a combination of issues that are all fixed now.

**Closed by znarf** 2019-09-30 21:02 UTC
Labels: api, bug, complexity → simple, frontend
