### ISSUE TITLE
New Payment method - Ideal (Mainly used in the Netherlands) 

### ISSUE THREAD

**Issue by shannondwray** [opencollective/opencollective#5904] opened 2022-08-25 11:21 UTC
## User story 
Most people in the Netherlands use Ideal as their payment method rather than Paypal or credit card 

## Best solution for this problem
Having Ideal as a payment option on Open Collective 

<details>
  <summary>Triage Template (team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by Betree** [comment] 2022-08-25 12:50
Duplicate of https://github.com/opencollective/opencollective/issues/5618

**Closed by Betree** 2022-08-25 12:50 UTC
Labels: feature, duplicate
