### ISSUE TITLE
Event: content is overlapping footer

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2524] opened 2019-10-14 11:22 UTC
See: https://opencollective.com/socially/events/launch-179ec824

![image](https://user-images.githubusercontent.com/1556356/66747757-93d85480-ee85-11e9-832e-35c711353237.png)

**Comment by jeffin143** [comment] 2019-10-16 07:52
https://opencollective.com/codenplay/events/formation-gratuite-pour-enseignants-10559ev

Why do other  collective page as expected and only socially/events/launch is not working as expected ?

**Comment by Betree** [comment] 2019-10-16 08:17
@jeffin143 That's a good question :-) I didn't investigate, but one difference is that this one doesn't have a map. Maybe the layout is broken only when there's no map displayed.

**Comment by jeffin143** [comment] 2019-10-16 13:03
> @jeffin143 That's a good question :-) I didn't investigate, but one difference is that this one doesn't have a map. Maybe the layout is broken only when there's no map displayed.

No, I guess that isn't the problem, https://opencollective.com/socially/events/private-beta-launching-d1d8f401#location , with map too the issue is there, I guess the issue is 
` 1 Person going ` with that person name :)

I am not sure from where is that line coming,  because other event pages doesn't have that , or is there any option to enable that.

**Comment by jeffin143** [comment] 2019-10-16 17:01
> > @jeffin143 That's a good question :-) I didn't investigate, but one difference is that this one doesn't have a map. Maybe the layout is broken only when there's no map displayed.
> 
> No, I guess that isn't the problem, https://opencollective.com/socially/events/private-beta-launching-d1d8f401#location , with map too the issue is there, I guess the issue is
> `1 Person going` with that person name :)
> 
> I am not sure from where is that line coming, because other event pages doesn't have that , or is there any option to enable that.

I found the error, and opened a PR to rectify it.

Thanks :)

**Comment by znarf** [comment] 2019-10-21 09:19
Closed in https://github.com/opencollective/opencollective-frontend/pull/2841

**Closed by znarf** 2019-10-21 09:19 UTC
Labels: bug, frontend
