### ISSUE TITLE
New pricing page (design)

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#2592] opened 2019-11-04 15:29 UTC
We need to update https://opencollective.com/pricing to reflect the new business model and focus on self hosted collectives.

I'd keep the same general design with a FAQ at the bottom.
Just the table needs to change:
![](https://d.pr/free/i/zQCUdy+)

And we need a "create your collective" call to action somewhere, or a button below each column?

**Comment by xdamman** [comment] 2019-11-08 13:57
FAQ and copy for the email announcement / blog post: https://docs.google.com/document/d/18vHDQLGz6aCgcdoGxKRlk_4MTZWYBwzTErGoYxC1EzM

**Comment by danielcompton** [comment] 2019-11-18 19:28
It is sometimes easier for people to read pricing pages if each tier only includes the features that are unique or different from the previous tier. If you did that here, it would make it much easier for people to see that there are only two metrics that change between tiers: number of collectives, and the amount of financial contributions you can record. 

Given that there currently aren't any other features, it might look good to have all of the features in one list, and then the two features + price on each tier?

**Comment by xdamman** [comment] 2019-11-19 16:39
That's good feedback. Is there a pricing page somewhere that you particularly like to illustrate that?
Also I've seen your comment in the google doc, thanks for contributing! :-)

**Comment by danielcompton** [comment] 2019-11-20 21:58
https://www.campaignmonitor.com/pricing/ has an interesting way of adding a + to features which are additional from the previous tier:

<img width="1457" alt="Screenshot of Safari (21-11-19, 10-56-26 AM)" src="https://user-images.githubusercontent.com/811954/69281684-9892e400-0c4d-11ea-90e9-6bcb1a8e6720.png">

https://freshdesk.com/pricing has the more traditional "Everything in tier -1 and..."

<img width="1182" alt="Screenshot of Safari (21-11-19, 10-57-33 AM)" src="https://user-images.githubusercontent.com/811954/69281745-b9f3d000-0c4d-11ea-9438-adff9f6f315d.png">

Profitwell/Price Intelligently have done a lot of writing on this over the years: https://www.priceintelligently.com/blog/topic/saas-pricing-page, https://www.profitwell.com/blog/pricing-page-examples.

**Comment by alanna** [comment] 2019-11-20 22:20
@xdamman sorry it took me a while to watch the video where you go over this, but I'm catching back up slowly.

Here are some initial notes. Basically I agree with the comments from the team members that it's going to be very confusing as currently designed, but I think we can make it a lot better by finding out about the user and only showing them pricing info that makes sense for their situation.

* Clarify *who* pays - not only for OSC, but also WWcode and all other fiscal hosts. Select options like a wizard and then and show details, otherwise it's going to give people confusing info.
* We need to empower fiscal hosts to set their own pricing for Collectives, who should never really think about OC's pricing, with fee options beyond just % ($x/mo, free, etc). Without that info in our system we can't give people accurate info about what they'll pay.
* Record financial contributions - expand this description to say 'other payment methods (bank transfer, Paypal, etc)' because people probably won't get it.
* Logically, all pricing is for *hosts only* (including hosts with only one Collective). Collectives should not be the target for pricing at all, because the answer to "how much" for Collectives is "it depends on your host". The issue is that most people don't know if they are acting as a host or a Collective and it's hard to explain. Our logic and the user's logic are different here and that's what's causing the issue.
* The divide is not "open source" vs another type, it's "fiscal hosted" vs "self hosted". It's not only OSC that will get caught up in this confusion if we don't get it right.

I have more concrete ideas about how to resolve some of this. I will jump into the Google doc and work there on specifics as soon as I can.

**Comment by alanna** [comment] 2019-11-21 03:49
OK I have had a go designing a pricing wizard in the google doc, and at the first part of the FAQs. - @xdamman and @piamancini please have a look.

I haven't had a chance to get into the fiscal hosting FAQ, email to fiscal hosts, and blog post content yet but I will soon.

**Comment by alanna** [comment] 2019-11-22 09:45
I've now worked on the FAQ, email, and blog content, so I think I've addressed everything. I hope it's helpful! Please let me know if you need more feedback @xdamman @piamancini

**Comment by xdamman** [comment] 2019-11-27 20:48
Here is another proposal to make the distinction clear between creating an independent collective or joining a fiscal host where each fiscal host could have their own pricing. 

Note that it has been decided that the open collective platform should only have a billing relationship with the host moving forward to simplify everything. So instead of showing 5% platform fee and 5% host fee for the open source collective host, we will show 10% host fee and then we will charge platform fees to the host. 
So it’s up to each host to come up with their own pricing strategy. For example, the All For Climate host will most likely offer the service for free but will be funded by various foundations. 

![](https://d.pr/free/i/WpxdS3+)

![](https://d.pr/free/i/cNbs2b+)

![](https://d.pr/free/i/Ie9y6x+)

PDF version: https://drive.google.com/file/d/1txJh75MkOfC8Gf8Wqbvf3CdAUT4Od_SF/view?usp=drivesdk

**Comment by znarf** [comment] 2019-11-27 21:16
"Independent collective" makes me think it's just for for a single one, it's difficult to understand why you would host multiple collectives as "Independent collective".

**Comment by alanna** [comment] 2019-11-28 01:43
This is a step in the right direction for sure @xdamman  

Although I don't understand why it's better than asking them in plain language how they will be set up and showing them the relevant info (the wizard approach). In your design, we still need a way to communicate about what a fiscal host means because the majority of people looking at this will have no idea which category they fit in and won't be familiar with our language. Most fiscally hosted Collectives don't even understand they are fiscally hosted. That's why the wizard was designed to walk them through to the right category.

@znarf is right - there are actually three options: independent Collective (self hosted, show only starter and small info), fiscally hosted (show options for joining different hosts and their fees), and becoming a fiscal host (show medium, large, network info).

**Comment by piamancini** [comment] 2019-11-28 14:22
This is my proposal for content: 

This is my proposal for the design of the pricing page https://docs.google.com/document/d/1y--R5DMaEf4v_iWBmuY1wRA-IawjvGILmF4wur4bGEM/edit#

It's more descriptive but I think it's clearer.

**Comment by alanna** [comment] 2019-11-28 22:59
Looks really good @piamancini - I made some phrasing and formatting changes to make things a bit more clear. I agree with your approach. I think it succeeds at simplifying things without oversimplifying them and risking misunderstanding.

**Comment by piamancini** [comment] 2019-11-29 10:35
ok great. I had a quick call with @raulgrafico yesterday, we'll do some basic wireframes to push this forward.

**Comment by piamancini** [comment] 2019-12-04 21:33
To keep record, these are the initial wireframes done for this page. 
![Image from iOS](https://user-images.githubusercontent.com/3671070/70183328-dc71f880-16e5-11ea-90e0-718593e54a7c.jpg)

@raulgrafico is working on better ones on figma - we'll update here before the end of the week. 

@znarf we can already put together a project to share with the community to see if someone wants to take this on. We are not too far from having a good enough page to get us unblocked.

**Comment by znarf** [comment] 2019-12-05 13:15
Work In Progress in Figma: https://www.figma.com/file/KinuveYf4WUlRIXzMTnmIsmO/OC.COM-XX1-%2F-Lab?node-id=4158%3A591

![Screenshot 2019-12-05 at 14 15 42](https://user-images.githubusercontent.com/806/70238518-b55d0a80-1769-11ea-9083-4971b7e47f02.png)

Any plan for a mobile version?

**Comment by piamancini** [comment] 2019-12-05 14:32
@znarf 
We feel there hasn't been a lot of enquiry on this so at this stage we are using this page to reach out to existing an potential hosts with the pricing to gauge their reaction. Once we get some feedback, we'll close the initial pricing option, iterate if needed and close design.

**Comment by xdamman** [comment] 2019-12-09 10:37
Looks great so far!

Small wording comments:
- "The starter plan includes" should probably be "All plans include"
- On the "Add funds received through other channels", the limit should be "per year" or "yearly budget".

**Comment by piamancini** [comment] 2019-12-18 20:46
New iteration: https://www.figma.com/file/KinuveYf4WUlRIXzMTnmIsmO/OC.COM-XX1-%2F-Lab?node-id=4158%3A591

<img width="683" alt="Screen Shot 2019-12-18 at 9 37 20 PM" src="https://user-images.githubusercontent.com/3671070/71121406-b9177500-21de-11ea-93cc-a5edcd644346.png">

<img width="749" alt="Screen Shot 2019-12-18 at 9 37 41 PM" src="https://user-images.githubusercontent.com/3671070/71121980-d7ca3b80-21df-11ea-9c7b-fd6a3689f265.png">

<img width="663" alt="Screen Shot 2019-12-18 at 9 37 54 PM" src="https://user-images.githubusercontent.com/3671070/71121991-de58b300-21df-11ea-93ca-6d4fadafabda.png">

**Comment by alanna** [comment] 2019-12-18 21:56
Looking really good! So much clearer. Very very close to being ready to go.

A few notes:

* I don't think "create bank transfer orders" will make sense to users (that's more our internal lingo). How about "raise money via bank transfer".
* Put the bank transfer bullet point above the 'other channels' one (makes more sense grammatically).
* On the hosts table, we mention bank transfer as an example of using "add funds" and as a seperate feature. This is confusing. Instead of saying "e.g. via bank transfer" let's say "e.g. payments you've invoiced, cash, or third party channels like a shop").
* Let's add a "learn more" link from the host pricing table to https://opencollective.com/become-a-fiscal-host.

I would be happier if we were also fixing the issues around host fees at the same time, to make the value pitch to hosts stronger when we tell them we're going to start charging them. But I guess it's not strictly required for MVP. 
Specifically I mean:
* Add host fees automatically
* Needing a host *and* a Collective for the host's budget instead of having it integrated
* More options for hosts to charge Collectives besides a %, such as $x/mo
* Display host fees on the host cards and add better filtering so Collectives can find the right host (e.g. country, nonprofit status, keywords/tags).

**Comment by alanna** [comment] 2019-12-18 22:11
@piamancini I have updated the [emails to fiscal hosts and self-hosted Collectives](https://docs.google.com/document/d/1y--R5DMaEf4v_iWBmuY1wRA-IawjvGILmF4wur4bGEM/edit#heading=h.c2n4i0eyczc1). Do you think we should move forward with those now?

**Comment by piamancini** [comment] 2019-12-19 08:05
@alanna yes let's do that. I've been scheduling calls as well to get some more accurate idea. I'd like to share this in blog format during January

**Comment by piamancini** [comment] 2020-01-07 09:51
Closing this issue since designs for this are now completed. Implementation issues should be opened separately. 

Final Designs: 

**Single Collective that is self hosted:** 
<img width="521" alt="Screen Shot 2020-01-07 at 10 49 50 AM" src="https://user-images.githubusercontent.com/3671070/71885865-85739f00-313b-11ea-86e6-02253d907d82.png">

**Collective that needs a fiscal host**
<img width="525" alt="Screen Shot 2020-01-07 at 10 50 02 AM" src="https://user-images.githubusercontent.com/3671070/71885867-860c3580-313b-11ea-9c28-638ef43352b7.png">

**Fiscal Hosts**
<img width="524" alt="Screen Shot 2020-01-07 at 10 50 13 AM" src="https://user-images.githubusercontent.com/3671070/71885868-860c3580-313b-11ea-891c-8d3a5c64a9d6.png">

**Closed by piamancini** 2020-01-07 09:51 UTC
Labels: design
