### ISSUE TITLE
If a hosting applicant changes the url before being accepted/rejected, the application disappears from the host's dashboard

### ISSUE THREAD

**Issue by kaylarep** [opencollective/opencollective#4432] opened 2021-07-07 00:30 UTC
**Describe the bug**
When an application comes in, we can find it in our dashboard's 'Pending application' tab (OCF as an example: https://opencollective.com/foundation/dashboard/pending-applications#application-155899).  

However, if an applying group changes their URL before being accepted/rejected, it disappears from the dashboard.  The group's application still exists as a pending application to the host, because once I found their new URL, I had the option to approve/deny from their account's page.

I only found the new url'd application because I searched for the name of the initiative in the general search and located it that way.

**Screenshots**
Dashboard where the application should appear (but doesn't after they changed the URL):
![image](https://user-images.githubusercontent.com/64920686/124682403-80ea8c80-de7f-11eb-8fd9-7d31633db6fd.png)

Their new URL page, with the option to accept/reject still available to the host:
![image](https://user-images.githubusercontent.com/64920686/124682449-9eb7f180-de7f-11eb-8d07-7b73d7c735f2.png)

**Comment by Betree** [comment] 2021-07-07 07:10
I tried to reproduce without luck. Here are the steps I followed:
- Create a collective with URL: `/abcde`
- Apply to host with this collective
- Confirms that the application is there on `/my-host/dashboard/pending-applications`
- Change collective slug to move URL from `/abcde` to `/fghij`
- Confirms that the application is still there on `/my-host/dashboard/pending-applications`

@kaylarep I may have misunderstood the issue, could you please tell me if the steps above are correct or propose others if they're not?

**Comment by kaylarep** [comment] 2021-07-07 22:29
hm ok, so maybe it's not just the URL change that causes this to happen. Did you also try changing the name of the collective @Betree ?

@alinamanko do you have any idea about other reasons that may cause this bug?

**Comment by kaylarep** [comment] 2021-07-07 22:33
@Betree yes that might be it...it's just happened again! [Here's ](https://opencollective.freshdesk.com/a/tickets/25889)the original application, and if you click their URL, it says 'not found', but then if I search it, it comes up (with a new name & new URL)

**Comment by Betree** [comment] 2021-07-09 09:31
Well if the collective changes its URL, it's normal that the old one (https://opencollective.com/communitykitchen) is not accessible anymore. We can eventually improve things in the future with #2283 but as of now, this is the expected behavior.

If you click on the "View application" button at the bottom of the email, you'll be redirected to the application in the host dashboard. This one isn't impacted by changes in names or slug so you'll always get fresh data from there.

**Comment by kaylarep** [comment] 2021-07-13 22:54
These types of applications disappear from the dashboard (when this occurs). 

The only way the application can be found is thru a manual search, but the header still exists to accept/reject.

The only reason I know to do a manual search is because we had a couple applications that disappeared from the dashboard, were 'not found' with their original URL, so I had assumed they deleted their application. But then their admin would email and ask why we hadn't replied, so I'd go to manually find the new named app, and see that it existed, with the option to accept/reject.

**Comment by kaylarep** [comment] 2021-07-14 21:21
@Betree here's another example of one:

- here's their application after changing the URL: https://opencollective.com/twisted-fields-research-collective (see the option to approve/reject from OCF)
- this application is not showing in [OCF's pending applications dashboard](https://opencollective.com/foundation/dashboard/pending-applications)

(do you have access to see this from OCF admin's point of view?)

**Comment by Betree** [comment] 2021-07-21 08:31
@kaylarep I haven't checked the page as I'm not an admin of OCF but looking at the code I'm pretty sure it's displayed, only not at the top of the page (it might even be on a separate one since we have pagination there). For legacy reasons, we currently sort applications by collective creation date, and this one was created a while ago.

**Comment by kaylarep** [comment] 2021-07-22 21:59
@Betree ah you're right! ok makes sense, I will keep a better eye out. Thanks!

**Comment by Betree** [comment] 2021-07-23 07:18
I've created a separate issue for sorting applications correctly: https://github.com/opencollective/opencollective/issues/4486

Closing this one since the rest is not a bug, and the proposal for redirects is already documented in https://github.com/opencollective/opencollective/issues/2283.

**Closed by Betree** 2021-07-23 07:18 UTC
Labels: need steps
