### ISSUE TITLE
Donation to buttercup failed 

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#557] opened 2017-10-24 17:45 UTC
Thank you for taking the time to report an issue 🙏

The easier it is for us to reproduce it, the faster we can solve it.
So please try to be as complete as possible when filing your issue.

***

URL: opencollective.com/buttercup/donate 
Logged in as: unsure. 
Error message if any: Cannot read property band of null
Expected result: make a donation
Browser:

Bonus point if you can add a screenshot :-)
<img width="1394" alt="pastedgraphic-1" src="https://user-images.githubusercontent.com/3671070/31959034-99e479ae-b8c1-11e7-8feb-54d3573c31ab.png">

Thank you and have a wonderful day/evening!
(and sorry for inconvenience! We'll do our best to solve this ASAP)

**Comment by piamancini** [comment] 2017-10-25 00:51
@xdamman this is the same issue Open Source facebook is hitting when trying to pay as an organization.  the organization id is 9337

**Comment by xdamman** [comment] 2017-10-25 02:36
Fixed and deployed. Duplicate of #558

**Closed by xdamman** 2017-10-25 02:36 UTC
Labels: high priority
