### ISSUE TITLE
Slug still guest after log in

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5051] opened 2021-12-16 23:32 UTC
I invited Steven as admin of an org. He accepted and logged in. I expected this would change his guest profile to a normal one.

![Screen Shot 2021-12-17 at 12 30 11 PM](https://user-images.githubusercontent.com/5498878/146464187-3004d94e-8271-43d9-987b-8d8a720a953e.png)

But when I then invited him to submit an expense. It was showing that they had a guest profile still"
![Screen Shot 2021-12-17 at 12 29 26 PM](https://user-images.githubusercontent.com/5498878/146464117-57f5838e-5d06-4d66-86e2-beb9d9758af9.png)

Shouldn't he have a full profile after logging in? A guest shouldn't be an admin of an org and be able to submit expenses.

**Comment by Betree** [comment] 2021-12-17 06:58
Duplicate of https://github.com/opencollective/opencollective/issues/4876. This situation is not ideal, but it's difficult to fix it without breaking some other parts (in particular, the link(s) that we send to update your recurring contributions). I proposed some specs to fix that in https://github.com/opencollective/opencollective/issues/4876#issuecomment-970110334

**Comment by Betree** [comment] 2022-01-10 14:58
Closing in favor of https://github.com/opencollective/opencollective/issues/4876

**Closed by Betree** 2022-01-10 14:58 UTC
Labels: enhancement, duplicate
