### ISSUE TITLE
OC displaying dollars instead of euros

### ISSUE THREAD

**Issue by jfdh** [opencollective/opencollective#1408] opened 2018-11-07 09:37 UTC
**Describe the bug**
OC interface displaying dollars instead of euros

**Screenshots**
![screenshot 2018-11-07 at 10 34 39](https://user-images.githubusercontent.com/30813303/48122945-0eadee00-e279-11e8-9671-106460aa9989.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome

**Comment by znarf** [comment] 2018-11-07 09:45
@jfdh can you link to the collective?

**Comment by xdamman** [comment] 2018-11-07 09:54
That's because all backers collective fall back by default to USD :-(
I fixed it in the database.

**Comment by znarf** [comment] 2018-11-07 09:56
@xdamman how can we fix the root cause? is there an open issue?

**Comment by jfdh** [comment] 2018-11-08 15:42
Thanks @xdamman

**Comment by znarf** [comment] 2019-06-13 12:36
@xdamman is that fixed?

**Comment by znarf** [comment] 2019-08-05 09:07
any update @xdamman?

**Comment by xdamman** [comment] 2019-08-05 15:00
Not fixed. Maybe it’s make a small bounty for this? Basically we could assume that the first transaction should set the currency of the user if none has been set. We should also allow people to change their default currency in their settings.

**Comment by piamancini** [comment] 2019-10-01 17:48
@Betree is this fixed with your latest deploy?

**Comment by Betree** [comment] 2019-10-01 19:01
The display for this one was already working:

![image](https://user-images.githubusercontent.com/1556356/65991599-e5e4a780-e48d-11e9-9597-5d167f979447.png)

I believe this issue is about contributors having `USD` as their default currency. We could fix it by letting users/orgs change their currency, or by applying the solution proposed by Xavier above:

> Basically we could assume that the first transaction should set the currency of the user if none has been set. 

However both solutions look bad to me. If I take my own profile as an example, I've made transactions in both `USD` and `EUR` so any number displayed there will be wrong. What we need is a field like `totalContributedByCurrency` which would return an object like:

```es6
{
    USD: 48623,
    EUR: 75369
}
```

Then we'll need to figure out a way of displaying all of them. For most collectives, this will return only one or two currencies max.

**Comment by piamancini** [comment] 2019-10-02 07:33
So we would have two separate amounts donated? The proper way would be to have the user set their currency (or pick it from their first transaction) and convert the different amounts on the fly to that transaction. 
So in your case, we would convert your USD donations to EUR and display EUR

**Comment by Betree** [comment] 2019-10-02 09:04
@piamancini That's a good option. I prefer allowing users to change their main currency because it's more flexible. But only users/orgs should be able to that, we don't want collectives to start messing up with that value.

So specs would be:
1. [ ] In `getTotalAmountSpent` (https://github.com/opencollective/opencollective-api/blob/6c894c16d1ec2975ef951c76ed4539ca33aea3b2/server/models/Collective.js#L1869) group amounts by currency so that SQL returns an object like:

```es6
{
    USD: 48623,
    EUR: 75369
}
```

2. [ ] Convert all the values that are not in collective currency (`this.currency`) to the collective currency so that the function will still return a number.

3. [ ] Add a select in `/{collective}/edit` to pick currency if collective is a `USER` or an `ORGANIZATION`

**Comment by piamancini** [comment] 2019-10-03 07:53
LGTM

**Closed** 2020-12-10 07:28 UTC
Labels: api, bug, frontend, support
