### ISSUE TITLE
Cannot edit event without loosing previously uploaded images and paragraphs moving around.

### ISSUE THREAD

**Issue by jdaviescoates** [opencollective/opencollective#6621] opened 2023-03-31 00:11 UTC
I just created this event:

https://opencollective.com/united-diversity-bridport/events/mmmm-monday-17-april-movie-finite-the-climage-of-change-meal-and-mingling-7f0d0b01

I note that I typoed the event name. Ever so slightly frustrating that the URL didn't get updated when I fixed the typo nor is the URL an editable field (e.g. like permalinks on WordPress). I should probably create another issue for that.

But what's really rather frustrating is that I am seemingly unable to edit my event description without loosing data and things randomly moving around.

As soon as I click on the edit button all the uploaded images disappear and a bunch of text moves to a completely different part of the page. All I wanted to do was to add another paragraph of text and another link, but it seems if I want to do that I'll have to do the whole description again :sob: 

See this video:

https://youtu.be/1HYkYBwecPU

**Comment by Betree** [comment] 2023-03-31 07:07
Extracted the feedback about letting admins edit the event's slug to https://github.com/opencollective/opencollective/issues/6622. Looking at the text editor issue.

**Comment by jdaviescoates** [comment] 2023-03-31 08:55
> Extracted the feedback about letting admins edit the event's slug to #6622. Looking at the text editor issue.

Great, many thanks @Betree

**Comment by Betree** [comment] 2023-04-04 15:55
@jdaviescoates This should now be fixed in production. Sorry for the inconvenience, and thank you for sharing all the details to easily reproduce the issue.

The root cause was a conflict between how we handle image and video attachments in these long descriptions. The bug would only appear when using both at the same time, which is why we never noticed it before.

**Closed by Betree** 2023-04-04 15:55 UTC
Labels: bug, frontend, important

**Comment by jdaviescoates** [comment] 2023-04-18 09:42
Thanks for fixing this so quickly (I've been meaning to say that for 2 weeks ;) )
