### ISSUE TITLE
Wrong currency showing for transaction

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2678] opened 2019-12-04 09:11 UTC
See https://opencollective.com/vincent-lefebvre

All this user's transactions were in Euro, but the total at the top and the refund are showing in USD.

Possibly the same as #1380

**Comment by znarf** [comment] 2019-12-09 09:50
I think we could display it in Euros by updating the user profile. That should work for that user.

But:
- not sure how `Collective.currency` is initialized when `type=USER`
- not sure how accurate `getTotalAmountSpent` when dealing with multiple currencies

**Comment by Betree** [comment] 2019-12-09 10:40
Duplicate of https://github.com/opencollective/opencollective/issues/1408

Proposed a solution in https://github.com/opencollective/opencollective/issues/1408#issuecomment-537404849

**Closed** 2019-12-16 14:14 UTC
Labels: api, bug, complexity → unknown
