### ISSUE TITLE
Unexpected error when login to transactions page from android

### ISSUE THREAD

**Issue by davojta** [opencollective/opencollective#1891] opened 2019-04-02 12:43 UTC
i see the page loading but after loading is completed i see the error page

URL: 
Logged in as (username or profile URL): dzianis.sheka@gmail.com
Error message if any:
Expected result: 
Browser: chrome opened from gmail

**Comment by Betree** [comment] 2019-04-02 13:31
Hi @davojta, thanks for opening this issue. Did that happen while you were trying to approve an expense from the email?

**Comment by davojta** [comment] 2019-04-02 15:50
i have an email with error about payment and want to verify that a new card
used

**Comment by Betree** [comment] 2019-04-02 19:26
Can you provide a screenshot and a URL?

**Comment by davojta** [comment] 2019-04-03 08:11
url - https://opencollective.com/shekadzianis/transactions

**Comment by davojta** [comment] 2019-04-03 08:14
https://www.dropbox.com/s/krcb6kuomf1sqm2/Screen%20Recording%202019-04-03%20at%2011.12.16%20AM.mov?dl=0 - video

**Comment by davojta** [comment] 2019-04-03 08:16
https://www.dropbox.com/s/9gqjuale6xe7d07/Screenshot%202019-04-03%2011.15.13.png?dl=0 - console output

If you need more info / debug - feel free to reach me in skype / telegram

**Comment by Betree** [comment] 2019-04-03 11:38
Thanks a lot @davojta, all these info are very helpful. 

It seems like a duplicate of #1872, but I'll keep it open to ensure we don't miss it.

**Comment by Betree** [comment] 2019-04-03 11:45
Edit: Looking back at it it's almost 100% sure that this is a duplicate of https://github.com/opencollective/opencollective/issues/1872. I've prioritized it so we'll get this fixed as soon as possible.

Sorry for the inconvenience and thanks again for sharing all the details!

**Closed by Betree** 2019-04-03 11:45 UTC
Labels: bug, frontend
