### ISSUE TITLE
Editing a team member creates multiple identical cards

### ISSUE THREAD

**Issue by kaylarep** [opencollective/opencollective#5394] opened 2022-04-06 00:17 UTC
Feedback from [a user](https://opencollective.slack.com/archives/C1974QBNK/p1649159581648089) :

> Editing a team member creates multiple identical cards

![group_62](https://user-images.githubusercontent.com/64920686/161871431-16402d10-4c16-4df4-b46d-7d39cd5be846.png)
:

**Comment by Betree** [comment] 2022-04-11 08:34
:gift: :money_with_wings: A **$200** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $200 when the Pull Request is reviewed, accepted and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by Betree** [comment] 2022-04-11 08:35
This issue can be really problematic, I'm adding a bounty on it.

At this point, we don't know yet if this is frontend or API but I would bet on a Frontend GraphQL cache issue.

**Comment by snitin315** [comment] 2022-04-26 07:46
Dropping it off. This related discussion might be helpful - https://github.com/opencollective/opencollective-api/pull/7412#discussion_r851003064

Up for grabs!

**Comment by leonardohofling** [comment] 2022-04-26 22:05
Hey @Betree!
I got how to reproduce the problem (https://www.loom.com/share/c22aa46f65f64b2e8dad6e8b286ac2a7)
Now, I'm thinking how to fix it... Should we clean this old records or adjust EditMember and CoreContributors to not consider this old data?

**Comment by Betree** [comment] 2022-04-27 06:02
@leonardohofling Ouch, great catch! We have an SQL query somewhere in our history to de-duplicate members, so don't bother with that part. Solving the root cause is enough to complete the bounty.

**Comment by leonardohofling** [comment] 2022-04-27 16:13
> @leonardohofling Ouch, great catch! We have an SQL query somewhere in our history to de-duplicate members, so don't bother with that part. Solving the root cause is enough to complete the bounty.

@Betree ,

I was looking for changes in this behavior and I found that in the past EditMembers was doing using this mutation:
![image](https://user-images.githubusercontent.com/294406/165563826-5406627a-feda-4614-8fe4-c886aae5b877.png)
That could create many duplicated data, and It was changed here: https://github.com/opencollective/opencollective-frontend/commit/ab5ff7aab5408c9a97230fc229bfa3cb59190c2a

Do you think we need to go deeper in this investigation?

**Comment by Betree** [comment] 2022-04-28 08:10
> > @leonardohofling Ouch, great catch! We have an SQL query somewhere in our history to de-duplicate members, so don't bother with that part. Solving the root cause is enough to complete the bounty.
> 
> @Betree ,
> 
> I was looking for changes in this behavior and I found that in the past EditMembers was doing using this mutation: ![image](https://user-images.githubusercontent.com/294406/165563826-5406627a-feda-4614-8fe4-c886aae5b877.png) That could create many duplicated data, and It was changed here: [opencollective/opencollective-frontend@ab5ff7a](https://github.com/opencollective/opencollective-frontend/commit/ab5ff7aab5408c9a97230fc229bfa3cb59190c2a)
> 
> Do you think we need to go deeper in this investigation?

It seems to me that the explanation you gave in https://github.com/opencollective/opencollective/issues/5394#issuecomment-1110295727 properly explains the issue. I don't think we need to investigate further, we just need a fix to make sure we only update your membership for the correct role (and not all of them).

**Comment by Betree** [comment] 2022-05-04 07:36
:trophy: This issue has been completed by @leonardohofling  

To claim the bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)

**Closed** 2022-05-04 07:35 UTC
Labels: bug, complexity → unknown, bounty, need steps, $200
