### ISSUE TITLE
Events host approval incorrect behavior

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2473] opened 2019-10-01 02:46 UTC
A Collective applied to join [CS&S](https://opencollective.com/css/) but was *not* approved. However, [an event](https://opencollective.com/collective/events/open-energy-data-hackdays-26090ev) created by that Collective is now showing up on the host's main page very prominently. 

I can't figure out what Collective the event is associated with (I'll raise another issue about that).

NO information related to unapproved Collectives should show up in any way associated with a host.

![Screen Shot 2019-10-01 at 3 41 53 PM](https://user-images.githubusercontent.com/5498878/65930527-8f15a880-e462-11e9-883a-9e2f43d3bb28.png)

**Comment by piamancini** [comment] 2019-10-01 09:25
@betree it looks like we need to remove events by pending collectives from showing in the host page. We filter out collectives but we probably missed filtering out events from those collectives.

**Comment by alanna** [comment] 2019-10-03 00:11
@Betree if you're not able to solve the underlying issue right away, can you just make sure that specific event isn't showing on that host's page for now? The user is waiting for a reply from support and isn't happy.

**Comment by Betree** [comment] 2019-10-03 06:35
@alanna I'll prioritize a fix for this issue today

**Comment by Betree** [comment] 2019-10-03 06:45
So the issue is not from the contributions section but in the way we create events. I've made a temporary fix in the database for the "Open Energy Data hackdays" event, I'll add more details on this issue after pushing a fix.

**Closed** 2019-10-03 11:17 UTC
Labels: api, bug, complexity → unknown, priority
