### ISSUE TITLE
/bin/sh: tput: not found

### ISSUE THREAD

**Issue by marcj** [opencollective/opencollective#1443] opened 2018-11-15 14:38 UTC
**Describe the bug**
I get an error in my npm logs, from a package using opencollective. Weirdly, I use also nestjs, which uses opencollective as well, but there isn't any error and it shows the opencollective stuff.

![screen shot 2018-11-15 at 15 39 03](https://user-images.githubusercontent.com/450980/48559798-9dabad80-e8ec-11e8-8be9-b9aa0b9068b6.png)

**To Reproduce**
```
docker run -ti alpine:3.8
apk add  nodejs-npm
npm install @compodoc/compodoc
```

**Expected behavior**
No error shown

**Actual behavior**
Error shown:

```
> @compodoc/compodoc@1.1.6 postinstall /node_modules/@compodoc/compodoc
> opencollective postinstall

/bin/sh: tput: not found

/bin/sh: tput: not found
(node:24) UnhandledPromiseRejectionWarning: Error: Command failed: tput cols
/bin/sh: tput: not found

    at checkExecSyncError (child_process.js:601:13)
    at execSync (child_process.js:641:13)
    at print (/node_modules/opencollective/dist/lib/print.js:48:95)
    at printFooter (/node_modules/opencollective/dist/lib/print.js:88:3)
    at /node_modules/opencollective/dist/commands/postinstall-rich.js:35:28
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:24) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

![screen shot 2018-11-15 at 15 37 57](https://user-images.githubusercontent.com/450980/48559723-71902c80-e8ec-11e8-9979-3cc78aab8225.png)

**Desktop (please complete the following information):**
 - OS: Alpine 3.8

**Additional context**

I was just seeing that error after upgrading some packages (including compodoc), so I'm not the maintainer of that package, just a regular user that happens to use that package.

**Comment by znarf** [comment] 2018-11-19 12:40
@xdamman Can you tell us more about this issue? I think you worked on that in the past?

**Comment by xdamman** [comment] 2018-11-20 02:18
Looks like they are using a community version of the `postinstall` created and maintained by the community, not us:
https://github.com/nestjs/nest/blob/master/package.json#L49

This issue should be reported to https://github.com/nuxt-community/opencollective

**Comment by znarf** [comment] 2018-11-20 07:33
@xdamman Good catch!

@marcj Can you report the issue there? https://github.com/nuxt-community/opencollective

Closing.

**Closed by znarf** 2018-11-20 07:33 UTC
Labels: bug

**Comment by smashnet** [comment] 2019-04-12 09:43
The problem is, that the alpine docker image has no "tput"command. That comes with the ncurses package. You'd have to install ncurses in the Dockerfile `RUN apk add ncurses` to make this work.
