### ISSUE TITLE
Updates broken for user: "unexpected error"

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2059] opened 2019-05-23 01:48 UTC
**Describe the bug**

- go to the updates
- click on “Create an Update”
- taken to the updates page in a broken state, screenshot below.
- Looks like a library for doing Markdown Editing is broken

**Screenshots**

![Screen Shot 2019-05-23 at 1 47 34 PM](https://user-images.githubusercontent.com/5498878/58220049-5dc4f780-7d61-11e9-94d9-f358566e683e.png)

**Additional context**
https://opencollective.freshdesk.com/a/tickets/388

**Comment by znarf** [comment] 2019-05-23 06:32
@alanna With the steps provided, I can't reproduce this issue.

It's missing the collective, the environment (browser, os). The screenshot is unreadable. There is no more additional context in the linked support ticket.

**Comment by alanna** [comment] 2019-05-23 06:36
Just ask the user for the info you need. It's inefficient for you to
explain to partially explain to me and then I partially explain to them and
we'll play telephone.

**Comment by znarf** [comment] 2019-05-23 06:47
@alanna Ok, then closing this issue as invalid and handling that on support side.

**Closed by znarf** 2019-05-23 06:47 UTC
