### ISSUE TITLE
Unable to pay expense from host budget

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3307] opened 2020-07-03 00:12 UTC
I attempted to pay the [first expense for OCNZ](https://opencollective.com/ocnz/expenses/18630), which is participating in the host budget alpha test, so its budget is directly in the host. But I get an error saying I can't pay expenses without a host. This budget *is* the host.

![Screen Shot 2020-07-03 at 12 10 21 PM](https://user-images.githubusercontent.com/5498878/86419082-545cdb80-bd26-11ea-9a57-36bc004fbc1d.png)

**Comment by Betree** [comment] 2020-07-03 07:52
Same root cause as opencollective/opencollective#3302, will be fixed by https://github.com/opencollective/opencollective-frontend/pull/4573

**Comment by znarf** [comment] 2020-07-28 13:45
@Betree @alanna  can we close this?

**Closed** 2020-07-28 14:13 UTC
Labels: bug
