### ISSUE TITLE
CSS alignment bug

### ISSUE THREAD

**Issue by ghuntley** [opencollective/opencollective#2379] opened 2019-08-28 23:39 UTC
**To Reproduce**

https://opencollective.com/reactiveui

**Screenshots**

![image](https://user-images.githubusercontent.com/127353/63899609-d57d7f00-ca40-11e9-9ffc-324ab888aacd.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser firefox quantium
 - Version latest

**Comment by znarf** [comment] 2019-10-02 09:14
@ghuntley Closing because we now released the updated collective page and I can't reproduce anymore. Feel free to reopen and update if this is also happening on the new page or elsewhere.

**Closed by znarf** 2019-10-02 09:14 UTC
