### ISSUE TITLE
paypal payment fails , offers horrific UI output

### ISSUE THREAD

**Issue by mixmix** [opencollective/opencollective#2639] opened 2019-11-15 01:30 UTC
I approved a payment via email ... then wondered if it was paid ... so clicked though to see the expense. No it hadn't, so I click "pay with paypal".

There's now a clear "the button as been clicked" thing, which is a response to a past issue I think. But then I see this : 

![image](https://user-images.githubusercontent.com/2665886/68909755-461c7800-07b4-11ea-9e73-f114e514a7c6.png)

This is pretty discouraging? Is the server on fire, do I trust this (this is my response as a user). I have no idea what went wrong. I'm gonna hand this over to the Admin of this collective ... but what would I do if that wasn't the case ? _shudder_

**Comment by mixmix** [comment] 2019-11-15 01:32
here's the expense I was trying to pay https://opencollective.com/scuttlebutt-maintenance/expenses/11565

The screenshot was me trying to approve it from https://opencollective.com/scuttlebutt-maintenance/expenses

Same error in both places though. This is 2/2 of the the last expenses I've tried to pay from this collective failing in a way I have no control / no idea what happened

**Comment by znarf** [comment] 2019-11-15 08:17
@mixmix thank you for the report. Without talking about the root cause (the PayPal error), that behavior is effectively not acceptable, the error should be properly digested and made clear to the user.

**Comment by alanna** [comment] 2019-11-17 20:41
Tried again to pay this expense. Still getting the same error:

> "The transaction cannot complete successfully. Advise the customer to use an alternative payment method"

There's enough balance in the pre-approval key so I don't think that's the issue.

**Comment by gmarcos87** [comment] 2019-11-22 14:33
Hello everyone, I was looking at the origin of the message and is the default message that is sent from opencollective-api in case of error.
Regardless of the paypal error, which message should be shown to the user? And what should be done with the error message returned by paypal in the backend?
I can try to solve this issue but you should know what is expected.

**Comment by znarf** [comment] 2019-11-25 07:52
@gmarcos87 This effectively happening in https://github.com/opencollective/opencollective-api/blob/master/server/lib/transactions.js#L91. Maybe can we throw an error earlier, for example just after we get the error message from PayPal. https://github.com/opencollective/opencollective-api/blob/master/server/graphql/v1/mutations/expenses.js#L242 

The message could be `Error while paying the expense with PayPal: "${PAYPAL_ERROR_MESSSAGE}"`. `PAYPAL_ERROR_MESSSAGE` should then be extracted from the `paymentResponse`, in this case "The transaction cannot complete successfully. Advise the customer to use an alternative payment method."

Full message would be: `Error while paying the expense with PayPal: "The transaction cannot complete successfully. Advise the customer to use an alternative payment method."`

It's a bit verbose but better than what we have today.

**Comment by alanna** [comment] 2019-11-25 22:54
> Error while paying the expense with PayPal: "The transaction cannot complete successfully. Advise the customer to use an alternative payment method."

This isn't really a fix because it tells the host admin nothing useful. We only offer payment through our API in the dashboard - what is the admin meant to do with this? They can't use an alternative method.

**Comment by gmarcos87** [comment] 2019-11-26 08:03
@alanna  In case there is a problem with the paypal account the one that should solve it is opencollective and not the user, am I right? If so, the frontend should notify that momentarily the transaction cannot be carried out and trigger some alert for the administrators/developers.

**Comment by gmarcos87** [comment] 2019-11-28 12:35
I opened the pull-request for this issue. I think it is necessary to reach a consensus on which error messages to display and what options are available to the user in case something goes wrong. Between a horrible message and a useless message, the difference is mainly aesthetic.

**Comment by znarf** [comment] 2019-11-28 14:24
To be actionable, we think the message should add `Please contact support@opencollective.com.`. This is the only useful thing we can tell the user.

We don't have better yet as we have not fully understood it. It's now gone and no one else has reported it so far.

**Comment by znarf** [comment] 2019-12-10 13:58
Closing the issue as it was not reported by anyone else and could not be reproduced.

If someone face it in the future, they will have a better error message and will be asked to contact support.

**Comment by znarf** [comment] 2019-12-10 13:59
Thank you @mixmix for the report and @gmarcos87 for the fix!

**Closed by znarf** 2019-12-10 13:58 UTC
Labels: api, bug, complexity → simple, frontend, priority

**Comment by mixmix** [comment] 2019-12-13 07:47
you're welcome. Super glad there's a nice thing there for the next person.
You're doing great work !
