### ISSUE TITLE
Filter expense status by draft

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#6607] opened 2023-03-27 20:08 UTC
This filter should include all the expense statuses, including draft, but it's not there.

<img width="250" alt="Screen Shot 2023-03-28 at 9 07 11 AM" src="https://user-images.githubusercontent.com/5498878/228054605-13ee2515-dde7-420c-85eb-46247761672c.png">

**Comment by Betree** [comment] 2023-03-28 06:33
Duplicate of https://github.com/opencollective/opencollective/issues/6224

**Closed by Betree** 2023-03-28 06:33 UTC
Labels: duplicate
