### ISSUE TITLE
Events Flexible Contribution Tier

### ISSUE THREAD

**Issue by shannondwray** [opencollective/opencollective#6219] opened 2022-12-07 07:05 UTC
**Describe the bug**
When checking the check box to turn on the flexible contribution tier the save button doesn't become active. This is quite confusing and I'm not sure whether I have enabled this or not

**To Reproduce**
1. Go to an event
2. Click on create contribution tier
3. Click on Enable flexible contributions

**Expected behavior**
I would expect to be able to click the save button and then see my changes on the event

**Desktop (please complete the following information):**
 - OS: Ventura 13.1 Beta
 - Browser: Brave
 - Version: [Version 1.45.131 Chromium: 107.0.5304.110 (Official Build) (x86_64)](https://brave.com/latest/)

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by Betree** [comment] 2022-12-07 15:24
Duplicate of https://github.com/opencollective/opencollective/issues/3263.

Long story short: everything's working normally, but the UI is confusing because the checkbox is auto-saved when clicked; you don't need to click on the Save button (which is there for the tiers themselves).

The new edit tiers page (#3438) shouldn't be impacted by this since there's no save button.

**Closed by Betree** 2022-12-07 15:24 UTC
Labels: duplicate
