### ISSUE TITLE
Date of fiscal host application showing as "invalid"

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2086] opened 2019-06-03 22:48 UTC
**Describe the bug**
Info message for pending Collective is showing "invalid date"

**To Reproduce**
1. Apply as a Collective to fiscal host
2. While application is pending, go back to edit Collective > fiscal host
3. See info message including "invalid date"

**Expected behavior**
It should show the date the Collective applied for hosting

**Screenshots**
![BLSeEChTIdUdM3kV6lYJpSMZrb7TyvwhtQ](https://user-images.githubusercontent.com/5498878/58839548-50d7ca80-86b6-11e9-868a-856c69bdb3f0.png)

**Comment by znarf** [comment] 2019-06-04 06:28
Duplicate with https://github.com/opencollective/opencollective/issues/1652

**Comment by flickz** [comment] 2019-06-05 09:42
This is a bit tricky as it is not reproducible locally from my side.

![Screenshot from 2019-06-05 10-34-30](https://user-images.githubusercontent.com/15707013/58946451-cc507f00-877d-11e9-808a-db711aaff7d1.png)

**Comment by znarf** [comment] 2019-06-05 10:08
@flickz where are we fetching this date from?

**Comment by flickz** [comment] 2019-06-05 10:15
`collective.members` with `HOST` role. ---> `collective.member.createdAt`
https://github.com/opencollective/opencollective-frontend/blob/master/src/components/EditHost.js#L81

**Comment by znarf** [comment] 2019-06-11 09:57
@flickz Can you try again with the application being accepted? Same?

**Comment by znarf** [comment] 2019-06-11 10:19
@alanna I'm not able to reproduce.

- Were the steps confirmed by you? Are you sure that was the path taken?
- Can you share wider screenshots?

**Comment by alanna** [comment] 2019-06-14 02:09
@znarf the original message said:

> I recently joined opencollective to support the development of my open source project. When I go to the Edit Collective page I can see that it says that I've applied on an "Invalid Date" and my application is being reviewed.

I have manually approved this Collective already, so that user will no longer be able to see this message. I tried reproducing it with a test Collective but was not able.

**Comment by znarf** [comment] 2020-07-29 23:11
Seems there is no new occurrence, closing.

**Closed by znarf** 2020-07-29 23:11 UTC
Labels: bug, complexity → simple, frontend
