### ISSUE TITLE
Formatting bug in expense - Firefox on Android

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5555] opened 2022-05-13 21:44 UTC
![Screenshot_20220514-094216.png](https://user-images.githubusercontent.com/5498878/168393421-01a8f923-466c-4008-8bcb-88e8e6e1af66.png)

**Comment by Betree** [comment] 2022-05-16 06:27
Duplicate of https://github.com/opencollective/opencollective/issues/4099

**Closed by Betree** 2022-05-16 06:27 UTC
Labels: bug, duplicate
