### ISSUE TITLE
Expense losing $0.02 after submitting

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3365] opened 2020-07-26 07:41 UTC
I've seen this multiple times but it's only happening sporadically. I submit an expense for $x, but after clicking through, the summary shows $x-0.02 (two cents). I submitted one for $1250 and the summary showed $1249.98. I went back and edited it and it was fine, but something strange is going on there.

**Comment by Betree** [comment] 2020-07-27 10:11
We got a support ticket that can be related to that a few weeks ago: https://opencollective.freshdesk.com/a/tickets/7897

My assumption was that it could be related to inadvertently scrolling into the amount input (see the screencast below) but I've since blocked this behavior to make sure it doesn't happen.

To help investigate, could you share:
- The number of items and their individual amounts
- Your locale (I assume it's EN_NZ)
- Browser
- OS

Also if you can try scrolling into the amount input to see if it changes, that'd be helpful.

Thanks!

---

![Peek 08-07-2020 09-21](https://user-images.githubusercontent.com/1556356/88529080-c6f86880-cfff-11ea-84b8-c9146319c354.gif)

**Comment by alanna** [comment] 2020-07-27 22:17
- The number of items and their individual amounts: it was one item on
   the expense (invoice) and the intended amount was $1250
   - Your locale (I assume it's EN_NZ): yes EN_NZ
   - Browser: Chrome
   - OS: MacOS

**Comment by Betree** [comment] 2020-07-29 08:04
I tried to reproduce with different scenarios but wasn't able to. I also looked at the code that handles the amounts and found nothing in there that could explain this bug. While I don't exclude that there may be a problem in the code, it's hard to investigate further without more precise steps.

Another track that I want to follow is the possibility of an UX issue, similar to the scroll behavior described [above](https://github.com/opencollective/opencollective/issues/3365#issuecomment-664259034). On Chrome, if the amount input has the focus, you can increase/decrease its value using the arrow keys on your keyboard. @alanna do you think that's something you may have done?

![Peek 29-07-2020 09-56](https://user-images.githubusercontent.com/1556356/88773484-73faee80-d182-11ea-8d68-8c2b6873e00a.gif)

**Comment by alanna** [comment] 2020-07-30 03:42
I knew this would be painful as I was writing the issue... sorry. I will
keep my eye out to see if it happens again. I haven't seen any complaints
from users yet so we can deprioritize this until it comes up again.

**Comment by Betree** [comment] 2020-08-19 12:33
I just realized that the fix I implemented for the scroll was not working on Chrome for some operating system. I just changed my OS and was able to reproduce the scroll behavior that I was previously changed. Given what I already researched, I'm pretty sure that this is the root cause for this issue. Below is a screenshot of how it happens, it's almost unnoticeable for users (because scrolling usually takes the input out of the view). 

https://github.com/opencollective/opencollective-frontend/pull/4872 will close this issue by implementing a more comprehensive solution that works on Chrome. Feel free to re-open if it happens again in the future.

![Peek 2020-08-19 14-27](https://user-images.githubusercontent.com/1556356/90634600-3bea4700-e228-11ea-84f9-88208e29eace.gif)

**Closed** 2020-08-19 12:58 UTC
Labels: bug, complexity → unknown, frontend
