### ISSUE TITLE
Slash in URL Slug causes problems

### ISSUE THREAD

**Issue by edent** [opencollective/opencollective#2077] opened 2019-05-30 09:34 UTC
**Describe the bug**
I wanted to create the slug `edent/supertinyicons` - that works.

When I view it, It displays as `edent%2Fsupertinyicons` - that also works.

When I try to edit it, it breaks, and goes to 
`https://opencollective.com/edent/supertinyicons/edit`

I have to manually edit the URL to 
`https://opencollective.com/edent%2fsupertinyicons/edit` in order to be able to edit the repo.

**To Reproduce**
1. Go to `https://opencollective.com/edent%2Fsupertinyicons?`
2. Click on "Edit collective"
3. See error

**Expected behavior**

**Screenshots**
![Screenshot at 2019-05-30 10-27-56](https://user-images.githubusercontent.com/837136/58623535-1a6d0a80-82c6-11e9-8d1d-272917c9eb18.png)
![Screenshot at 2019-05-30 10-27-39](https://user-images.githubusercontent.com/837136/58623536-1a6d0a80-82c6-11e9-8a4d-fb6f3c88b1ac.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Firefox
 - Version 67

**Additional context**

**Comment by znarf** [comment] 2019-05-30 11:24
Thank you for reporting this. We should have been more strict in slug validation and should not have allowed to have a slash in it. I suggest to change your slug.

On our side, we will check the validation to avoid that in the future.

**Comment by edent** [comment] 2019-05-30 13:04
Will do! Cheers :-)

**Comment by Betree** [comment] 2019-06-03 11:13
This is a duplicate of https://github.com/opencollective/opencollective/issues/1476, though you've added way more details and helpful context. Thank you for that @edent, I'm closing https://github.com/opencollective/opencollective/issues/1476 in favor of yours.

Also let's keep in mind that this is not only about `/` character, we need to ensure slug is always alphanum + dash only. An entry in `validate` for the slug of the `Collective` model is probably the way to move forward with it.

While doing the change, we have to take a decision about what to do with UTF8 characters for slug: two users have special slugs. Do we want to migrate them, or do we want to support it?
- `晃羽田`
- `иванк`

<details>

The query:

```sql
SELECT slug FROM "Collectives"
WHERE slug NOT SIMILAR TO '%[a-zA-Z0-9]%'
```

</details>

**Comment by edent** [comment] 2019-06-03 11:16
The majority of the world are more diverse than ASCII 😊

I'd certainly vote to keep UTF-8 - but escape any URL special characters.

**Closed** 2019-06-27 05:56 UTC
Labels: api, bug, complexity → simple, priority
