### ISSUE TITLE
Double check monthly numbers

### ISSUE THREAD

**Issue by xdamman** [opencollective/opencollective#1418] opened 2018-11-08 14:18 UTC
From Pia's email:

>How can we still grow the 3 month average but we so down in total donations. 
> 
> The big dip is in `totalMoneyBroughtIntoPlatformInUSD` which is added funds, almost 100k lower. 
> 
> - Donations ($)
>  - Total donations: $147,398 (-13%)
>    - 3-month Avg total donations: $166,682 (+3% m/m) 
>    - 3-month Recurring donations:$103,953 (+6% m/m)
> - Num of donations
>   - \# of total donations: 4,117(+3% m/m) 
>   - \# of recurring donations: 3,681 (+5% m/m)
> - Other
>   - Avg recurring donation: $29.16 (+1%)  
>   - OC Revenue: $7,411 (-13% m/m)
> - Collectives
>   - Active collective: 493 (+2.9% m/m) 
>   - Active hosts: 54 (+8%)
> - Of the top 30 collectives by donations:
>   - 12  collectives increased budget m/m
>   - 16 decreased m/m 
>   - 1 stayed the same m/m
>   - 1 inactive (raised $0)
> - Sponsors
>   - Of the top 30 Sponsors by donation
>     - 1 increased their contributions
>     - 3 decreased 
>     - 19 remained the same
>     - 7 are inactive
>  - New Sponsors created: 97 ( +86%) from which 46 contributed +$100

**Comment by xdamman** [comment] 2018-11-09 03:03
`totalMoneyBroughtIntoPlatformInUSD` is not "added funds", it's the total amount brought into the platform, that means not only added funds but also all donations.

I've updated the query with latest fx rates: 
https://github.com/opencollective/opencollective/wiki/Queries#revenue-and-transaction-splits-by-month-with-all-currencies-converted-to-usd

And I'm posting those stats publicly in this spreadsheet: 
https://docs.google.com/spreadsheets/d/1XG1VGYodr5xxrZWdfr5q5gf3EhN4zpU_7Oa6Z5XI288/edit?usp=sharing

Would be good to keep that one as the source of truth when you run the query every month.

**Comment by xdamman** [comment] 2018-11-09 04:40
The big drop in added funds come from the fact that in September, [Open Collective Paris](https://opencollective.com/paris) manually added €85k from [Handshake](https://opencollective.com/handshake) to [Access](https://opencollective.com/access)
![](https://d.pr/free/i/HKEle7+)
and [BrusselsTogether](https://opencollective.com/brusselstogether) manually added €14,855.30 to [CodeNPlay](https://opencollective.com/codenplay).
![](https://d.pr/free/i/Y7XjZc+)
So that's €100k or ~$113k.

**Comment by piamancini** [comment] 2018-11-09 18:38
@xdamman the query is off now. Did you add a column? It's not matching the columns I have on the spreadsheet?

**Comment by piamancini** [comment] 2018-11-09 18:39
Any chance you can revert? the process data will be broken everywhere else.

**Comment by xdamman** [comment] 2018-11-09 18:42
Oh yes I just moved the added fund column next to the “donations on platform” because it makes much more sense there. Take a look at the public spreadsheet that I shared. And I’ve reflected that change in the query to make it easier for you to update that public spreadsheet which should be the source of truth.

What do you mean by “the process data will be broken everywhere else”? Where is “everywhere else”?

**Comment by piamancini** [comment] 2018-11-09 18:45
the spreadsheet uses those columns to process the data and calculate the 3 month averages, charts etc. 
Moving those columns affects the process data pages and I need to update them. 
Please see the OC Monthly Analysis file I shared on the email.

**Comment by piamancini** [comment] 2018-11-09 18:45
The problem is not so much the public spreadsheet is the one I use for revenue calcs

**Comment by xdamman** [comment] 2018-11-09 18:48
Ah ok gotcha. Can you send me that file and I’ll update that process. 
In the meantime you can just look at the history of the wiki to get to the previous version of the query and it should work (or you can also simply cut and paste the part of the query towards the end that is showing that column). Otherwise happy to do all this for you tomorrow (it’s very late here)

**Comment by piamancini** [comment] 2018-11-09 18:51
ok. Tomorrow is fine. 
regarding my original question, what dropped by 13% while all other numbers are up is not hte total money brought into the platfrom, but the donations. 
Here's the link if you want to play with it. https://www.dropbox.com/preview/OpenCollective/Data/monthly%20analysis/OC%20Monthly%20Analysis.xlsx?role=personal

**Comment by znarf** [comment] 2019-06-13 12:39
@xdamman can we close this?

**Comment by piamancini** [comment] 2019-06-14 10:26
yes.

**Closed** 2019-06-14 10:26 UTC
Labels: project
