### ISSUE TITLE
backers charged twice in a row if they set up contribution close to end of month

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#1215] opened 2018-08-07 14:49 UTC
we now charge people on the 1st of the month, regardless of when they made the donation. This results in people getting charge twice in the same month and it's particularly annoying when the get charged two days in a row... 

We should push the second charge to the 1st of the second month when donations are made after the 15th of the month. 

if 1st charge is between 1 - 15th of month x then second charge is 1st of x+1
if first charge is between 16-31st then second charge is 1st of x+2

This was a problem when we were using stripe to run subscriptions but should be doable now that we charge them ourselves.

**Comment by xdamman** [comment] 2018-08-07 14:55
the real proper way to do this is to charge pro rata for the first payment. 
E.g. If payment made the 10th of the month, the user should pay 2/3 for the 20 remaining days in the month. Likewise, if the subscriptions starts on the 20th, first payment should be 1/3 of the full amount.

**Comment by piamancini** [comment] 2018-08-07 15:04
That is indeed a better way. 
If too complicated, at least a first step to push txns should help as a v1. Hosts lose money every time we refund because stripe is not giving the fees back. We should try and avoid refunds as much as possible.

**Comment by xdamman** [comment] 2018-08-07 15:21
@marcogbarcellos assigning this to you. See what's easiest for you to implement.

**Comment by marcogbarcellos** [comment] 2018-08-08 14:32
One question about it: Why does it need to always be on the first of the month? Example: I as User prefer to pay after the 15th of each month because of a personal preference(let's my salary is only on the 15th and I feel more comfortable or whatever else).

**Comment by piamancini** [comment] 2018-08-09 16:10
@marcogbarcellos 

This is what we have in FAQ: 

> Why do you charge recurring monthly subscriptions on 1st of every month?
> It helps our collectives manage their monthly budget. Instead of getting donations randomly throughout the month, they can start with a minimum budget for that month. Any new donations improve the budget.
> We're working on a way to charge a single payment spread out across monthly contributions, to reduce payment processor transaction fees.

the idea is also to be able to batch payments in the future. If we charge all your transactions in one go then stripe fees are less (right now stripe fees are 2.9% + 0.30c) in a large txn is doesn't matter in a $2 donation is a large % of the donation.

**Comment by piamancini** [comment] 2018-11-08 19:47
This is still something we should do

**Comment by alannallama** [comment] 2019-02-04 21:44
We've recently had a support thread caused by this issue, resulting in the user wanting dozens of transactions refunded because they were charged twice too close together. 

At the very least, we should add help text that makes it super clear when they will be charged when they are setting up a contribution. Right now it says it will charge on the 1st of the month, but it does not also say it will be charged today in addition.

As an alternative to pushing the payment back to the second month, we could just hold off charging them the first time until the 1st of the month. Or, we could give them an option of charging today and the 1st or just on the 1st.

**Comment by alannallama** [comment] 2019-02-06 03:18
@znarf the problem is while it's clear they will be charged on the 1st of the month, it's not clear they will *also* be charged today. I suggest changing the text, and also not hiding it behind the expandable FAQ thing but always displaying it.

> When will I be billed?

> You will be charged once today, and again at the beginning of your chosen subscription period (1st of the month for monthly subscriptions, 1st of January for yearly). You may be charged twice in a short time frame if you are setting up a subscription close to the end of a billing cycle.

The "next contribution" section is confusing it further, because it looks like they will only be charged on that date. I suggest adding to it so it says:

> First charge: today
> Next charge: Mar 1, 2019

**Comment by znarf** [comment] 2019-02-06 08:44
@alannallama sounds good

**Comment by znarf** [comment] 2019-02-11 10:54
@alannallama The proposed FAQ is not properly describing current behavior for yearly subscriptions. Let me propose another version. Feel free to phrase it better!

`You will be charged for the first time today. For monthly subscriptions, you will then be charged the 1st of next month, then the 1st of each month. For yearly subscriptions, you will then be charged the 1st of same month next year, then the 1st of same month each year. Warning: you may be charged twice in a short time frame if you are setting up a monthly subscription close to the end of the month.`

**Comment by alannallama** [comment] 2019-02-12 01:06
@znarf OK that make sense. Here is a polished version:

> You will be charged today, and then on the 1st of each month (for monthly subscriptions) or the 1st of the same month next year (for yearly subscriptions). Warning: you may be charged twice in a short time frame if you are setting up a monthly subscription close to the end of the month.

**Comment by alannallama** [comment] 2019-03-05 22:43
The flow is still showing misleading information. In this screenshot, it implies the first charge will be the first of next month, but actually the first charge is today, right?

<img width="888" alt="screen shot 2019-03-06 at 11 29 38 am" src="https://user-images.githubusercontent.com/5498878/53842594-d0e18c00-4004-11e9-8b9e-3a54da2a81f4.png">

This other view of the flow is much clearer. Why are these different?

<img width="892" alt="screen shot 2019-03-06 at 11 42 50 am" src="https://user-images.githubusercontent.com/5498878/53842662-02f2ee00-4005-11e9-9404-50332d349ea6.png">

**Comment by Betree** [comment] 2019-03-06 07:29
@alannallama We've decided to skip the step "Contribution Details" if the amount / interval cannot be edited. I agree that screenshot n.1 is not clear on the fact that first payment is today.

So on the first screenshot, instead of:

```
You'll contribute with the amount of $2.00 monthly
Your next charge will be on: Apr 1, 2019
```

We should display:

```
You'll contribute with the amount of $2.00 monthly
First charge: Today
Next charge: Apr 1, 2019
```

Right?

**Comment by alannallama** [comment] 2019-03-06 09:22
Yes that would be good @Betree

**Comment by alannallama** [comment] 2019-03-14 00:14
More user feedback about this issue today: the user wanted to change an existing subscription amount, but the only option was to cancel and set up a new one, so he did that, but then realised if he restarted it he would be charged twice this month since he already paid once under his original subscription. So he's having to manually track the dates and go back to set up the new one on April 1. 

@Betree will the improvements underway help users in this situation? Is there any way to change the amount without cancelling and restarting again, or a way to keep the original timeline in the new subscription?

**Comment by znarf** [comment] 2019-03-14 07:55
@alannallama What prevented him to update the subscription? How could he cancel without seeing  the update?

![Screen Shot 2019-03-14 at 08 54 53](https://user-images.githubusercontent.com/806/54340082-dd826780-4636-11e9-902c-e56cd9ca864b.png)

**Comment by Betree** [comment] 2019-03-17 23:13
@alannallama Sounds like another issue, this => `the user wanted to change an existing subscription amount, but the only option was to cancel and set up a new one` is not normal.

I've delivered the clarifications on intervals in https://github.com/opencollective/opencollective-frontend/pull/1507. It has screenshots if you want to see how it looks.

**Comment by alannallama** [comment] 2019-03-18 02:21
Verified this latest thing is a seperate issue #1817

**Comment by alanna** [comment] 2019-07-04 01:42
Every 1st of the month we are getting support requests from people who started new recurring contributions in the proceeding few days and are angry about being "double charged". This is despite improve the help text explaining this on the contribution screen.

I believe we should change how our recurring charges work, so that you are charged when you set it up, and then on that day of each month going forward. 

The justification that's been given previously is Collectives need the charges to happen all at the same time so they can know their recurring budget, but surely it would be easier just to give them that information somehow, rather than confusing users with this unexpected double charge? (#1585)

**Comment by alanna** [comment] 2019-07-04 01:44
Pretty much every month we have a user threatening to do a chargeback on their credit card. Who knows how many are just doing that without even contacting us? That's pretty bad for us.

**Comment by Betree** [comment] 2019-07-04 10:00
> I believe we should change how our recurring charges work, so that you are charged when you set it up, and then on that day of each month going forward.

I agree with that. I was personally surprised by the current behaviour when I first discovered Open Collective and this :arrow_up: is what I would have expected.

---

One assumption that I have is that some users may actually be discouraged to contribute because of this issue. I've collected some data to challenge this assumption.

There seems to be a pattern where we have less subscriptions created in the last 5/10 days. These data **doesn't prove** that users are not coming back later to create their subscription at the beginning of the month.

<details>

<summary>See raw data and query</summary>

```sql
SELECT
	extract(DAY from "createdAt")::int AS created_on_day,
	COUNT(*)
FROM
	"Subscriptions"
WHERE
	"isActive" = TRUE
	AND "createdAt" > '2018-01-01'
GROUP BY
	created_on_day
ORDER BY
	created_on_day
```

| created_on_day | count | 
|----------------|-------| 
| 1              | 253   | 
| 2              | 242   | 
| 3              | 169   | 
| 4              | 185   | 
| 5              | 123   | 
| 6              | 140   | 
| 7              | 169   | 
| 8              | 206   | 
| 9              | 151   | 
| 10             | 207   | 
| 11             | 134   | 
| 12             | 133   | 
| 13             | 140   | 
| 14             | 149   | 
| 15             | 158   | 
| 16             | 161   | 
| 17             | 172   | 
| 18             | 145   | 
| 19             | 165   | 
| 20             | 158   | 
| 21             | 154   | 
| 22             | 129   | 
| 23             | 129   | 
| 24             | 134   | 
| 25             | 139   | 
| 26             | 175   | 
| 27             | 162   | 
| 28             | 139   | 
| 29             | 125   | 
| 30             | 106   | 
| 31             | 108   | 


</details>

> Number of subscriptions created (Y) / Day of the month (X) since 2018-01-01

![Filename](https://user-images.githubusercontent.com/1556356/60657651-f5822f00-9e51-11e9-98ee-daabc21e8fef.png)

**Comment by Betree** [comment] 2019-07-04 10:07
Also from the previous data:

| Days of the week | Average | 
|----------------|-------| 
| 1 -> 7              | 118.4285714285714286   | 
| 8 -> 15              | 99.8750000000000000   | 
| 16 -> 23             | 86.1250000000000000   | 
| 24 -> 31              | 83.5000000000000000   | 

Note that last week's numbers can partially be explained by the fact that some months have less days for the last week.

**Comment by piamancini** [comment] 2019-07-04 10:25
I agree we need to change this behavior as is. The  current justification is weak and the issues it brings are several. 

The real justification for doing was having the ability to batch payments. If we bundle all payments on one day of the month we can make on charge a month for all subscriptions. The benefit of this is improving fees in small donations and also having one invoice / one charge per month. 

Our data shows that we are receiving an average recurring donations of ~$30 which seems quite high. We should run a query to see how many donations we have <$10 and the impact they have on the funds raised. 

If we are not going to focus on  optimizing small donations (and I think we shouldn't because of new actors in the ecosystem doing this - at least for the OS vertical) then there's no reason to batch. 

If we decide that we still want to batch, then I suggest prorating the month at the date of the first payment or pushing to the 1st of the month payments made after the 20th of the previous month.

**Comment by Betree** [comment] 2019-07-04 11:46
@piamancini We currently have 3466 active subscriptions for less than $10, which represents a total of $11.912/month + $23/year.

| interval | count | sum | 
|-------|------|---------| 
| month | 3359 | $11912 | 
| year  | 7    | $23    | 


<details>

```sql
SELECT "interval", COUNT(*), SUM(amount)
FROM "Subscriptions" 
WHERE amount < 1000 
AND "isActive" IS TRUE 
AND currency = 'USD'
GROUP BY interval
```

</details>

**Comment by Betree** [comment] 2019-07-04 11:49
Also the conclusion from https://github.com/opencollective/opencollective/issues/1916 was that batching would currently save ~$233.70/month in stripe fees.

**Comment by alanna** [comment] 2019-08-08 23:32
We continue to receive support requests about this, with angry people wanting refunds. Can this please be considered for prioritisation? @Betree what would it take to implement the solution you described?

**Comment by Betree** [comment] 2019-08-09 09:28
@alanna The solution I prefer is the one you suggested because that's what most services do and I believe that's what users usually expect when they create a subscription:

> I believe we should change how our recurring charges work, so that you are charged when you set it up, and then on that day of each month going forward.

This will break the possibility of implementing batching in the future but:
- Batching is complex to implement and we currently have no clear plan to do it
- From https://github.com/opencollective/opencollective/issues/1916, it would "only" save $233/month in Stripe fees
- The problem of double charges seems way more important to me than the $233 Stripe fees issue

I've never worked on the subscription code, but from there I'd say that **charging on the exact date instead of the first of the month should be pretty easy** (we just need to make sure that we only apply this new rule for new subscriptions - we don't need to update the old ones). Maybe @znarf can give a second opinion on that.

I'm all up for it and if this can indeed be done quickly then I can prioritize it, but I'd like to make sure we all agree on this as it is an important change. @piamancini @xdamman

**Comment by znarf** [comment] 2019-08-09 09:52
Let me propose another solution, after the middle of the month set next charge to the month after. Ie: August 12 -> September 1st, August 16th -> October 1st. Advantage: this will still allow us to batch in the future.

Whatever the solution we pick, let's make sure we have a team wide discussion and consensus before moving forward.

**Comment by piamancini** [comment] 2019-08-19 16:08
Let's do this during the Fall team retreat next month

**Comment by znarf** [comment] 2019-09-16 08:59
Seems that there is an understanding that my proposed solution (https://github.com/opencollective/opencollective/issues/1215#issuecomment-519858300) is an acceptable fix. Let's implement it.

**Comment by Betree** [comment] 2019-09-24 12:31
Adding on the [above data](https://github.com/opencollective/opencollective/issues/1215#issuecomment-508423286) about users being discouraged to create subscriptions at the end of the month, here's a graph showing subscriptions cancelled by users. **All** the pics that you see are 1st or 2nd of the month.

![image](https://user-images.githubusercontent.com/1556356/65511633-edc5aa00-ded7-11e9-8c2e-3ad4524cdb94.png)


Will be interesting to measure the success of the proposed fix based on these metrics.

**Closed** 2019-10-04 07:39 UTC
Labels: api, complexity → complex, feature, priority
