### ISSUE TITLE
Contribute As: review error handling in Create Organization

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective#1692] opened 2019-01-30 20:18 UTC
**Describe the bug**

In the Create Organization form, no errors should be displayed until required.

**To Reproduce**

1. Make sure you're authenticated
2. Go to 'https://opencollective.com/babel/contribute/tier/356-bronze-sponsors
3. In 'Contribute As, select 'Create Organization'
4. Focus on the 'Organization name' field
5. Focus on the 'Website' field
6. Focus on the 'GitHub' field

**Actual behavior**

Errors are displayed under the  'Organization name' and 'Website' fields

**Expected behavior**

No errors displayed until required:
- When focusing out of an input that is filled but invalid
- When submitting the form, if an input is required/empty or invalid

**Screenshots**

![screen shot 2019-01-30 at 11 39 36](https://user-images.githubusercontent.com/806/52010041-c1869480-24d4-11e9-94b1-ac6e5473269e.png)

**Comment by Betree** [comment] 2019-02-04 10:51
As of today the behaviour for the website field is confusing, it is marked as required but we accept submitting the form if not provided. Do we want to mark this field as optional?

**Comment by znarf** [comment] 2019-02-06 07:41
@Betree website is required, this should be enforced wherever it make sense.

**Comment by kewitz** [comment] 2019-02-06 12:05
About the validation when clicking the **Next Step** button:
Not sure if the UX worths the refactor.
There are two validations happening here: _Field Validation_ and _Step Validation_.

_Field Validation_ is responsible for validating our inputs in `ContributeAs` component.
It is triggered by input events, which are internal to `ContributeAs`.
If fields are valid, `ContributeAs` calls `updateProfile` from `createOrderNewFlow` page. `updateProfile` does exactly what it says it does, it updates `stepProfile`.

_Step Validation_ is responsible for enabling the Next Step.
This happens one level above, in `createOrderNewFlow` page.
It is processed in `getMaxStepIdx()` which is responsible for passing to `renderNextStepButton()` (triggered on rendering).

The problem is that we have two validations happening in different levels of abstraction.
`ContributeAs` and the Next Step button are siblings and children of `createOrderNewFlow`.
IMO, if we want to start calling step functions when clicking this button, this means these buttons should be children of the page and not siblings.
The other solution is implementing and Observer pattern (use events) to trigger actions across different components, but if we go with that, we'll eventually end up in _I made queso_.

**Comment by Betree** [comment] 2019-02-06 13:09
@kewitz I replied to this part directly on the PR https://github.com/opencollective/opencollective-frontend/pull/1371

**Closed** 2019-02-07 11:42 UTC
Labels: complexity › medium, enhancement, frontend
