### ISSUE TITLE
Deleting events

### ISSUE THREAD

**Issue by piamancini** [opencollective/opencollective#2496] opened 2019-10-03 14:38 UTC
**Describe the feature**

Events should be deletable.

**Expected behavior**

1. Go to a collective
2. Click on create event & create one
3. Click on edit event in order with the intention of deleting it
4. See a delete event button on the bottom of the screen, click on it
6. See a confirmation modal, confirm
7. The event is deleted

**Notes**

On the GraphQL side, events are "Collective", so the `deleteCollective` mutation should be used. If for some reason it's not usable, a new dedicated GraphQL mutation should be created.

**Comment by znarf** [comment] 2019-10-07 12:51
@piamancini Can you edit a bit? "See error" doesn't seem to apply here. Also, there is no "Current behavior".

More generally, that should be a feature request, not a bug.

**Comment by piamancini** [comment] 2019-10-07 17:12
@znarf I think you could delete events before, that's why I'm considering it a bug. - Happy to edit if this wasn't the case.

**Comment by someofthethings** [comment] 2019-10-07 17:34
Please post error here so I know if I can fix it. Navigating GUIs is time consuming and I prefer to fix based on source info.

**Comment by maddhruv** [comment] 2019-10-10 02:24
+1 for this feature. Had trouble deleting some random events I created 😬
@znarf can you assign this to me?

**Comment by znarf** [comment] 2019-10-10 09:32
@maddhruv yes

**Comment by znarf** [comment] 2019-11-18 11:11
The PR went stale unassigning.

**Closed** 2019-11-22 09:26 UTC
Labels: $200, bounty, complexity → simple, events, feature, frontend

**Comment by znarf** [comment] 2019-11-22 09:29
🏆 This issue was completed by @leonardohof 

To claim the bounty please, as a recurring contributor, please simply add it to your next invoice to Open Collective Engineering https://opencollective.com/engineering/expenses/new  Please make sure to mention the ticket number in the invoice and in the expense title.
