### ISSUE TITLE
NCP: add E2E tests for collectives

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#2442] opened 2019-09-20 16:37 UTC
The new collective page doesn't have a good test coverage yet. We want to solve that by adding new cypress tests. We've added the paths that we want to cover in https://github.com/opencollective/opencollective-frontend/blob/master/test/cypress/integration/04-collective_v2.test.js.

To implement the missing tests, you need to:
1. Setup your local environment & check the best practices: https://github.com/opencollective/opencollective-frontend/blob/master/docs/e2e.md
2. Open `test/cypress/integration/04-collective_v2.test.js`, for each test with a `// TODO`:
    - Remove the `.skip` (`it.skip('...')` --> `it('...')`)
    - Implement the test (make sure it passes)
    - If you're not sure about what should be tested for a given test, please ask directly on this issue
3. Commit the result, CI will run your tests to make sure they pass.

**Comment by NotJohs** [comment] 2019-09-25 01:16
@Betree can I be assigned this task

**Comment by NotJohs** [comment] 2019-09-27 17:18
@Betree can I get avatar and cover image

**Comment by Betree** [comment] 2019-09-27 17:25
@NotJohs Sorry, I don't understand what you need exactly?

**Comment by Betree** [comment] 2019-09-27 17:26
As a helper for the file upload feature, feel free to install & use https://www.npmjs.com/package/cypress-file-upload

**Comment by NotJohs** [comment] 2019-09-27 17:28
@Betree `'can change avatar' `and `'can change cover background-image'`
both need images to be uploaded and my question is: 
should I use any image or would one be provided to me?

**Comment by Betree** [comment] 2019-09-27 17:34
Feel free to use any image :slightly_smiling_face:

**Comment by NotJohs** [comment] 2019-09-27 17:36
Alright

**Comment by NotJohs** [comment] 2019-09-27 18:13
@Betree having a little issue with the `cy.login` command
After creating a hosted collective, I log in with `cy.login` command which worked and redirected to ``/<randomslug>/v2``.
The problem is after redirection I logged off the `testuser`

**Comment by Betree** [comment] 2019-09-30 09:29
@NotJohs Can you share the code with me?

**Comment by NotJohs** [comment] 2019-09-30 11:36
Currently in the hospital. Will do when i get back home.

**Comment by Betree** [comment] 2019-10-01 08:55
I hope everything's fine for you @NotJohs, let me know if I can help (there's no problem if you need additional time to complete this)

**Comment by NotJohs** [comment] 2019-10-01 09:01
@Betree Thanks a lot. Currently working on this.

**Comment by znarf** [comment] 2019-11-05 11:49
🏆 This issue was completed by @NotJohs

To claim the bounty please, as a recurring contributor, please simply add it to your next invoice to Open Collective Engineering https://opencollective.com/engineering/expenses/new

**Comment by NotJohs** [comment] 2019-11-07 09:48
@znarf can we close this issue?

**Closed** 2019-11-07 10:38 UTC
Labels: $300, bounty, complexity → medium, frontend, test
