### ISSUE TITLE
Typing into date picker breaks

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5162] opened 2022-01-28 01:08 UTC
**Describe the bug**
This is what happens when I click into the date picker on the expenses page and type 0 1 01 2 0 1 9

![](https://i.gyazo.com/4b1e73334ccffaf09757cc952b991fe3.gif)

**To Reproduce**
1. Go to the expenses list of a Collective
2. Open the date picker
3. Try to type in a date

**Desktop (please complete the following information):**
MacOS Monterey, Firefox 96.0.2

**Comment by Betree** [comment] 2022-02-03 09:07
I haven't found the time to dig into this one but was able to reproduce it, it's an annoying one that affects many parts of the UI. I'm adding a bounty on this.

**Comment by Betree** [comment] 2022-02-03 09:08
:gift: :money_with_wings: A **$200** bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $200 when the Pull Request is reviewed, accepted, and merged.

:arrow_right: [More info](https://docs.opencollective.com/help/developers/bounties)

**Comment by JoyLubega** [comment] 2022-02-04 12:18
Hi @snitin315   can  work on this one since you are working on another bounty

**Comment by snitin315** [comment] 2022-02-04 12:19
Sure.

**Comment by JoyLubega** [comment] 2022-02-04 12:26
Thanks so much

**Comment by Betree** [comment] 2022-02-17 07:55
:trophy: This issue has been completed by @JoyLubega  

To claim the bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)

**Comment by alanna** [comment] 2023-10-16 20:25
This is happening again. Here's me trying to type `0 1 0 7 2 0 2 3`

![](https://i.gyazo.com/a7d3f9d51e67049d8d4ad2c98723fa87.gif)

**Comment by Betree** [comment] 2023-10-17 06:59
The `useEffect` added in https://github.com/opencollective/opencollective-frontend/pull/8736/files#diff-6023aad1ed480e0431173b9cdbe3ab33d7804e90c93dbcc2d8588709c8fa3becR136 seems to be the cause of the problem. Looking at it.

**Closed** 2023-10-19 11:54 UTC
Labels: bug, complexity → simple, frontend, bounty, important, $200
