### ISSUE TITLE
slow login produces a 500 when trying to donate before it finishes

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#528] opened 2017-10-18 15:41 UTC
Message from Marius:

> I've been setting up the Kea collective page now and found a few bugs to report.
> 
> First, the first time I clicked on "collaborate" on the $50 tier when logged in as myself, I got this:
> and clicking "forward" opened the correct donation page.
<img width="1396" alt="screen shot 2017-10-18 at 12 50 52" src="https://user-images.githubusercontent.com/30665166/31728012-c89d49cc-b3f0-11e7-9948-db857646ef4e.png">

**Comment by xdamman** [comment] 2017-10-19 06:47
I can't reproduce this. Could you?

**Comment by piamancini** [comment] 2017-10-19 16:28
@xdamman yes. If you hit on the contribute button before the page finishes logging you in (it takes a while) you get that error. 

<img width="1269" alt="screen shot 2017-10-19 at 12 27 14 pm" src="https://user-images.githubusercontent.com/3671070/31782452-ee12ee9a-b4c8-11e7-85bd-558372bebd5f.png">

**Comment by piamancini** [comment] 2017-10-19 16:29
seems related to this https://github.com/opencollective/opencollective/issues/484

**Comment by xdamman** [comment] 2017-10-23 02:52
I've speed up considerably the loading time of the logged in user. I'm not able to reproduce it anymore locally. Let's keep an eye on this one.

**Comment by piamancini** [comment] 2017-10-23 15:01
will do! closing this issue until it pops up again.

**Closed by piamancini** 2017-10-23 15:01 UTC
Labels: high priority, v2
