### ISSUE TITLE
Export members in csv no longer works

### ISSUE THREAD

**Issue by luceos** [opencollective/opencollective#1032] opened 2018-04-27 17:48 UTC
request uri: https://opencollective.com/tenancy/members/all.csv

```
cache-control: no-cache, no-store
cf-cache-status: MISS
cf-ray: 412318aa6ffe9d26-AMS
content-type: text/html; charset=utf-8
date: Fri, 27 Apr 2018 17:44:48 GMT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
oc-backend: frontend
oc-environment: production
server: cloudflare
status: 503
vary: Accept-Encoding
```

it seemed to download at some point, but with incorrect contents:

![image](https://user-images.githubusercontent.com/504687/39377011-ecd472da-4a53-11e8-9909-68af26ac29bc.png)

**Comment by znarf** [comment] 2018-04-29 20:52
I'm new to Open Collective and I'm looking at it. Unfortunately, the error output is currently not the way it should be. But it's possible that it's saying "Need to be logged in to export members in CSV".

How are you downloading it? When was the last time it worked for you?

**Comment by znarf** [comment] 2018-04-30 06:51
Looks like it's working for others but something specific to your data is breaking it. I'm on it.

**Comment by luceos** [comment] 2018-04-30 07:12
I've been moved to Europe recently, that might have affected it @znarf. Hope you find something 🙇

**Comment by piamancini** [comment] 2018-04-30 10:08
@znarf indeed, he's collective used to be hosted in open source collective and now it's hosted by open collective europe, but that shouldn't break this.

**Comment by znarf** [comment] 2018-05-01 13:44
I made some good progress regarding the problem reported by @luceos. A fix should land tomorrow. I don't think it's because the collective moved to Europe.

@piamancini Regarding your additional report, what collective are you trying to export?

**Comment by znarf** [comment] 2018-05-02 07:42
So, the root cause was that there are Collectives in the database without a createdByUserId. Let's track that in a new ticket:
https://github.com/opencollective/opencollective-api/issues/1258

The problem was reproducible when checking permissions for an authenticated user to access the email of an Organization. This is fixed in:
https://github.com/opencollective/opencollective-api/pull/1259

When debugging, I also encountered an issue preventing GraphQL responses to be sent, fixed in:
https://github.com/opencollective/opencollective-api/pull/1257

Also, please note that the CSV export only works when using the button from the interface. Accessing the URL directly will generate an error because the authentication headers are not sent. Previously, this error was not properly sent back to the user. This is fixed in:
https://github.com/opencollective/frontend/pull/353

**Comment by luceos** [comment] 2018-05-02 07:52
@znarf is there a way to use a permanent token to access the endpoint so getting the email address automated is still possible?

**Comment by znarf** [comment] 2018-05-02 08:06
@luceos It's not officially supported, but it's possible, unfortunately not as a permanent token. You need to add an Authorization header containing your access token: `Authorization: Bearer YOUR_ACCESS_TOKEN`. If you look at requests from the website to the API in your browser, you should be able to find this access token. Unfortunately, it will expire at some point and you'll need to update it.

**Closed** 2018-05-02 12:04 UTC
Labels: bug, high priority
