### ISSUE TITLE
Approve/Reject buttons visible after approving REconomy

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#798] opened 2018-01-04 16:41 UTC
Nenad from https://opencollective.com/reconomycop/ collective is having trouble again with the approve/reject buttons showing even after approving an expense. 

He also says that the available balance is not updating/reflecting the real amount. They are having problems to make the expenses as paid, that's the end result.

**Comment by xdamman** [comment] 2018-01-05 13:28
For 15mn you can still reject the expense. It's meant in case people have approved an expense by mistake.

**Comment by xdamman** [comment] 2018-01-05 16:07
Can someone try to reproduce this on staging?
Don't have the time to look at it now.

**Comment by piamancini** [comment] 2018-01-05 16:22
you can see it live. he's been waiting on this for a while. It's this same error https://github.com/opencollective/opencollective/issues/727

**Comment by asood123** [comment] 2018-01-09 15:57
What's the update on this @xdamman ? It's marked high-priority.

**Comment by xdamman** [comment] 2018-01-09 16:00
I've updated the #727 issue. Cannot reproduce. It's probably not clear for this user that "approved" doesn't mean that it has been paid.

Closing this one to avoid duplicated.

**Closed by xdamman** 2018-01-09 16:00 UTC
Labels: bug, high priority
