### ISSUE TITLE
Banner saying Collective is pending shows even after approval

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2100] opened 2019-06-06 04:12 UTC
I'm not sure if this is the same as #1878, but that issues doesn't describe it like it's a bug.

**Describe the bug**
@mixmix created a Collective for Patchbay using the GitHub automatic approval flow. It was approved and was active, but the system still showed him this green banner indicating his Collective had not been approved yet. This was confusing. 

![unnamed](https://user-images.githubusercontent.com/5498878/59006373-ad351880-8875-11e9-850c-de9a0004b967.png)

**To Reproduce**
1. Create new Collective for a project with 100 stars using the GitHub flow
2. See banner even though your Collective is already approved

**Expected behavior**
When someone successfully completes the Github approval flow, they should be taken to their active Collective. If they are shown a message, it should say the Collective is already approved and activated.

**Comment by mixmix** [comment] 2019-06-08 11:25
yeah #1878 is similar, but is specifically saying "The message is confusing, write that better". This issue is "This message is there times when it shouldn't be". Both are important

I've closed this issue (duplicate of mine)  https://github.com/opencollective/opencollective/issues/2108 , but there's a link in case you want to read how I describe it.

**Comment by piamancini** [comment] 2019-06-10 09:50
@xdamman could you look into this on Friday?

**Comment by znarf** [comment] 2019-06-13 12:18
- The message should be customized depending if the collective is approved or not.
- The upcoming "pending approval banner" https://github.com/opencollective/opencollective/issues/1878 should not be displayed at the same time that this green message.

**Comment by znarf** [comment] 2019-07-05 14:41
It will be taken care of in https://github.com/opencollective/opencollective/issues/1878

**Closed** 2019-09-30 11:36 UTC
Labels: bug, complexity → simple, frontend, hackathon
