### ISSUE TITLE
Accessibility: Confetti animates and shouldn't when prefers-reduced-motion set

### ISSUE THREAD

**Issue by iliana** [opencollective/opencollective#3036] opened 2020-04-03 05:56 UTC
**Describe the bug**
Confetti animates after becoming a member of a project regardless of [the prefers-reduced-motion media query](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion), causing site accessibility issues

**To Reproduce**
1. Configure your OS or browser to prefer reduced motion (for Firefox on Linux, I do this by setting `ui.prefersReducedMotion` to `1` in about:config, but this is an OS-wide accessibility setting on [macOS](https://support.apple.com/guide/mac-help/reduce-screen-motion-mchlc03f57a1/mac) and [Windows](https://developer.paciellogroup.com/blog/2019/05/short-note-on-prefers-reduced-motion-and-puzzled-windows-users/))
2. Click through the prompts to give money to a project
3. :tada: confetti moves around :tada:
4. Become motion sick, if you're like me and [other folks](https://webkit.org/blog/7551/responsive-design-for-motion/)

**Expected behavior**
Confetti probably shouldn't animate in multiple directions or at all when prefers-reduced-motion is set. A static image is likely the best option; fades are probably okay. See https://webkit.org/blog/7551/responsive-design-for-motion/ for some tips in designing for motion accessibility.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 74

**Additional context**
What kind of motion is a problem for people is 100% subjective based on a person's needs. I'll offer to test any fixes made for this, but what is fine for me is a vestibular trigger for someone else. I'll recommend a static confetti image when the prefers-reduced-motion media query suggests that a user needs reduced motion.

**Comment by Betree** [comment] 2020-04-03 08:09
Hi @iliana, thank you very much for opening this very well-documented issue. I've created a second one based on your description on the [canvas-confetti library repo](https://github.com/catdad/canvas-confetti/issues/114) (the one we're using) to get a chance at fixing this for everyone else using it.

We'll keep this one open until the problem is solved on our end.

**Comment by Betree** [comment] 2020-04-08 13:42
New version has been merged with https://github.com/opencollective/opencollective-frontend/pull/3889, I'll iterate on this issue now together with #3019

**Closed** 2020-04-09 07:26 UTC
Labels: accessibility, blocked → waiting parent, complexity → simple, frontend

**Comment by Betree** [comment] 2020-04-09 07:28
The fix will be deployed soon. Thanks @iliana!
