### ISSUE TITLE
Value too long for type character varying error on Update preview

### ISSUE THREAD

**Issue by flaki** [opencollective/opencollective#3702] opened 2020-11-22 12:12 UTC
**Describe the bug**
Getting an error when trying to preview/create a new Update:

> **Update failed: value too long for type character varying(255)**

**To Reproduce**
Not exactly sure, to be honest.

Started out trying to bring [this document](https://hackmd.io/6JaBAp6KT1K8yyzxZ0HAIQ?both) over from HackMD and initially it worked fine (one needs to copy-paste the formatted version into the WYSIWYG editor), but with a few edits to make it look better with Open Collective's formatting at some point it started throwing this error back on edits, and even when trying to create a new document.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/2089432/99903299-317a9600-2ccc-11eb-97f9-a2198c22013a.png)

**Desktop (please complete the following information):**
 - OS: Arch Linuxe (Gnome on Wayland)
 - Browser Firefox
 - Version 85

**Additional context**

**Comment by Betree** [comment] 2020-11-26 10:47
@flaki I wasn't able to reproduce, I tried copy pasting the content from HackMD + doing some edits but can't get the bug yet. Tested on https://staging.opencollective.com/captainfact_io/updates/welcoming-the-rustfest-project

Would you be able to copy paste the exact content that's triggering the error? Best would be to get it from the `.ql-editor`:

![image](https://user-images.githubusercontent.com/1556356/100341670-2af66200-2fdd-11eb-9493-82fa2f6eb3b0.png)

**Comment by znarf** [comment] 2020-12-09 21:34
We'll have to close if we can't reproduce I'm afraid.

**Comment by znarf** [comment] 2020-12-18 10:45
255 can't be about the content itself, it's either `slug`, `title`, `image`, `tags`, `summary` or `notificationAudience`.

**Comment by znarf** [comment] 2020-12-18 10:53
If I try to submit a long title, I get:

<img width="1088" alt="Screenshot 2020-12-18 at 11 49 43" src="https://user-images.githubusercontent.com/806/102606543-2b3ed480-4127-11eb-92ad-11604f6951d9.png">

Tell me that it's not `title`, it has its own validation. I discard `image`, `tags` or `notificationAudience` because they're not in the form. We have `summary` left ...

**Comment by znarf** [comment] 2020-12-18 11:08
It's autogenerated by `generateSummaryForHTML`. I suspect an issue with utf8 handling in `generateSummaryForHTML`.

Reproducing here: https://github.com/opencollective/opencollective-api/pull/5041

**Comment by flaki** [comment] 2020-12-18 11:08
Note that 1. the hackmd's current latest content is different from what produced the bug and 2. it's definitely an iterative bug, it needed multiple modifications to surface, so I'm guessing it might be some junk getting into the text area due to transforms. I can do some testing over the weekend to see if I can get this to reproduce on staging!

**Comment by flaki** [comment] 2020-12-18 11:13
Oh yes that VARCHAR(255) surprised me too, but if it's auto-generated on submission that would make sense. I really wish I saved the request/response when I submitted this to help reproduce 🤔

**Comment by znarf** [comment] 2020-12-18 11:21
It's just a blind guess, but we could try https://github.com/parshap/truncate-utf8-bytes

**Comment by flaki** [comment] 2020-12-18 11:30
Also there's not much UTF-8 in that post for the first half at least that is relevant here (maybe the quotes?).

I've been trying to reproduce for the past 10 minutes but without much luck.

I guess if we can't find the root cause you could just treat the symptoms (and ensure that summary contents are the correct byte length or set up some logging to see if this reproduces in the wild).

**Comment by znarf** [comment] 2020-12-18 11:39
I'm discarding utf-8 now and looking at improper truncating of html tags.

**Comment by znarf** [comment] 2020-12-19 10:17
Tentatively fixed in https://github.com/opencollective/opencollective-api/pull/5041

Closing!

**Closed by znarf** 2020-12-19 10:17 UTC
Labels: api, bug, complexity → unknown, frontend
