### ISSUE TITLE
Missing field in Zapier integration

### ISSUE THREAD

**Issue by josesimoes** [opencollective/opencollective#2527] opened 2019-10-16 10:58 UTC
**Describe the bug**
It seems that the field `Data Order Total Amount` is empty on Zapier integration.

**To Reproduce**
Steps to reproduce the behaviour:
This is the setup I have in Zapier:

![image](https://user-images.githubusercontent.com/1881520/66912854-4f76c100-f00b-11e9-9cc1-1d51f86aa6c5.png)

This is a real message in our Discord channel:
![image](https://user-images.githubusercontent.com/1881520/66913132-f22f3f80-f00b-11e9-8993-8c26801d7c9b.png)

Note that the amount is missing.
Also worth noting that if I use the "test" feature in Zappier setup I do get a message with an amount in the message:

![image](https://user-images.githubusercontent.com/1881520/66913213-1be86680-f00c-11e9-9c32-ed81eb0ff501.png)

**Expected behavior**
The amount field should be populated with correct value.

**Additional context**
- I'm using Zapier app v1.0

**Comment by znarf** [comment] 2019-10-21 08:24
@Betree can you have a look?

**Comment by Betree** [comment] 2019-10-30 12:32
@josesimoes Thanks for reporting this issue, we indeed have a bug for this webhook event that should be fixed by https://github.com/opencollective/opencollective-api/pull/2826.

**Comment by josesimoes** [comment] 2019-10-30 12:36
@Betree thanks!

Worth pointing out that the icon on the message is the one from Zappier and not the user avatar. Unlike what's showing on the test message. Probably related...

**Comment by Betree** [comment] 2019-11-12 08:10
@josesimoes I'll look at that as well.

Feel free to re-open this issue if the problem is not solved on your end.

**Closed by Betree** 2019-11-12 08:10 UTC
Labels: api, bug, complexity → simple, integrations

**Comment by josesimoes** [comment] 2019-12-04 13:15
@Betree we got a contribution today and it looked too generous to be true, so I went and double check it. Seems that the decimal separator is missing. See below the output that we got at our endpoint.

![image](https://user-images.githubusercontent.com/1881520/70145509-26cc8880-1698-11ea-966b-3f841c7c15fe.png)

**Comment by Betree** [comment] 2019-12-04 13:47
@josesimoes Amounts are in cents (we do this to handle the [imprecision of processors when dealing with float amounts](https://stackoverflow.com/questions/21895756/why-are-floating-point-numbers-inaccurate)). You can add a formatter on Zappier to handle this (just divide amount by 100). 

We recognize that this is not ideal, which is why #2117 was started.
