### ISSUE TITLE
Update `mdillon/postgis` to official image

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#4217] opened 2021-04-22 15:21 UTC
It seems that the [`mdillon/postgis` image that we use](https://registry.hub.docker.com/r/mdillon/postgis) is outdated and moved to the new home, https://registry.hub.docker.com/r/postgis/postgis/ and renamed to `postgis/postgis`. I think we should update our docs and CI to use this image preferably as that seems to be the official image released by postgis. Only difference is that for this image to work we need to pass a super user password or set `POSTGRES_HOST_AUTH_METHOD: trust`.

**Comment by Betree** [comment] 2021-04-22 15:24
I think we're rather heading in [that](https://github.com/opencollective/opencollective/issues/3171) direction :wink:

**Comment by SudharakaP** [comment] 2021-04-22 15:36
> I think we're rather heading in [that](https://github.com/opencollective/opencollective/issues/3171) direction wink
> 
> (edit: that does not prevent updating the image if it improves the codebase)

Ah, didn't know we were going to remove postgis altogether. 😄

**Comment by znarf** [comment] 2021-04-26 10:09
I merged the PRs.

I still think it would be valuable to get rid of postgis, the issue is still relevant. https://github.com/opencollective/opencollective/issues/3171

**Closed by znarf** 2021-04-26 10:09 UTC
Labels: api, complexity → simple, enhancement, frontend
