### ISSUE TITLE
Include financial contributor contact info in notification

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2297] opened 2019-08-02 03:39 UTC
## User story 
As a core contributor, I want to be able to contact new financial contributors to my Collective, so that I can connect with them and build a relationship.

## MVP
Add an 'email' field to the email that core contributors get when a new financial contributor gives to their Collective.

This is a user requested feature via support.

**Comment by alanna** [comment] 2020-02-05 21:02
Sorry @znarf I added `bounty candidate` but then realised you previously removed it. Is this not a simple one?

**Comment by alanna** [comment] 2020-02-17 00:10
Bump. This has been requested again by users.

**Comment by znarf** [comment] 2020-02-20 11:21
@alanna I removed "bounty candidate" when we added "hackathon" but we then removed "hackathon".

**Comment by znarf** [comment] 2020-02-21 07:25
A $100 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $100 when the Pull Request is reviewed, accepted and merged. [More info](BOUNTY.md)

This bounty is currently reserved to participants of the Open Source Festival event. If not completed there, it will be later open to everyone.

**Comment by bolariin** [comment] 2020-02-24 00:06
What is the expectation if the financial contributor is made by a collective or an org?

**Comment by znarf** [comment] 2020-02-24 09:18
@bolariin Good question. I think it's ok to just ignore it for now.

**Comment by joshikeno** [comment] 2020-02-24 16:28
@bolariin Please indicate if you are from `OSCA` as this issues tagged `OSCA` is reserved.

**Comment by bolariin** [comment] 2020-02-24 16:45
Oh my bad, I didn't know about that. I'm not part of `OSCA`. Sorry about that.

**Comment by hacktivist123** [comment] 2020-02-25 00:30
Hello @znarf can you assign me to this task, i am from osca.

**Comment by znarf** [comment] 2020-02-27 08:49
@hacktivist123 you're assigned on another issue, let's focus on that.

**Comment by JoyLubega** [comment] 2020-03-06 12:05
@znarf, @alanna   I need some clarification. Do I need to create a new email template? I am also assuming, `notification` == `email` OR If Notification is not the same as email on the backend, do I need to just add the field in a certain object that sends the notification?

**Comment by znarf** [comment] 2020-03-06 12:08
I think this is just about adding the email address of the contributor somewhere in the template. If applicable (individual contributor only).

**Comment by JoyLubega** [comment] 2020-03-06 13:22
Perfect 👍. Thanks

**Comment by snitin315** [comment] 2020-06-05 13:35
@JoyLubega are you still working on this?

**Comment by JoyLubega** [comment] 2020-06-05 15:01
You can go ahead with it

**Comment by snitin315** [comment] 2020-06-15 03:18
Is there any specific reason we should not display email if it's an organization?

**Comment by znarf** [comment] 2020-06-22 17:25
My take was to skip it for Organization, because it's complicated, there is no unique email for an Organization, there is one email per collective admin of the Organization. @alanna may provide more feedback.

For the meantime, I suggest to not have Organization support.

Finally, please double check that we're not exposing the email address of Incognito users.

**Comment by alanna** [comment] 2020-06-23 01:23
I think we should still provide contributor contact info for organzations. The purpose of this feature is to give core contributors a way to deepen relationships with their funders, and many time the most important ones are organizations. I think it's fine to just put the email of one of the active org admins if there are multiple.

Alternatively, we could address this by adding a `contact` button to all org profiles and directing core contributors to use that, but that would be a whole other kind of solution.

**Comment by Betree** [comment] 2020-06-23 06:56
The problem is that we're using the `CreatedByUserId` field, which maybe someone else (ie. some collectives were created for users by Pia or Xavier) and more importantly that may be someone that is not an admin anymore of the Collective.

This is a bounty, introducing more complexity to handle organizations admins is not fair to the contributor. I propose that we stick with what @znarf initially specified in https://github.com/opencollective/opencollective/issues/2297#issuecomment-595740413, to only show the email if "individual contributor only". We can later follow up on extending this feature to organizations.

**Comment by Betree** [comment] 2020-06-24 11:33
:trophy: This issue has been completed by @snitin315  

To claim the **$100** bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)

**Closed** 2020-06-24 11:33 UTC
Labels: $100, api, bounty, complexity → minimal, feature

**Comment by Betree** [comment] 2020-06-24 11:34
I've created a followup issue for including the org admins emails: https://github.com/opencollective/opencollective/issues/3273
