### ISSUE TITLE
Ability to edit a pending order

### ISSUE THREAD

**Issue by alinamanko** [opencollective/opencollective#4069] opened 2021-03-09 01:22 UTC
## User story 
A user is looking to make a contribution using the option of bank transfer to a collective which generates a pending order on the system for the amount of the contribution. In some instances, upon making the transfer, a bank transfer fee is deducted, making the net amount transferred slightly lower (normally about $20 difference - depending on the amount transferred). Currently, there is no option to edit the order from the host dashboard and in this instance, the host admin has to mark the pending order as expired and add the funds manually. Normally it is a bit of a nuisance. However now, with guests contributions in place, it is getting quite tricky to recreate the user profile when they are not registered on the platform. 

**Recent example:**

_Funds received in the bank - $980 (extract from Xero):_

![Screenshot 2021-03-09 141924](https://user-images.githubusercontent.com/57156267/110403743-7fcc6d00-80e2-11eb-9ddf-0f7ec3d1b77c.png)

_Pending order as showing on Open Collective ($1,000):_

![Capture](https://user-images.githubusercontent.com/57156267/110403593-3ed45880-80e2-11eb-9561-7a2d1522f673.JPG)

## Best solution for this problem
It would be great to add a field for allocating bank transfer fees allow the host admin to adjust the net amount of funds received. Or alternatively, allow for the option of editing the order amount without the reflection of the bank fees which we effectively don't really see as all that really matters is the net amount received in the bank and allocated to the collective. 

## Metrics 
There is a clear link between the order originally created and the funds received by the collective for instances where the original amount of the contribution had to be altered. It also will make the user experience better as the contributor can track the status of their transfer based on the order alone.

**Comment by alanna** [comment] 2021-05-05 21:05
#2702 and #4144 are about the same thing

**Comment by alanna** [comment] 2021-10-30 07:53
@Betree could this be added to root admin? Like we enter the pending order reference code and can then edit the amount?

**Comment by Betree** [comment] 2021-11-02 07:08
@alanna I think we should directly add this for all host admins. Adding that to the root admin instead wouldn't simplify that much, because there are no complex security checks here: we can always trust host admins to know what arrived in their bank account.

A small input from @opencollective/design on this one would be welcome :wink:

**Comment by Memo-Es** [comment] 2021-11-02 14:15
@Betree, I'm thinking of including this for the next sprint. Is that ok? Or is it more pressing?

**Comment by Betree** [comment] 2021-11-02 14:17
@Memo-Es IMO it's not an emergency as we can handle most cases through support, but I'll let @alanna confirm.

**Comment by alanna** [comment] 2021-11-02 19:40
If we don't do this, engineering needs to do this manually and we're making people wait longer for their money. So it's not a blocker it's just a pain.

**Comment by Memo-Es** [comment] 2021-11-29 00:09
Plan for this week

- [ ] Wrap-up production files

**Comment by aminakazi** [comment] 2021-12-06 10:50
Production ready file is [linked here](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?node-id=15268%3A213802)

**Comment by SudharakaP** [comment] 2021-12-13 15:45
@aminakazi : Just to clarify the edit modal for the pending order appears when the user clicks on the `Mark as Completed` button?

**Comment by znarf** [comment] 2021-12-14 10:55
I see a few potential ambiguities with the current design. Let's look at some scenarios to be sure we're on the same page.

**1) A contributor donate $100 to a Collective with $20 as Platform Tip. $120 arrive on the Fiscal Host bank account as intended.**

- In the current design, "amount initiated" would be equal to $120, right?
- What would be the value of the "Amount received" field? $120 and greyed?
- What would be the value of the Platform Tip field? $20 and greyed?

**2) A contributor donate $100 to a Collective with $20 as Platform Tip. $100 arrive on the Fiscal Host bank account, the contributor skipped the Platform Tip.**

So far, everything should work like the previous scenario.

- We're expecting the user to replace the greyed default of $20 with $0 and press confirm. Correct?

**3) A generous company donate $10000 to a Collective. Only $9575 arrive on the Fiscal Host bank account because of unknown reasons, certainly payment processor fees.**

If we follow previous scenarios:

- "amount initiated" would be equal to $10000
- "amount received" would be equal to $10000 and greyed. We expect Host Admins to replace the default and enter $9575 here.
- "payment processor fee" would be equal to $0 and greyed. Host Admins can enter enter $425 here in place of the default.

That way, we will enter this in the ledger as a transaction of $10000 with $425 payment processor fees. Net amount for the Collective will be $9575.

Make sense?

@aminakazi, let me know if anything that is written here is not right.

**Comment by kewitz** [comment] 2021-12-16 18:23
@aminakazi could you explain why there is a dropdown arrow in the currency field?

I understand that this modal is displayed to the host who's settling the order, shouldn't we expect these values to be passed in the host currency, despite a possible edge-case where the order/collective currency doesn't match the host currency?

cc @znarf, @SudharakaP

**Comment by znarf** [comment] 2021-12-16 19:13
There should be no dropdown for the currency here, everything should be expressed in the currency of the order (which is already set, doesn't change and is certainly the currency of the collective). The host currency is not at play there, at least not for now.

**Comment by Memo-Es** [comment] 2021-12-16 19:47
Cool, I just removed the currency dropdown from the file @kewitz

**Comment by SudharakaP** [comment] 2021-12-20 05:19
- [ ] Finalize and merge the API and Front-end PRs.

**Comment by SudharakaP** [comment] 2021-12-20 13:58
@Memo-Es @aminakazi : [Something which @Betree](https://github.com/opencollective/opencollective-frontend/pull/7268#discussion_r772221950) brought up in one of our code reviews is that currently in the modal we have, "Amount received by {collective}"

![On Button tap](https://user-images.githubusercontent.com/12435965/146778383-87d1239e-b4a0-4cde-bf68-49150172366a.png)

Instead since the money is received by the fiscal host should this line actually be `Amount received by {fiscalHost}" ? 🤔

**Comment by Memo-Es** [comment] 2021-12-20 17:16
I agree with @znarf on:

> @Betree is right, but maybe we can rephrase "Amount received for {collective}".
And follow up later if we want to replace with fiscalHost.

Perhaps we should also ask @alanna

**Comment by alanna** [comment] 2021-12-22 01:29
I've asked Ember to look at this as I won't have a chance and don't want to slow you all down

**Comment by emberwry** [comment] 2021-12-23 20:32
hi! i'm catching up on this issue, but i don't think i have any blocking concerns, this seems to make sense to me and will be a great update. Watch the spelling of "received," and changing it to amount received for {fiscal host} makes more sense, per @SudharakaP's mockup.

**Comment by SudharakaP** [comment] 2021-12-24 05:29
> hi! i'm catching up on this issue, but i don't think i have any blocking concerns, this seems to make sense to me and will be a great update. Watch the spelling of "received," and changing it to amount received for {fiscal host} makes more sense, per @SudharakaP's mockup.

@emberwry : Thanks for confirming Ember. I've already [initiated the change](https://github.com/opencollective/opencollective-frontend/pull/7291); you'll soon see it in production. 

I am closing this issue since I think everything here is been tackled now. 😉

**Closed by SudharakaP** 2021-12-24 05:29 UTC
Labels: feature, complexity → medium, api, frontend, design

**Comment by Betree** [comment] 2021-12-24 07:23
> hi! i'm catching up on this issue, but i don't think i have any blocking concerns, this seems to make sense to me and will be a great update. Watch the spelling of "received," and changing it to amount received for {fiscal host} makes more sense, per @SudharakaP's mockup.

I'm not sure about the "Amount received **for** {fiscal host}" part. The amount is received **by** the fiscal host **for** a collective. So either:
1. `Amount received by {fiscalHost}`
2. Or `Amount received for {collective}`

In the end, I think the 2nd approach brings more valuable information: you're on the host admin panel, so you already know which host you're receiving the funds for (there's only one). But there can be multiple orders for different collectives on this page and admins may misclick or not remember which entry they selected. It's therefore helpful to remind that: `Amount received for Babel`.

**Comment by alanna** [comment] 2022-05-23 09:11
This is a small UX niggle but I had to come find this issue to confirm we built this feature because I wasn't going to click the `mark as completed` button on a wrong amount and there was no indication that I'd have another confirmation screen where I could make changes. Maybe we could add a hover tooltip on that button saying "You'll have the chance to confirm and make any needed adjustments to the amount". This seems to small to raise a whole new issue for...
