### ISSUE TITLE
`tier` missing from Contributor that switched from one-time donation to recurring

### ISSUE THREAD

**Issue by zachleat** [opencollective/opencollective#2794] opened 2020-01-10 14:40 UTC
**Describe the bug**

Hans Gerwitz has switched from being a one-time contributor to 11ty to a monthly. But his entry in the API is missing a `tier` entry.

**To Reproduce**
1. Go to https://opencollective.com/11ty/members/all.json
2. Find two entries for `https://opencollective.com/hans-gerwitz` (this is fine, one is active and one is not)
3. However, the active entry should have a `tier` property of “Backer” and it does not.

**Screenshots**
Missing a `tier`:
![image](https://user-images.githubusercontent.com/39355/72160744-7a5f7f80-3384-11ea-89e3-af22fcff2c72.png)

Other entry (this one has the tier, which is wrong I think?)
![image](https://user-images.githubusercontent.com/39355/72160793-8f3c1300-3384-11ea-9cea-e1dcf1781c5d.png)

**Comment by znarf** [comment] 2020-01-11 09:16
@zachleat this is a known issue (but could not find a reference in GitHub) that we're happy to manually fix for you. Can you contact support@opencollective.com ?

**Comment by znarf** [comment] 2020-01-13 09:02
I think a good enough mitigation would be to always update the Members table with the latest Tier. What do you think @Betree ?

**Comment by Betree** [comment] 2020-01-13 09:20
This was supposed to be fixed by https://github.com/opencollective/opencollective-api/pull/3060. I'll check why it didn't work.

**Comment by znarf** [comment] 2020-01-13 09:30
@Betree maybe the problem occurred before the fix

**Comment by Betree** [comment] 2020-01-13 09:35
Actually the tier is correct: contributor used to contribute through `Donation` (which is not a tier) - member 39458. When contributor switched to monthly, they used the `Backer` tier (member 68879).

So the question is about the `isActive` flag. `isActive` is always true for one-time contributions. The fact that it is false for `backer` on the other hand seems to be a bug: a recurring tier is normally active if the contributor made a contribution in the interval: https://github.com/opencollective/opencollective-api/blob/12969e740f8f151ed640c87fd0bde3ee06a96191/server/models/Member.js#L129

![image](https://user-images.githubusercontent.com/1556356/72244735-30c69d00-35ef-11ea-8538-c9ae5fe9e1d6.png)

**Comment by sbinlondon** [comment] 2020-10-08 15:36
Is this a bug we still need to fix?

**Comment by Betree** [comment] 2020-11-26 09:28
It looks fixed on https://opencollective.com/11ty/members/all.json, both members now have the `isActive` flag to `true`.
The fact that there are two entries for the same contributor is not a bug, it's the way this endpoint was designed.

For fetching deduplicated entries, one should now use the GQLV2 `contributors` field.

**Closed by Betree** 2020-11-26 09:28 UTC
Labels: bug, complexity → simple, frontend
