### ISSUE TITLE
Unable to edit invited expense

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#6956] opened 2023-08-27 22:30 UTC
https://opencollective.com/tauiwi-tautoko/expenses/157881

I invited an expense but then the payee told me I needed to add GST. So I went to the draft expense and clicked edit. However the 'pay to' was reset to myself instead of the real payee, and then it didn't let me search or select the correct payee so now I am stuck.

Unedited draft:
<img width="793" alt="Screen Shot 2023-08-28 at 10 25 15 AM" src="https://github.com/opencollective/opencollective/assets/5498878/49ae57ed-4269-4e04-83c6-56c462641779">

Defaulting to me as payee:
<img width="793" alt="Screen Shot 2023-08-28 at 10 25 32 AM" src="https://github.com/opencollective/opencollective/assets/5498878/7d1dba56-b2bb-4ffa-a631-d7e60d46cec5">

Unable to select correct payee:
<img width="800" alt="Screen Shot 2023-08-28 at 10 26 22 AM" src="https://github.com/opencollective/opencollective/assets/5498878/b5c4bed2-a366-405c-b8ce-c1001880d4c2">

**Comment by Betree** [comment] 2023-08-28 05:59
Sound like a duplicate of https://github.com/opencollective/opencollective/issues/6586, cc @kewitz

**Comment by alanna** [comment] 2023-08-28 22:03
Yes it's mostly a dup, except the point that it's not just nice to have, but totally blocking, because you *cannot* re-select the correct payee and you are completely stuck.

**Closed** 2023-10-05 09:55 UTC
Labels: bug, frontend, duplicate
