### ISSUE TITLE
Feedback: Send notification to added members of a collective

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#565] opened 2017-10-26 01:36 UTC
Feedback from Danny from La Conexión Collective:

> I think it would be great at a minimum for people to get notified they’ve been added as members of a collective- if not also given basic onboarding instructions, too!

**Comment by xdamman** [comment] 2017-10-26 01:48
Duplicate of #566 
Please check if there is no related issue before and if so just +1 it.

**Comment by xdamman** [comment] 2017-10-26 01:49
Actually, just realized that both our issues were sent the same minute and probably crossed each other ¯\_(ツ)_/¯

**Closed by xdamman** 2017-10-26 01:48 UTC
Labels: enhancement

**Comment by nicobarretoOC** [comment] 2017-10-26 01:56
No worries, good coincidence!
