### ISSUE TITLE
Can't disable 2FA

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3913] opened 2021-01-26 03:46 UTC
I clicked the 'enable 2FA' tickbox in host settings for Protozoa just to see how it works, but now the save button doesn't seem to do anything, and I don't see any options for disabling. So either it's turned on and the UI just isn't giving me feedback that it's saved, and there's no way to turn it off, or it hasn't actually been turned on. I do not want 2FA activated for this host.

**Comment by alanna** [comment] 2021-01-26 03:47
Ah, I see the note in the FAQ saying to contact support about disabling it, but that doesn't fix the UI issues where you can't tell if it's successfully beed turned on.

**Comment by znarf** [comment] 2021-01-26 09:05
It seems all right for me.

**Comment by alanna** [comment] 2021-01-27 01:37
When I click save, there's no change in the UI and it seems it hasn't saved.

https://user-images.githubusercontent.com/5498878/105929752-24ec3280-60ad-11eb-9ed3-238be8683358.mp4

**Comment by znarf** [comment] 2021-01-27 10:18
Then, it's not about disabling 2FA.

**Comment by alanna** [comment] 2021-01-27 22:31
1. If it is enabled, please disable it
2. if it is enabled, please fix the UI so the admin can know whether or not is enabled

**Comment by znarf** [comment] 2021-01-27 22:54
The ticket title says "Can't disable 2FA". The FAQ says "How do I disable 2FA once it's been enabled? For security purposes, 2FA can only be disabled by contacting support once it has been enabled.".

- If the issue is really about "Disabling 2FA", I'm afraid it's on purpose, as stated in the FAQ
- If the issue is about something else, then I suggest to create a new issue that clearly explains the problem.

@sbinlondon can jump in if there is any quick win on the UX side

**Comment by sbinlondon** [comment] 2021-02-03 14:56
I think we can do a quick win like a banner to say it's been turned on, certainly. Will add that to my list.

**Comment by znarf** [comment] 2021-03-20 07:38
Closing because it seems it was addressed by Kate. 

If that's not the case,  let's track this in another issue because this one started to be a bit confusing.

**Closed by znarf** 2021-03-20 07:38 UTC
Labels: bug
