### ISSUE TITLE
Feedback on payouts for 100% of the balance (put fees on the payee)

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#5255] opened 2022-02-23 21:51 UTC
Initially reported at, https://github.com/opencollective/opencollective/issues/5233#issuecomment-1047304606 by @emberwry

> hey y'all! It looks like this is the place to throw in some feedback? Feel free to redirect me :) this is for using it with some of the recent changes on showing the payment processing fees- i think one fix would be easy and the other more complicated (). more notes (from slack)
> 
>* paypal payouts where expense = collective balance, we have to manually pay them from paypal. What we have set up now for wise payments (the tick box, showing the payment fees) possible with paypal on our platform? or can we go back to automatically having the collective take on the fees, which I think is what was happening before? right now we have to process these manually, which leaves a ton of room for human error :/
> 
> Demo: https://www.loom.com/share/54c42224dec44cbc86bc131e678e97b7
>
>* the other is we had debated above about putting in the tick box (that the fee should come from the expense) for all wise expenses or only when expense = collective balance. often folks don't expense the full amount, but close enough to it that there's still not enough in the balance to pay. Can we re-add the little tick box to make the collective pay for the payment processing fees at ALL TIMES, not just when expense = collective budget?
>
> Demo: https://www.loom.com/share/aa96b64196b34d1da439a82997ab3a3f
>

**Comment by Betree** [comment] 2022-02-24 07:10
> paypal payouts where expense = collective balance, we have to manually pay them from paypal. What we have set up now for wise payments (the tick box, showing the payment fees) possible with paypal on our platform?

It is possible, we have it planned at #5033. I don't think it will be really complex, I was kinda waiting for a use case to implement it.

> or can we go back to automatically having the collective take on the fees, which I think is what was happening before?
That's still the default behavior, we haven't changed that.

> Can we re-add the little tick box to make the collective pay for the payment processing fees at ALL TIMES, not just when expense = collective budget?
To be clear: having the collective pay for the payment processor fees is the default behavior. The checkbox is there to move the responsibility of the fees on **the payee**. We could display it at all times (and I would argue we should edit this issue to target it on this topic since everything else is tracked elsewhere).

**Comment by emberwry** [comment] 2022-02-24 20:23
hm @Betree maybe i'm expressing it wrong- it's not that the collective isn't paying the payment processing fees, it's that when there's not enough balance to cover both the expense and the fees, the expense should automatically swallow these fees. right now, we have to do that manually- i go in to the expense, reduce it by the fee amount, pay it via paypal, and then record it manually with whatever the paypal fees were. this is a pain and prone to error. does that make sense?

**Comment by Betree** [comment] 2022-04-06 08:09
From what I understand this is a duplicate of https://github.com/opencollective/opencollective/issues/5033. Please re-open if I did not get tit right.

**Closed by Betree** 2022-04-06 08:09 UTC
Labels: enhancement, discussion, duplicate
