### ISSUE TITLE
Duplicate Contribution Cards Shown on User Profile

### ISSUE THREAD

**Issue by SudharakaP** [opencollective/opencollective#6745] opened 2023-05-11 23:04 UTC
**Describe the bug**

Note that some users see duplicate contribution cards on their profiles. This happens for example when they contribute to multiple tiers of the same collective. 

**To Reproduce**
1. Go to https://opencollective.com/polcode
2. Note that there's identical contribution cards

**Expected behavior**

We should remove the duplicates on the front-end. 

**Screenshots**

![image](https://github.com/opencollective/opencollective/assets/12435965/fec3a090-aac3-4c77-b5c8-f86809062500)

**Comment by Betree** [comment] 2023-05-15 06:54
Duplicate of https://github.com/opencollective/opencollective/issues/4672

**Closed by Betree** 2023-05-15 06:54 UTC
Labels: bug, complexity → simple, frontend, duplicate
