### ISSUE TITLE
Surprising color conversion after luminance adjustment

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3456] opened 2020-09-03 21:17 UTC
**Describe the bug**
A Collective admin is trying to update the custom color for [their Collective](https://opencollective.com/hrmi) to `#262262` which is a dark blue.

<img width="497" alt="Screen Shot 2020-09-04 at 9 13 03 AM" src="https://user-images.githubusercontent.com/5498878/92168814-dbe1da80-ee8e-11ea-87ee-e5832da3469e.png">

However, when they enter that and click save, it turns grey.

![grey](https://user-images.githubusercontent.com/5498878/92169360-fddb5d00-ee8e-11ea-86be-2ce199971e75.png)

They are able to successfully select any of the preset colors and they've tried other HEX codes that are working, just not their brand color which they need to use.

**To Reproduce**
I was able to reproduce this using that specific HEX code as well. All the other HEX codes I tried are working normally, just not that specific one.

**Comment by Betree** [comment] 2020-09-04 06:31
Duplicate of https://github.com/opencollective/opencollective/issues/3383

**Comment by Betree** [comment] 2020-09-04 06:38
Though this example of `#262262` turning to grey is a little strange, let's keep it open.

**Closed** 2020-12-24 14:38 UTC
Labels: bug, complexity → simple, frontend

**Comment by valeciawolf34** [comment] 2020-12-24 14:46
Vwolf_ua@nec.edu and and I have been working on the welcome-orb for the
last few days and I have been working on the welcome-orb for the last few
days and I have been working on the welcome-orb for the last few days and

Valecia G Rodriguez

**Comment by valeciawolf34** [comment] 2020-12-24 14:48
Valecia G Rodriguez
