### ISSUE TITLE
`Missing CODA_IN_APP_SURVEY_TOKEN` error message in Toast

### ISSUE THREAD

**Issue by NikitaKorevo** [opencollective/opencollective#7048] opened 2023-10-10 11:52 UTC
**Describe the bug**

`Missing CODA_IN_APP_SURVEY_TOKEN` error message in Toast

**To Reproduce**
local frontend and backend
1. Donate to collective
2. Click on emoji on Toast
3. See error message

**Expected behavior**
Toast without error message

**Screenshots**

https://github.com/opencollective/opencollective/assets/48645737/dbe2bd2a-441a-491e-a017-43527a820eb8

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by gustavlrsn** [comment] 2023-10-10 12:20
This is expected, but perhaps we should only display this error in staging and production (where the environment variable `CODA_IN_APP_SURVEY_TOKEN` is set). And instead log a mocked Coda fetch to the API console if the environment variable is not set.

We might also want to update the error message to say: "Missing CODA_IN_APP_SURVEY_TOKEN **environment variable**" to be clearer.

**Comment by Betree** [comment] 2024-01-04 06:21
I don't really see any issue there; we rely on a config variable that is not set by default because it would be easy to abuse it if we set one (it's a third-party service). Developers then get this clear error message if they test the feature and can easily search the codebase to understand what they need to fix.

The "Expected behavior" defined in the issue is: "Toast without error message". That means we either:
- Need to configure a CODA token by default - that won't happen (see above)
- Or ignore the error in dev, which is a far worse behavior than throwing an error message, as developers will then scratch their heads to understand why they're not seeing any result after submitting the form.

Unless there's a strong argument for a better solution, I think that we should close this.

**Comment by samkevin1** [comment] 2024-01-11 17:46
Should this issue get closed?

**Comment by gustavlrsn** [comment] 2024-01-11 18:29
@samkevin1 yep, closing this, thanks for the contribution!

**Closed by gustavlrsn** 2024-01-11 18:29 UTC
Labels: bug, frontend, developer experience
