### ISSUE TITLE
Update twitter logo.

### ISSUE THREAD

**Issue by Sandigupta** [opencollective/opencollective#7627] opened 2024-10-20 15:26 UTC
Updated Twitter social logo will remove confusion between new users. Improve user experience.![Image](https://github.com/user-attachments/assets/4f1a7962-5fbd-480b-a4fd-bbaa8da08859)

**Comment by Betree** [comment] 2024-10-21 06:10
Duplicate of https://github.com/opencollective/opencollective/issues/7195

**Closed** 2024-10-21 06:10 UTC
Labels: duplicate
