### ISSUE TITLE
Duplicate Entities showing under contributions. 

### ISSUE THREAD

**Issue by shannondwray** [opencollective/opencollective#5792] opened 2022-07-27 16:55 UTC
**Describe the bug**
When I think of contributions I think of money, I feel like we should have the core contributor section separate and under a different header. I find it confusing when the same entity is shown twice, looks like a bug. 

**Screenshots**
Screenshot attached 

**Desktop (please complete the following information):**
 - OS: Mac OS Monterey - Version 12.5 Beta 
 - Browser. Brave 
 - Version - [Version 1.41.96 Chromium: 103.0.5060.114 (Official Build) (x86_64)

<details>
  <summary>Triage Template (core team only)</summary>

  This template is for members of the team to triage for prioritisation. For more guidance see https://www.loom.com/share/369ab467fbc64dec848085d38ff57ca0:

  P1 high frequency, high impact
  P2 low frequency, high impact
  P3 high frequency, low impact
  P4 low frequency, low impact

  Examples of high impact - a problem affects users during an essential process (expenses and payments > onboarding and registration > contributing) with no workaround.

  High frequency - >10% of users affected (measured as a proportion of total potential users for this case).
</details>

**Comment by shannondwray** [comment] 2022-07-27 16:56
<img width="842" alt="Screen Shot 2022-07-27 at 5 47 53 PM" src="https://user-images.githubusercontent.com/79115149/181305503-356e5e4e-f50c-4747-a50c-b73cc4c4033a.png">

**Comment by Betree** [comment] 2022-07-29 08:56
Duplicate of https://github.com/opencollective/opencollective/issues/4672

**Closed by Betree** 2022-07-29 08:56 UTC
Labels: bug, duplicate
