### ISSUE TITLE
Use new SignIn component everywhere

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective#1676] opened 2019-01-25 15:37 UTC
Now that we have the [SignIn](https://github.com/opencollective/opencollective/issues/1486)  and the `SignInOrJoinFree` components ready, we should migrate all SignIn and SignUp forms to them.

- [ ] SignInForm.js
  - [x] Sign in page
  - [ ] src/apps/expenses/components/CreateExpenseForm.js
  - [ ] src/components/CreateCollective.js
  - [ ] src/components/CreateOrganization.js
  - [ ] src/components/EditCollective.js
  - [ ] src/pages/completePledge.js
  - [ ] src/pages/createHost.js

- [ ] SignInUp

  - [ ] `src/components/InterestedForm.js`

**Comment by flickz** [comment] 2019-01-25 16:18
@Betree Can I take this on?

**Comment by Betree** [comment] 2019-01-25 16:22
Hi @flickz thanks for offering! I'm not totally finished preparing the ground for this one and I'm already working on parts of it.

I can recommend going through these issues: https://github.com/opencollective/opencollective/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+label%3A%22complexity+%E2%80%BA+simple%22

**Comment by flickz** [comment] 2019-01-25 16:24
Good, Thanks!

**Comment by Betree** [comment] 2019-04-23 14:52
Update: Base component for this issues are ready.

**Comment by znarf** [comment] 2019-06-13 11:22
Closing as duplicate of https://github.com/opencollective/opencollective/issues/2119

**Closed by znarf** 2019-06-13 11:22 UTC
Labels: complexity → medium, frontend, technical-debt, up for grabs
