### ISSUE TITLE
Automatic data extraction (OCR through a service API) from receipts and invoices in the expense submission flow

### ISSUE THREAD

**Issue by iamronen** [opencollective/opencollective#6865] opened 2023-07-11 13:21 UTC
## Friction

A large number of expenses that are marked as incomplete have input errors, receipts omissions or illegible receipts. Over 25% of expenses and invoices that are marked as incomplete (at OCF, OSC and OCE combined) have issues that might be prevented through data extraction from receipts and invoices at the time of submission.

![Image](https://github.com/opencollective/opencollective/assets/8337819/502ffce3-ffdb-4923-85c0-d98e507ef42d)

Figure: Incomplete expenses in categories highlighted in pink could be reduced by automated data extraction.

How could these errors be avoided with automatic data extraction?
1. Automatic extraction of purchase dates could prevent the user from using the expense submission date
2. Automatic extraction of receipt amounts could prevent input errors
3. Automatic detection of receipt photo blur or underexposure could prompt the user to take a new photo
4. A mismatch of reported amount and extracted amount could result in a prompt to either double check the amounts or to add a comment with the submission explaining why there is a discrepancy (for example requesting a partial reimbursement, or supplying another documentation of an added tip)
5. Automatic extraction of VAT could help hosts that need to report it

Furthermore, one of the most important things to validate for a host is that the expense submission matches the submitted receipts. If we want to allow hosts to automatically pay out expenses in the future under certain conditions, one vital validation is to check that the receipts are valid and match what the expense submitter is claiming.

In addition, many modern accounting and expense management platforms extract data from receipts and invoices to save time for expense submitters. This functionally will most likely soon be expected by users, as it become cheaper and easier to integrate such features. Thus, an additional friction is to improve what will soon be perceived as an outdated user experience and make the platform more user friendly.

There are multiple services on the market that allow us to extract data from financial documents through an API that we could integrate to the platform. @aerugo  has tested two such services, Klippa and Mindee, on 100 expenses from OSC, OCF and OCE.

After evaluating these services, he recommends to go with Klippa, as the error rate of Klippa seems lower than that of Mindee (based on the sample of 100 expenses), and their customer support is better. Klippa also comes with evaluation of document quality, something that Mindee lacks.

https://www.loom.com/share/9d0f382906c242248b749c1c4af79f9e?sid=1f97a67c-685c-4064-b311-b44a5b27fd3a

A drawback of Klippa is that we need to commit to a fixed price after estimating our annual volumes, while Mindee offers a pay-as-you-go plan at a competitive rate. Extracting data from all documents submitted to our first party hosts would cost around $5000 per year with Klippa. 

After implementing this for our first party hosts we will consider if/how to make it available to other hosts.

## MVP

It would work like this:

1. A user uploads a receipt.
2. When the receipt has been saved, we send the URL to the OCR API
3. Get back the data and pre-fill the amounts and dates (if the result is confident enough)
4. Save the JSON as a blob in the database with the expense, in case we want to check the amounts we get back from Klippa agains what the user inputs or make use of some of the other data in future validation features.
5. Display the uploaded document and prefilled data, and prompt the user to double check before submission.

## Traps

Even if the error rate is low, there will still be cases where the OCR software gets it wrong in situation where the user would have gotten it right on their own. In these cases, we need the user to correct the error made by the model. If it turns out that users will blindly trust the data extraction, it is possible that this would increase the error rate. However, based on my experience with evaluating these services, the errors are usually not subtle. They are often in the category of adding a digit in front of the amount, or mistaking some other number in the document for the amount. I find it likely that such errors would be caught by the user or the collective admin.

It is also important to have a fallback strategy in case the OCR API does not respond, to not leave the user hanging in case of service outage. 

## Boundaries

This feature is initially going to initially be only to 1st-part hosts. 

Automated data extraction from documents also allows us to implement validation features. For example:
 - Klippa generates unique hashes of every document they parse. We could use the Klippa attachment hash to validate that the receipt or invoice has not already been submitted to another collective on a host that uses automated data extraction. - 
 - If the expense submitter changes the amount, we could prompt them with the instructions to leave an explanation in the comments if requesting partial reimbursement etc.
 - If Klippa thinks the receipt is blurry, we could ask the user to confirm that he photo is clear and well lit.
 - We could automatically extract VAT from receipts, potentially allowing fiscal hosts with commercially active collectives to deduct VAT of collective expenses.

However these things are NOT within the scope of this project. In this project, we limit ourselves to implementing Klippa in the expense submission flow and will only do automated data extraction.

## Scoping

![image](https://github.com/opencollective/opencollective/assets/7785081/37a5c615-0477-465e-a401-4d655c0efe0e)
We would implement automated data extraction when adding an expense item or invoice.

Note: All sketches below are extremely rough and not at all indicative of the actually UI/UX. Notes in red & blue.

![image](https://github.com/opencollective/opencollective/assets/7785081/e03a3de0-a348-4956-b132-4dd39051268c)
When uploading a document, there would now be a loading-indicator in the attachment box, the date box and the amount box.

If loading the data from Klippa takes more than 10 seconds, we assume the service is down and stop the loading indicator in the UX (but we might still wait for some while longer in the background, TBD by developers).

If the user has already selected a date or entered the amount before uploading the document, we still load the Klippa data in the background but do not replace the users input.

Compared to the current implementation, the default Date value should be empty - not the current date (which is almost always wrong anyway, because the intended use is to input the date the expense was incurred).

![image](https://github.com/opencollective/opencollective/assets/7785081/d48c5b8d-9d82-47d6-a32f-e31c82c826d5)

**In the first release, this feature should be limited to first party hosts.**

**Comment by aerugo** [comment] 2023-07-11 16:08
Edit: Added the scoping from my original Make OC pitch.

**Comment by Betree** [comment] 2023-07-12 06:19
An issue [already existed](https://github.com/opencollective/opencollective/issues/6793) for this, I closed it in favor of this one.

Also related: https://github.com/opencollective/opencollective/issues/1862

**Comment by Betree** [comment] 2023-07-27 08:08
Some notes on this project:

## About privacy

Invoices can contain very sensitive information, such as payment information (bank routing numbers). Since we'll share this information with a new third party, it should be mentioned in our privacy policy. 

While reviewing it, I noticed that our [privacy policy](https://opencollective.com/privacypolicy) was actually lacking an explicit list of the third parties we use, I thus opened https://github.com/opencollective/opencollective/issues/6896 to make sure we address this in a consistent way.

## About using an open-source / self-hosted solution

As per a discussion with @aerugo on whether we explored the idea of relying on opensource / self-hosted solutions like https://github.com/clovaai/donut, he replied:
> I did not look at this particular one, but I focused on hosted API services for the following reasons:
> - I did not find any self-hosted open source models that were trained to deal with receipts and invoices in all languages we would want (the donut models, for instance, are only trained on English, Chinese, Japanese and Korean)
> - Even if the parsing might perform well with an open source model, the other part of the workflow is sorting out the information to extract the total amount, VAT, currency, merchant etc. Klippa and other hosted services do this very well.
> - We would be responsible for updating the model, keeping track of when new models are released and deploying them. With Klippas we outsource this to their engineering team, meaning that our small team does not have to be dependent on in-house machine learning expertise.
> - Given that the price of parsing all of the first party host documents with Klippa is equivalent to about 2-3 weeks of senior developer time, it seems like a good deal.

Though it could have been great to discuss this with the broader team, I think going for a hosted solution is the right call at this stage. Given how small the engineering team is, we tend to prefer using hosted services when possible.

**Comment by Betree** [comment] 2023-07-28 11:00
Some notes from kickoff call:
- We need serious Rate limits. Rate limits should not crash the page, only prevent prefilling (maybe with a warning)
- We'll go with 1 single Klippa account, because we need to reach a certain volume of documents to keep API access. OC Inc will figure out how to charge hosts for the service.
- We could use the "blurry" info from Klippa to put a warning in the interface (e.g. This doc is not clearly readable). However @aerugo says this info was not super reliable during his tests.
- Klippa returns structured data about taxes, we should either integrate or create follow-up issues about implementing that.
- We may not want to use Klippa's generated description, as per @aerugo it's usually pretty bad
- We need to blank the date by default, to differentiate between empty and pre-filled (+ having today's date by default in there is misleading and wrong 99% of the time)
- We'll need to figure how to handle currency mismatches:
   - We can automatically convert, but we'll need to surface FX rate very clearly
   - Otherwise we can start with not prefilling amount when item currency is different from expense's currency
- Engineering will make a proposal for the loading states & graceful failures if Klippa errors / timeouts
- We should keep the raw Klippa data in expenses (for debugging, and in the future for host security checks)

**Comment by aerugo** [comment] 2023-07-28 11:16
In the kick-off call with @aminakazi, @Betree, and @BenJam, we surfaced that currency has a more complicated scope than I initially anticipated. A user might upload receipts in different currencies with the same expense. In these cases, which currency do we choose for the expense? @Betree has the experience of uploading receipts in multiple currencies to the same expense for his collective, and when this happens, he usually picks a currency and converts the others himself. 

We could automatically set the currency of the expense to the currency detected by Klippa for (probably) the first receipt uploaded and automatically convert amounts to that currency if the user uploads receipts in other currencies. However, we must show the user we have done it and expose the exchange rate.

@aminakazi will look at this problem from a UX perspective. We discussed leaving this out of this project's scope, but given that currency conversions are annoying for users to do (and the cause of a fair number of incomplete cases) we decided to include it in the scope. If we do not find a satisfactory UX solution, we default to not automatically setting the amount of an expense item if Klippa determines that the currency is different than the currency of the expense.

**Comment by Betree** [comment] 2023-07-31 09:04
# Project To-do

## Core issues
- https://github.com/opencollective/opencollective/issues/6900
- https://github.com/opencollective/opencollective/issues/6901
- https://github.com/opencollective/opencollective/issues/6902
- https://github.com/opencollective/opencollective/issues/6903
- https://github.com/opencollective/opencollective/issues/6904
- https://github.com/opencollective/opencollective/issues/6905

## Stretch goals
- https://github.com/opencollective/opencollective/issues/6906
- https://github.com/opencollective/opencollective/issues/6907

**Comment by Betree** [comment] 2023-07-31 09:08
This week:
- [ ] https://github.com/opencollective/opencollective/issues/6900
- [ ] https://github.com/opencollective/opencollective/issues/6902

**Comment by Betree** [comment] 2023-08-07 06:47
This week:
- [ ] https://github.com/opencollective/opencollective/issues/6903
- [ ] https://github.com/opencollective/opencollective/issues/6901

**Comment by Betree** [comment] 2023-08-14 08:36
This week:
- [ ] Merge open PRs
- [ ] https://github.com/opencollective/opencollective/issues/6904

**Comment by Betree** [comment] 2023-08-21 12:15
This week:
- [ ] Merge rate limiting
- [ ] Internal release: Enable access for the core team

**Comment by BenJam** [comment] 2023-08-21 13:09
- [ ] @aminakazi  to clean up layers in design otherwise ready to roll

**Comment by aminakazi** [comment] 2023-08-22 13:50
Design file can be [found here](https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/%5BOC-Design%5D-Production-Ready-%E2%9C%85?type=design&node-id=21313-18966&mode=design&t=3DrtHufx3PoXvGqc-11)

Lottie JSON for the animation is attached in this [Slack thread](https://opencollective.slack.com/archives/C05M63GFHPB/p1692712150527689). 

We'll need @jpjhill 's help with the content to inform users to check the amount and date.

**Comment by jpjhill** [comment] 2023-08-22 14:01
Happy to help. Gimme a holler to chat if you like.

**Comment by Betree** [comment] 2023-08-28 12:37
This week:
- [ ] https://github.com/opencollective/opencollective/issues/6909
- [ ] Look at the stretch goals, especially design-related ones

**Comment by Betree** [comment] 2023-09-01 13:54
Feedback issue: https://github.com/opencollective/opencollective/issues/6965

**Comment by BenJam** [comment] 2023-09-11 13:06
- [ ] @znarf and @aminakazi to run through proposed design
- [ ] review feedback (pause 'til ben is back)

**Comment by kaylarep** [comment] 2023-09-12 19:47
> looks like there's a problem with long-form invoices. Examples from @kaylarep and @poohlaga. Proposed that we only enable this for receipts, not invoices.

(My issue came from a receipt, not an invoice)

**Comment by BenJam** [comment] 2023-09-25 13:11
- [ ] take this week to implement the loading state. 

Given we are taking this week, we have the opportunity to adjust given some feedback from early usage:

- [x] remove line by line itemisation 
- [ ] remove OCR from invoice path

**Comment by Betree** [comment] 2023-09-27 07:17
Follow-ups on this project that won't be addressed this sprint (will update):
- https://github.com/opencollective/opencollective/issues/7010
- https://github.com/opencollective/opencollective/issues/6906 (needs design)
- https://github.com/opencollective/opencollective/issues/6907
- https://github.com/opencollective/opencollective/issues/6925
- https://github.com/opencollective/opencollective/issues/6905

**Comment by Betree** [comment] 2023-10-02 07:00
This week:
- [ ] Merge & deploy https://github.com/opencollective/opencollective-frontend/pull/9400
- [ ] Complete & merge https://github.com/opencollective/opencollective-frontend/pull/9403
- [ ] If enough time, look at https://github.com/opencollective/opencollective/issues/6906

**Comment by Betree** [comment] 2023-12-11 08:29
Closing this project as the base feature is now implemented and released. We're following up this sprint with https://github.com/opencollective/opencollective/issues/6906 + https://github.com/opencollective/opencollective/issues/7153.

**Closed** 2023-12-11 09:26 UTC
