### ISSUE TITLE
"Unexpected Error" when trying to view transactions page

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective#1898] opened 2019-04-03 22:08 UTC
**Describe the bug**
This was reported by a user, and when I tried to reproduce it's happening to me as well.

<img width="1268" alt="Screen Shot 2019-04-04 at 11 07 16 AM" src="https://user-images.githubusercontent.com/5498878/55516495-d7c5f200-56c9-11e9-80cc-72fa6b309377.png">

**To Reproduce**
1. Go to 'transactions' under the user menu

**Comment by Betree** [comment] 2019-04-04 06:35
Duplicate of #1872. This is not an easy one, it seems to come from a library we're using. I've prioritized it.

**Closed by Betree** 2019-04-04 06:35 UTC
