### ISSUE TITLE
Custom text missing from receipts

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#5009] opened 2021-12-01 21:07 UTC
OCF has set custom text for receipts:

![Screen Shot 2021-12-02 at 9 19 14 AM](https://user-images.githubusercontent.com/5498878/144313700-80e04ffd-2088-48dc-95cf-cc4356a69cb6.png)

But it's not appearing on the file:

![ocfreceipt](https://user-images.githubusercontent.com/5498878/144313673-1980fe94-dc44-4e40-8b3e-6f7a6bc1c580.jpg)

The same thing is happening for other hosts (Gift Collective for example).

This is a very big problem because these details are required for tax deductibility. We need to investigate this and then re-issue all receipts that went out missing custom text. We're already getting complaints from people trying to claim their tax credits in NZ for Gift Collective contributions.

## P1

**Comment by Betree** [comment] 2021-12-02 09:02
- [ ] Deploy fix (https://github.com/opencollective/opencollective-api/pull/6913)
- [ ] Generate affected users emails list
- [ ] Prepare email
- [ ] Send email

**Comment by alanna** [comment] 2021-12-06 20:08
What's the update on this? I'm very concerned about invalid receipts going out for our tax deductible hosts especially.

**Comment by Betree** [comment] 2021-12-07 12:36
@alanna It has been fixed in https://github.com/opencollective/opencollective-api/pull/6913. I prepared a query to get all the affected users, but we're dealing with a lot of them here so I'll need help with the copy and sending (Mailchimp seems like the right tool).

**Comment by alanna** [comment] 2021-12-11 23:23
@Betree can you please give me a data export of the affected users? I can take care of sending the message to them.

**Comment by alanna** [comment] 2021-12-11 23:24
Also can you give me an export of admins of affected hosts? I will send a separate email letting them know.

**Comment by Betree** [comment] 2021-12-31 09:54
The root cause was fixed with [opencollective-api#6913](https://github.com/opencollective/opencollective-api/pull/6913) and an email has been sent to concerned users.

**Closed by Betree** 2021-12-31 09:54 UTC
Labels: bug, complexity → simple, api, P1
