### ISSUE TITLE
Display the budget section as soon as there is an expense

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#3859] opened 2021-01-17 02:57 UTC
Currently, if you don't have any transactions the entire budget section is hidden. This means if you have expenses but no transactions yet, you can't see those expenses. We encourage users to submit expenses even before they have any money, so I think we need to reveal that section as soon as there is an expense.

Related: #3846

**Comment by znarf** [comment] 2021-01-18 10:21
The problem is that there is no "Expenses" section on the Collective page itself, only a "Budget" section that is only containing a link to "View all expenses".

@Memo-Es what can we do here?

**Comment by alanna** [comment] 2021-01-18 21:29
I think it would be OK to show the whole budget section to reveal the expense, even if it just said `$0`.

**Comment by Betree** [comment] 2021-01-19 08:37
> I think it would be OK to show the whole budget section to reveal the expense, even if it just said `$0`.

The budget section only show transactions, so expenses only appear there after they are paid. If we decide to display it as soon as there is an expense, we'll need to have an empty state for this section.

However, if the main goal is to have a link to the expenses page, it's something that I think was resolved by the new navbar. We (the core team) may not be used to it yet because we have our old habits, but there is a link in there to view all expenses: 

![image](https://user-images.githubusercontent.com/1556356/105008432-84a56680-5a39-11eb-82ab-af93e62b0bc9.png)

**Comment by znarf** [comment] 2021-01-19 08:49
@Betree problem is that the "Budget" menu item is not appearing until you have one transaction, right?

**Comment by Betree** [comment] 2021-01-19 15:25
> @Betree problem is that the "Budget" menu item is not appearing until you have one transaction, right?

I just checked and you're right, though this is not the behavior that we wanted to implement initially. The "Budget" category should be displayed in the navbar in this case. @alanna would that solve the issue?

**Comment by znarf** [comment] 2021-01-19 15:39
@Betree Then what would be the behavior when clicking on "Budget" if there is no budget section? Nothing?

**Comment by Betree** [comment] 2021-01-19 15:41
> @Betree Then what would be the behavior when clicking on "Budget" if there is no budget section? Nothing?

Yes. That can be a bit counter-intuitive. @Memo-Es any opinion on that topic?

**Comment by znarf** [comment] 2021-01-19 15:44
@Betree sounds like a good solution though even if not perfect.

**Comment by Memo-Es** [comment] 2021-01-19 17:05
We can update the budget section to display something like this:

<img width="1434" alt="Screen Shot on 2021-01-19 at 11-02-51" src="https://user-images.githubusercontent.com/49539954/105068013-04d1c900-5a46-11eb-858b-90148889f81a.png">
 
We can add an empty state for transactions or just don't display the option if there are no transactions yet, what do you think @Betree

**Comment by Betree** [comment] 2021-01-19 17:08
> We can update the budget section to display something like this:
> 
> <img alt="Screen Shot on 2021-01-19 at 11-02-51" width="1434" src="https://user-images.githubusercontent.com/49539954/105068013-04d1c900-5a46-11eb-858b-90148889f81a.png">
> 
> We can add an empty state for transactions or just don't display the option if there are no transactions yet, what do you think @Betree

We used to do this in the first version of the collective page. It adds a bit of complexity (because it's mixing transactions with expenses), but actually that's not too difficult to do in the frontend.

> We can add an empty state for transactions or just don't display the option if there are no transactions yet, what do you think 

An empty state could be useful, at least for admins.

**Comment by alanna** [comment] 2021-01-19 20:17
I think revealing the budget section and showing the pending expenses there is the best solution. From the user's point of view, they just want to transparently show or view anything that affects the budget, and pending expenses are part of that.

**Comment by Betree** [comment] 2021-01-21 10:47
@kewitz since you implemented the update to this budget section, do you have any objection to the idea of re-implementing something like we had before where in the frontend we fetch 3 expense + 3 transactions, mix them and display the 3 first entries (regardless if they're transactions or expenses)? 

I think we got rid of this for the sake of simplicity, but I don't remember if there were other reasons

**Comment by kewitz** [comment] 2021-01-25 13:19
I don't have any technical objection to that.

**Comment by Betree** [comment] 2021-01-26 11:00
Let's go with that then. We'll need to make sure that section data is still properly cached.

**Comment by Betree** [comment] 2021-02-04 11:16
Amina shared the design for the empty state: https://www.figma.com/file/ZQBMWhnGGtRWeIZknFW1eP/OC.com-Production-Ready-%E2%9C%85?node-id=9923%3A0

**Closed** 2021-02-10 19:08 UTC
Labels: complexity → medium, design, enhancement, expenses, frontend
