### ISSUE TITLE
Map on event page super zoomed out

### ISSUE THREAD

**Issue by alanna** [opencollective/opencollective#2845] opened 2020-01-22 23:33 UTC
This is the default view of the map location on [this event](https://opencollective.com/open-source-speed-dating/events/open-source-speed-dating-fosdem-2020-96f78c6c). It should be zoomed in to at least the city.

![Screen Shot 2020-01-23 at 12 29 13 PM](https://user-images.githubusercontent.com/5498878/72943988-7ef05300-3ddc-11ea-8c62-8558d896de76.png)

**Comment by maddhruv** [comment] 2020-01-23 01:57
@alanna It doesn't seem to be happening at https://opencollective.com/open-source-speed-dating/events/open-source-speed-dating-fosdem-2020-96f78c6c#section-location

![Screenshot from 2020-01-23 07-26-51](https://user-images.githubusercontent.com/18121502/72950579-ce6d5980-3db1-11ea-85ec-fb7c8f513ee1.png)

**Comment by daud1** [comment] 2020-01-23 02:01
Doesn't seem to be happening for me either.
![image](https://user-images.githubusercontent.com/30657749/72950701-25b4ff00-3d9d-11ea-9807-f761d7be3419.png)

Perhaps you attempted scrolling the page while the cursor was hovered over the map area?

**Comment by znarf** [comment] 2020-01-23 07:32
Works for me too. But I also can see what happened to @alanna  

1. go on this page on desktop
2. put your cursor at the middle of the screen
3. start scrolling to the bottom and try to reach the bottom (using mouse wheel or touchpad)

The map is hijacking the scroll event and instead of scrolling to the bottom, you're starting to zoom out in the map.

**Comment by maddhruv** [comment] 2020-01-23 07:35
@znarf for me it is just scrolling (zooming out/in) the map when the cursor is out of the map box

**Comment by Betree** [comment] 2020-01-23 08:40
@maddhruv but @znarf didn't say the opposite, he just said that when you scroll the page then arrive on the map it hijacks your scroll (because your cursor is on the middle of the screen). Which I agree with, Google Maps used a combination of Ctrl + scroll to prevents this.

However the issue described here by @alanna is real, I was not able to reproduce on Firefox but on Google chrome (Version 79.0.3945.130) yes - it was zoomed out upon loading:
![image](https://user-images.githubusercontent.com/1556356/72968719-5bb9a980-3dc4-11ea-9e07-d953e2220b8a.png)

**Comment by piamancini** [comment] 2020-01-23 09:28
I had the same issue as @alanna

**Comment by znarf** [comment] 2020-02-04 09:58
It's confirmed to be linked to the mouse scroll event. If you use the right scrollbar, it's working fine.

**Comment by znarf** [comment] 2020-02-04 09:58
A $100 bounty was attached to this issue. Anyone submitting a Pull Request will be rewarded with $100 when the Pull Request is reviewed, accepted and merged. [More info](BOUNTY.md).

**Comment by Betree** [comment] 2020-02-04 15:16
> It's confirmed to be linked to the mouse scroll event. If you use the right scrollbar, it's working fine.

I can still reproduce using only the scrollbar:

![Peek 04-02-2020 16-15](https://user-images.githubusercontent.com/1556356/73757525-a0045c80-4769-11ea-8453-6044d8d7d548.gif)

**Comment by znarf** [comment] 2020-02-04 15:57
@Betree Good to know. Just confirming it works for me on Chrome / Mac OS when using the right scrollbar.

**Closed** 2020-02-17 08:46 UTC
Labels: $100, bounty, bug, complexity → unknown, events, frontend

**Comment by Betree** [comment] 2020-02-17 15:15
:trophy: This issue has been completed by @joshikeno  

To claim the **$100** bounty, you can either:
- Submit an invoice to https://opencollective.com/engineering/expenses/new (please mention the issue number in the expense's title)
- Or ask for an Open Collective gift card of the same value (to donate to other collectives)
