### ISSUE TITLE
Collective Page → How to get to the expenses page? (EPIC #1928) 

### ISSUE THREAD

**Issue by mixmix** [opencollective/opencollective#1428] opened 2018-11-11 10:53 UTC
## Problem 

I go to https://opencollective.com/secure-scuttlebutt-consortium and I want to see if there are any invoices to approve, I want to go to the expenses page ... I scroll down and see a bunch of stuff I don't want / need as an admin, then I see a summary of things which have been paid but no clear indication of whether there are any outstanding.

current solution ... remember I need to go to https://opencollective.com/secure-scuttlebutt-consortium/expenses  ):

## Possible solutions

- if there are no expenses to approve, say that
- create a section of "admin/ coordinator" actions which includes:
  - edit collective
  - approve expenses

## Referenced Issues
#1928

**Comment by mixmix** [comment] 2018-11-11 10:55
said differently : as an admin, when I land on the page I want the tools I'm going to use immediately visible. I don't want to go scrolling looking for things, and I don't want to have to rely on my memory or bookmarks

**Comment by alannallama** [comment] 2018-11-11 20:35
As a host admin, I use a whole list of saved URLs in a document, because it's so many clicks to get to the page to manage the expenses approvals and payments. So I agree the current design isn't ideal.

**Comment by mixmix** [comment] 2018-11-11 20:44
yeah finding people using hacks is usually a really great validation that there's a new feature or different design emerging

**Comment by piamancini** [comment] 2018-11-12 15:13
cc/ @cuiki Please take this into account when we re-design the page. 
A link to the host dashboard is also needed.

**Comment by alannallama** [comment] 2019-04-25 01:34
Will this be fixed on the new Collective page?

**Comment by cuiki** [comment] 2019-04-25 01:45
Yes, @alannallama . :)

**Comment by piamancini** [comment] 2019-09-26 07:44
reopening this as it's still an issue. 
@lindatalu please only close issues created by design, not issues tagged design thank you!

**Comment by Betree** [comment] 2019-12-12 15:03
This should be resolved in the new collective page where we implemented a `View all expenses` button.

![image](https://user-images.githubusercontent.com/1556356/70723289-f1a7e200-1cf8-11ea-9eeb-c884e2fd92b7.png)

**Closed by Betree** 2019-12-12 15:03 UTC
Labels: design, design → UI, design → UX, design → community request, enhancement, expenses, figma → Collectives

**Comment by mixmix** [comment] 2019-12-12 15:31
Sweet, thank you.

Design feedback : I see two sorts of filter active in this design
1. How much do you want to see? (recent/all)
2. What sorts of transactions do you want to see (transactions/ expenses)

As a collective admin I always have to pause and think what the
relationship between transactions and expenses is. I want it to be clearer
by e.g.
- showing me which filter is currently active (I think by default it's
transactions yeah?)
- use different language like "all transactions" and "just expenses"
- have 3 options : all / contributions / expenses

Messing with these filters collides with the "show all X" "show all Y"
design. I think that should be replaced with a "Show more" button which
takes you to a full page which has the same filters for exploring the data
(all / contributions / expenses) .

**Comment by Betree** [comment] 2019-12-12 15:42
The one you're talking about is slightly different than what's discussed in this issue: it's the section displayed on your **user profile** (ie. https://opencollective.com/betree#section-transactions), not the **collective budget** (ie. https://opencollective.com/secure-scuttlebutt-consortium#section-budget).

> Messing with these filters collides with the "show all X" "show all Y"
design. I think that should be replaced with a "Show more" button which
takes you to a full page which has the same filters for exploring the data
(all / contributions / expenses).

I agree, #2434 was started with this intent. We still need an input from the design team to go ahead with this change but that's something we want to do.

**Comment by mixmix** [comment] 2019-12-12 16:03
Oh, I've never seen the user profile! (eg
https://opencollective.com/betree#section-transactions).
That's *exactly* what I want.
