### ISSUE TITLE
Assist Adam from Colly Collective with flexible tiers

### ISSUE THREAD

**Issue by nicobarretoOC** [opencollective/opencollective#858] opened 2018-01-24 03:50 UTC
User would like flexible tiers like the ones on Webpack. 
This is the collective URL:
https://opencollective.com/colly

**Comment by xdamman** [comment] 2018-01-24 05:00
Duplicate of https://github.com/opencollective/opencollective/issues/853

**Closed by xdamman** 2018-01-24 05:00 UTC
Labels: support
