### ISSUE TITLE
Support Metrics Report September 2021

### ISSUE THREAD

**Issue by alinamanko** [opencollective/opencollective#4780] opened 2021-10-05 01:33 UTC
### Support Metrics Report September 2021
This report looks at the trends around support to help us better understand areas we need to improve and highlight key topics for the month. 

**Tickets received** 

![capture](https://user-images.githubusercontent.com/57156267/135945668-f1342666-b975-4951-89c3-52fc543edf20.png)

The number of tickets received seems to be quite consistent - with a slight increase from 1,659 in August to 1,678 in September. By removing blank tickets and expenses notifications where no actions were required, the rise during September was at about 10% with 644 tickets compared to 585 in August. [You can find the working files here. ](https://docs.google.com/spreadsheets/d/1pO6FQzpxUXpBms43J94rxhX4toU2IP3S/edit#gid=1005618264)

The tickets contribution across the teams was as shown below:

![capture](https://user-images.githubusercontent.com/57156267/135945801-9ea68fd5-86cb-403d-93d5-be88a2ea3ad3.png)

I think it is worthwhile to note that this distribution will also include any tickets automatically assigned to a specific agent through the automations on FD where no actual action may be required. So, for example, under Operations Support we will have all the expense comments that may not require the team time and tickets that are automatically closed. So thinking about this element the distribution showing here may be quite skewed and this is something worth noting. I am looking into how to improve this representation, to provide more accurate information. 

**Trends and Recommendations**
After removing irrelevant tickets, we had 644 that required support attention. Here is the summary of the common areas of questions - please note I took out the Expenses and Onboarding topics as these are addressed separately and would make a large portion of the questions we handle.

![capture](https://user-images.githubusercontent.com/57156267/135945976-591b3904-e833-4ddd-b27a-30e7393fd688.png)

Below are some notes on these trends:

**Virtual cards**

The issues with Privacy and restrictions applied on our accounts (mostly on the OCF end) have not been resolved yet. Looks like some of the restrictions are coming through our bank, however, the interactions with Privacy were still time consuming during September and we are currently looking into alternative service providers, with conversations with Stripe currently taking place. 

**Tax**

This month we saw an increase in questions related to local tax issues and it was great to have a quick response from the team in the form of giving the fiscal hosts the option [to incorporate local tax elements](https://docs.opencollective.com/help/fiscal-hosts/local-tax#vat) (VAT/GST) to allow for easier reporting and meeting local compliance.

A common question received is when users follow up on the status of the invoice they submit when they don’t realize tax form needs to be completed (or they may miss out on the email from HelloWorks with the link to the form). We did, however, received this lovely feedback from OpenMined on the use of the Tax Form tag on approved expenses and it seems to be an appreciated feature.

**Grants/Contributions**

This keeps on being a lead topic with notifications received on contributions or grants we receive from initiatives hosted (mostly) through OCF. 

Following from [the onboarding pains experienced with The Week](https://opencollective.slack.com/archives/G013S279X63/p1631733047163000), one of the issues was a missed contribution I wanted to see if the process could be improved or whether we could take a certain element into account. In their particular example, we received a number of very significant contributions (a few lots of $100k). They initially processed these through the platform, recording them as bank transfers and hence recording pending orders. But later, these amounts starting coming outside of the platform, and given similar amounts, creating some confusion when reconciling the bank with the platform on our end. As a general rule, the ideal situation would be to encourage users to use the platforms to record these larger transfers and while this is not something we can easily regulate now, it would be fantastic control to have in place. 

I wonder if there is a way to create an easier flow for instances where a Fund sends $$ to update their budget. There is no easy way to add these funds using the frontend and we would normally assign these requests to Pia which creates an additional burden and slows the process down given the limitation on the users who can make the update. 

**Lost/project support**

Instances, where users get in touch with support directly when in fact they are looking to connect with a specific project, continue to be quite common. We think that with the introduction with the new support page these types of questions could be minimized. In the meantime, we are sending a general response to these users to minimize our engagement with these questions. Basically, an email is sent asking them to contact the collective they are after directly. 

**Payment methods/Payment errors**

Tickets related to payment methods remain at a similar level we received during August. With the introduction of crypto, we had a handful of inquiries, but these were (for now) coming from collectives _not_ hosted with OSC. It will be interesting to see how the uptake here may look as we move forward.

Just a quick comment to say tickets tagged as ‘payment error’ relate both to issues with contributions and also some expenses where users experienced some issues were classed into that category. 

**Expenses and Onboarding**

It seems like it would make sense to aggregate these categories into a separate section to look at some of the trends we can witness. Below is a more detailed description. 

**Expenses**

Common issues during September and other topics worth noting and weren’t flagged last month:

- The selection of Payout Method can sometimes be problematic when the user will choose the Other method. It most often happens for collective hosted with OCF where users are looking to be reimbursed through cash app or Venmo. Can we perhaps make it clearer Open Collectives don’t support these payout options?
- This is related to the above. Payout methods such as AliPay for users based in China are something that can be updated under bank transfer though we are not able to support this option. Is it possible for us to make an easier identification on what is allowed or not? We’d likely need to gather this information to allow for docs/expense forms update first. Right now it slows the process of getting money sent to China quite significantly and takes time out of support to help the user navigate through the other options available. 
- Expense editing option continues being a common trigger for some users (we are already aware of that)
- We still see a lot of bank transfers requests to India (mostly through bounty contributors on some OSC collectives - huntr specifically). This is something we need to be extra careful about catching early and not processing given the risk of our Wise account being deactivated if we accidentally [breach the policy around those payments.](https://wise.com/help/articles/2932151/guide-to-inr-transfers) 

In addition, there are a couple of updates you should be aware of:

- While our policy on processing expenses is still twice a week (every Monday and Thursday), as of last week we experiment in getting OCF expenses run on a daily basis to see whether this is something we could transition to more formally in the short term as we are looking to see what is our capacity in this space.
- We are now experiencing some issues with the OSC account on Wise. It seems like some notifications sent to us went to spam and they paused our account making it impossible to process payments to OSC hosted collectives. Given it happens now that monthly invoices are raised is far from ideal, but we hope this will be resolved ASAP.

**Onboarding**

Onboarding related questions are still some of the common ones we receive. There is a 13% decrease in the number of new initiatives joining OCF and a 7% decrease for OSC. Here is how it was distributed:

We approved 21 new applications for OCF in September compared with 24 in August.

For OSC -  71 new collectives were approved this month compared to 76 in August.

**Comment by alanna** [comment] 2021-10-05 02:44
Some takeaways for me...

* Virtual cards / Privacy is killing us right now - so painful
* We should implement #4754 to reduce the onboarding support load
* A pull request was just merged to introduce custom OCF onboarding emails, so hopefully that will reduce the load on main support
* Do we have a second automated reminder to fill out the tax form if it's been sitting a while?
* #4024 and #4497  would really help with the problems caused by people not setting up transactions on the platform before sending a check/bank transfer, leading to confusion about matching up the money
* The new contact/support page can't come fast enough
* Maybe we should give hosts the option to turn off the user-defined manual payout method option (especially if we have #4024 )
* #4715 would help support load

> I wonder if there is a way to create an easier flow for instances where a Fund sends $$ to update their budget. There is no easy way to add these funds using the frontend and we would normally assign these requests to Pia which creates an additional burden and slows the process down given the limitation on the users who can make the update.

Can't we do it via added funds like normal, and can't they contribute to their Fund as a normal contribution? Or is the issue that Funds often have contributions turned off?

**Comment by alinamanko** [comment] 2021-10-05 02:53
Great summary @alanna! My two cents in regards to the funds question (take it with a grain of salt as I am not fully familiar with the flow though) is that fund setup is different atm to that of a collective and the whole budget section is restricted in its view, making it impossible to add the funds from the platform end as we would do for collectives and this is why the process is entirely different. I would love to see an easier process here where a similar flow could be followed. I think there were some restrictions as to why it was designed in that way but would need more feedback from the wider team on this one

**Closed** 2021-11-23 15:23 UTC
Labels: support
