### ISSUE TITLE
Guest account to User account Link

### ISSUE THREAD

**Issue by shannondwray** [opencollective/opencollective#6419] opened 2023-02-15 05:40 UTC
## What are they trying to achieve?
When a guest account is activated to a user account should the old guest account link redirect to the new user account link? 

## How are they currently doing this?
Currently the guest account comes up as not found after the account has been activated 

## How well understood is this problem?

 - [ ] Surfacing: if you feel this is a seed of an idea that needs to be researched.
 - [ ] Understanding: if you've done some research and feel it is already well understood and ready for shaping.
 - [ ] Shaping:  if you feel a solution is clearly defined and can be made into a pitch ([read more about shaping](https://basecamp.com/shapeup/1.1-chapter-02))
 - [ ] Pitching: if you feel that it is ready to be presented for prioritisation ([read more about pitching](https://basecamp.com/shapeup/1.5-chapter-06))

**Comment by Betree** [comment] 2023-02-21 07:53
> should the old guest account link redirect to the new user account link

Guests' profiles are empty and don't provide any meaningful info; therefore, they're not supposed to be linked from anywhere. In this context, it doesn't really make sense to redirect the old URL to the verified profiles.

The issue doesn't tell much about what we're trying to achieve; is this to assist the support team when they're investigating? What's the path you're following to arrive on a guest profile link?

**Comment by Betree** [comment] 2023-02-21 08:46
@shannondwray Where do you get this guest link? My point is that guests are not supposed to have a link in the first place

**Comment by shannondwray** [comment] 2023-02-21 08:48
https://opencollective-metabase.herokuapp.com/question/1008-user-slug-from-email?email=jrhalsten%40aol.com - If I put an email in here and they have a guest account it gives me a slug

**Comment by Betree** [comment] 2023-03-03 10:17
I suggest not documenting the profile URL for guests in support tickets or finding a better identifier. It's unlikely that we'll ever redirect guest profile URLs to their confirmed profile URLs.

**Comment by shannondwray** [comment] 2023-03-19 02:44
Some users seem to be keeping their guest account links even after activating their accounts - https://opencollective.com/guest-46b0a4b2?

**Comment by Betree** [comment] 2023-03-20 09:47
@shannondwray That's a bug that has been resolved since https://github.com/opencollective/opencollective-api/pull/7313 (they verified their profile on 2022-01-26). We may have a few more like that but not since 2022-03.

**Comment by SudharakaP** [comment] 2024-01-17 16:15
As per the discussion in the [dev issue tracker](https://coda.io/d/Support_dEguIswyoKq/Dev-Issue-Tracker_su5Wl#Tracker_tuKQp/r69) we are closing this issue.

**Closed by SudharakaP** 2024-01-17 16:15 UTC
