### ISSUE TITLE
Bar button in navbar don't work

### ISSUE THREAD

**Issue by nlok5923** [opencollective/opencollective#3132] opened 2020-05-09 09:05 UTC
![Screenshot (804)](https://user-images.githubusercontent.com/56120084/81469361-53ca1d80-9199-11ea-8349-a077517158fb.png)

on clicking bar button in mobile view takes to the bottom of the page. 
Can i work on this issue please let me know.

**Comment by Betree** [comment] 2020-05-13 08:10
Will indeed be resolved by https://github.com/opencollective/opencollective/issues/3009. Also duplicate of https://github.com/opencollective/opencollective/issues/2529

**Closed by Betree** 2020-05-13 08:10 UTC
